### ISSUE TITLE
When selecting a completion from classpath (provided by indexer), don't insert fully qualified name.

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#166]
_From @aemoncannon on February 15, 2015 16:14_

I feel like a more useful behavior would be to insert unqualified while at the same time inserting the import. Thoughts?
##

_Copied from original issue: ensime/ensime-server#830_
##

**Comment by fommil** [comment]
yes, agreed! I think this is a regression as it didn't always do this.

**Comment by fommil** [comment]
_From @ploddi on March 13, 2015 10:42_

👍

**Comment by fommil** [comment]
_From @tonylotts on June 4, 2015 20:55_

:+1:

**Comment by fommil** [comment]
_From @tbje on June 6, 2015 12:55_

+1

**Comment by fommil** [comment]
@e8kor is looking into this. Did you get any further with it? Need any help?

**Comment by e8kor** [comment]
@fommil Hi, feature implemented, but have problem with writing test.

**Comment by fommil** [comment]
@e8kor let us know how we can help! Can you raise a PR maybe as a point of discussion

**Comment by fommil** [comment]
@aemoncannon made some changes server side, but it might mean rethinking the client fix

**Comment by e8kor** [comment]
@fommil @aemoncannon here is diff of fix :
https://github.com/e8kor/ensime-emacs/commit/695e734c1170a8bbcac55cc7fb96f36b4d5c1f69

**Comment by aemoncannon** [comment]
to-insert is meant to be a general way to send an alternative string for insertion which differs from the string typed by the user. It shouldn't be relied upon to carry the fully qualified name of a type. Actually, we don't have a good way to communicate to the client that some extra step (e.g. importing a type) needs to happen after completion.

In any case, I believe this should really be a separate step -- 'fixups' -- where an 'unrecognized symbol' error can be manually or automatically resolved by adding an import. The same framework would take effect when the user pastes a block of code with unresolved types.

**Comment by e8kor** [comment]
@aemoncannon Hi, can you point me to places what you are speaking about, because I didn't understand what from you explanation.

@fommil Please give me some advises about how to simulate "company" completion inside unit test, I did not found examples in ```ensime-test.el```

**Comment by fommil** [comment]
@e8kor I think it's just standard completion actually.  There's got to be an example, I hope!

**Comment by aemoncannon** [comment]
I don't think we do trigger the full company flow in the tests. It's hairy.
Callbacks on timers, etc. Instead we invoke completion rpc manually and
then feed result into yasnippet to make sure the expansion works correctly.

But, to reiterate my previous note: I don't think the completion system is
the right place to be inserting imports. For two reasons:
1) There isn't enough information. Just based on the rpc result, we don't
know if a completion result needs to be imported.
2) We're going to have to handle this in other places anyway: e.g., auto
import on paste, or, what if the user types an unknown class name without
using completion system?

**Comment by fommil** [comment]
@aemoncannon is the TL;DR "don't worry about this, Aemon is going to fix it" :smile:

**Comment by aemoncannon** [comment]
@fommil, yeah. pretty much : )  unless someone gets to it first!

**Comment by e8kor** [comment]
@fommil @aemoncannon there is no reason to hurry as I see, if I started doing it ill gladly complete it, only thing I need is love :)

With respect, IEvgenii Korniichuk

**Comment by aemoncannon** [comment]
Great! :-)

On Wed, Jan 6, 2016 at 1:41 PM, Evgenii Korniichuk <notifications@github.com
> wrote:

> @fommil @aemoncannon there is no reason to hurry as I see, if I started
> doing it ill gladly complete it, only thing I need is love :)
>
> With respect, IEvgenii Korniichuk
>
>
>

**Comment by fommil** [comment]
probably what we want is some kind of auto-import thing like IntelliJ does, for when a class name is written, but not in scope, and the user just typed space (or some set of triggers), but that's a separate ticket.

**Comment by fommil** [comment]
@e8kor do you think you'll get to finish this off? It should be pretty easy nowadays with protocol changes we implemented.

**Comment by e8kor** [comment]
Sorry but I think now, doest have time for that.
