### ISSUE TITLE
standalone / shared scala repl mode with sbt-mode

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#178]
_From @fommil on September 25, 2014 13:44_

I have some work that allows tab completion in the scala repl mode, it would be good to factor this out into a general scala repl mode and enhance our own console (perhaps also to be used by `sbt-mode`)

https://github.com/fommil/unix/blob/master/.emacs.d/lisp/maker-mode.el
##

_Copied from original issue: ensime/ensime-server#627_
##

**Comment by doofin** [comment]
+1
