### ISSUE TITLE
Asynchronous RPC Aborted:...

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#181]
_From @toddleo on June 30, 2015 8:4_

The mini-buffer reports: 

> Asynchronous RPC Aborted: Malformed swank:symbol-designations call: (swank:symbol-designations "/path/to/my/project/src/main/scala-2.10/tjack.scala" 0 34 (var val varField valField functionCall operator param class trait object package deprecated))

as I opened an empty `.scala` file, right after creating `.ensime` using `sbt gen-ensime` command. Annoyingly, this message prompts again everytime I hit any key to make it disappear.

_Copied from original issue: ensime/ensime-server#1026_

**Comment by fommil** [comment]
@edani @ale64bit looks like recent changes have broken the emacs client for older scala 2.10 and 2.9 projects which can't handle the new deprecation symbols (or the implicit symbols). Any ideas?

@toddleo as a workaround, you could always grab a version of ensime-emacs prior to recent changes, e.g. d7c4e86972aa8e9f6feedb93043208728695992b

**Comment by fommil** [comment]
Or upgrade your project to scala 2.11 :wink: (yeah yeah, I know... I have 2.9.2 projects that can't be upgraded...)

**Comment by toddleo** [comment]
Thanks for the quick response, Sam. I am willing to upgrade my project, whereas this project is Spark specific and only Scala 2.10 is officially supported when installing by tarballs. (Scala 2.11 requires build from source, which several failings were reported)

**Comment by fommil** [comment]
we're due a backport of the server to 2.10 in the coming weeks anyway.

**Comment by ale64bit** [comment]
> Asynchronous RPC Aborted: Malformed swank:symbol-designations call: (swank:symbol-designations > "/path/to/my/project/src/main/scala-2.10/tjack.scala" 0 34 (var val varField valField functionCall > operator param class trait object package deprecated))

Strange, the implicits are missing from the designations. I saw a similar error when deprecated was included in the designations but the client wasn't handling it. I will have a look.

**Comment by fommil** [comment]
eric's PR might have excluded requesting the implicits unless the protocol version was high enough. You might want to do something similar for `deprecated` requests.

**Comment by fommil** [comment]
can you check that this is fixed with the next MELPA update please? Reopen if it still persists in an hour or so.

**Comment by fommil** [comment]
and thanks to @ale64bit for a fast response!
