### ISSUE TITLE
Add ability to run tests from difference source sets

### ISSUE THREAD

**Issue by jacobono** [ensime/ensime-emacs#183]
I was almost going to be pressured to switch to in IDE (after the team heard I use Emacs) and I was so happy to be able to smile a big smile and say "I can do what you can do in Emacs with ensime".  :smile: 

So it goes without saying, that I love this package!

I came across a particular use case on a project with an integration test source set, and unfortunately I can't run any `ensime-*-test` commands in that source set.

I think it would be cool if it were possible to do this -- and I'd be more than happy to work on it!

I was thinking that maybe in this case we could incorporate [hydra](https://github.com/abo-abo/hydra) as it seems fitting to me.

Maybe create a custom variable with a default hydra 

- test
- it:test

and some of its other variants, to feed those in to `sbt-command`.  Then if other users need some more additions, they can define their own.

The hydra was just an idea I thought might be cool -- I don't have much else other than the idea, but I would be happy to work on it if you liked the gist of it.

Sorry if this has been implemented and I didn't see it, or if their was another issue open like this.

**Comment by fommil** [comment]
ha! Funny, you know I discovered this limitation while creating the Scala Days talk https://t.co/NYOc5CDy7K

I think it would be easy to fix, actually, so it would be awesome if you could have a look. It boils down to regexes I think. https://github.com/ensime/ensime-emacs/blob/master/ensime-goto-testfile.el#L241

**Comment by jacobono** [comment]
I had some time to take a look and adding another string match 
```elisp
(string-match-p "src/it/scala/$" dir)
```
helps find an integration test in the `it` directory.

Just to check, I added the same test name for an implementation file in `test` and `it`.
Is this a valid use case? I've seen it happen.

Anyway, currently only picks one.

What do you think of [projectile](https://github.com/bbatsov/projectile)? 

I think it is pretty awesome -- I did a little bit of hacking to try and get a different answer for the (possibly) invalid use case I mentioned above, and I was able to get it to work with some minor changes and show a nice choice option in the `mini-buffer` of which test to select.

I thought that was cool.

It looks through all the file names in the project and see if they match against a Suffix `["Spec" "Specification" "Test" "Prop"] and gets the matching file names.

I guess the downside is it only works on file names, not from the top level class.

Could also change functionality in `ensime-get-test-class-info` (and what it feeds in to) to work on lists, but I thought it might be neat to bring in projectile since it is so awesome (top 10 downloaded packages in MELPA or something like that).

What do you think?

**Comment by fommil** [comment]
I tend to find myself using `projectile` a lot for this actially, but yeah it's no good at creating new test files.

Adding the `it` directory (also `fun` for functional tests) would be a good move.

**Comment by jacobono** [comment]
Ya I agree, no good for creating new test files.

What if it was used to find current ones, and if it didn't, default to the
current ensime methods to generate test files?

**Comment by fommil** [comment]
that would add a projectile dependency just for one function... but you could certainly implement a short `deffun` locally to do that instead. Can we expect a PR with the added directories to the ENSIME goto-test search?

**Comment by jacobono** [comment]
You can definitely expect a PR with the added directories at a minimum.

Regarding that dependency for one function -- it is one *top-level* function, but there is **a lot** of extra work going on behind the scenes of that call.  Maybe not everyone has projectile, but my line of thinking is that it is so ubiquitous that including a dependency on it would gain a good infrastructure cheaply -- not reinventing what that project has already done (and tested) -- and if users don't have it, we could expose them to a pretty neat package too.

You could also you use it for finding the implementation file too, so.... 2 functions ;)  haha

All we would need to do is override a `defcustom` that spat out a list of test file extensions ensime projects expect and after that it is good to go.  Could be in a new file `ensime-projectile`.

Not trying to harp, I just think it would be really smooth to go that route.  `ensime` **is** used for scala projects and there is no better project management package than `projectile`.

**Comment by fommil** [comment]
Well there is no point in using projectile when the ENSIME server can do the job for us. I tend to fall back to projectile only when the ENSIME server is having problems.

Of course, the real way to fix this ticket is the distinguish main and test paths in the configuration file. Either we infer that information or we demand it explicitly in the configuration file format. Maybe that's something we should move towards.

**Comment by jacobono** [comment]
I guess I never thought that the server can do that job for us as well. :+1: 

If we could demand the test paths explicitly that would work.  Does the server know about each file in the project, or just compiled class files?

I'm putting in the PR for these directories now.

I think another part of this ticket was that I can't run tests in different source sets -- i.e. only `test` goes through, and not `it:test` or `it:testOnly`.  I can submit a different PR for that.

How much work do you think it would be to get ENSIME server to demand the test paths in the configuration file and move towards what you mentioned?

**Comment by fommil** [comment]
it's almost no work at all, but it will break backwards compatibility and that's going to impact all users.

1. add new filed into EnsimeConfig
2. update ensime-sbt
3. move all users over, supporting the legacy setup until then

at that point, the server wouldn't even need to do any work, the emacs client would know exactly which bases are the test bases.

It's possible to do steps 1 and 2 and maintain backwards compatibility, so we'd definitely accept a PR in that area. The biggest problem would be that using a new version of ensime-sbt with an old version of the server (e.g. scala 2.9 or 2.10) would be broken for people so there is quite a lot has to happen between 1 and 2.

If you send a PR for 1, it is maybe a good time to drop the support for some of the legacy fields like `target` and `testTarget` https://github.com/ensime/ensime-server/blob/master/api/src/main/scala/org/ensime/api/config.scala#L61

**Comment by jacobono** [comment]
I can take a look at number 1.

Do you think something like this has a shot at getting in the next major release?

**Comment by fommil** [comment]
Sure, I don't see why not. We do continuous release, btw

**Comment by fommil** [comment]
I think we need to change the .ensime format to really support intelligent selection of test phases, instead of just guessing.
