### ISSUE TITLE
we don't deal well with moved files

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#184]
if I open a file and then go to dired and rename it, we seem to have both files (the old one now deleted) in the presentation compiler memory.

Maybe this is a server issue and we should periodically filter files that don't exist.

**Comment by reactormonk** [comment]
I'm trying to solve this issue via `(ensime-owning-connection-for-source-file /path/to/file)`, but it returns nil even for a buffer where I just typechecked with ensime.

**Comment by fommil** [comment]
Hmm, that certainly sounds like a bug in itself. if you could write a failing test case just for that function, and fix the bug, that would be awesome. Might be something to do with canonical file names? Which OS are you on?
