### ISSUE TITLE
Search integration with ido

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#186]
or other typical emacs search interaction tools. Having our own front end gives us some options that we might not get --- e.g. choose source or docs. But I think the vast majority of people just want to jump to source in search. If people want search for documentation we can have a separate function for that where the callback is to ask for docs instead.
##

**Comment by tbje** [comment]
Helm does give you this option, one default one and in addition a multiple choice menu.

**Comment by fommil** [comment]
It would be good to integrate with helm if people want it, but I personally can't stand it so it would have to be optional :-P

**Comment by fommil** [comment]
we have helm support for search now but leaving this open for `ido`.
