### ISSUE TITLE
(ensime-owning-connection-for-source-file) doesn't work well for out-of-buffer

### ISSUE THREAD

**Issue by reactormonk** [ensime/ensime-emacs#191]
The optimization with `ensime--buffer-unrelated-connections` doesn't work well when calling `(ensime-owning-connection-for-source-file)`.

a) remove the optimization
b) add another function that doesn't optimize

**Comment by aemoncannon** [comment]
Could you elaborate on 'doesn't work well' ?

**Comment by reactormonk** [comment]
It works for only the first call.

**Comment by reactormonk** [comment]
Apparently the caching via `ensime--buffer-unrelated-connections`
interferes here.

a) delete the caching
b) make a separate function that doesn't cache

**Comment by aemoncannon** [comment]
Could you explain how to reproduce this bug and perhaps paste a stacktrace?

**Comment by reactormonk** [comment]
No stacktrace. The problem is pretty simple: The caching logic assumes that you're only ever asking for the connection for the current buffer, which I am not. So it rules out anything that didn't match in the first try, which means it can only ever match the connection requested in the first call in subsequent calls.

**Comment by fommil** [comment]
@reactormonk ok, I (sort of) see. Can you think of a better way to do it? We'd definitely accept a PR in that area.

**Comment by reactormonk** [comment]
The correct way to get this information is via `(ensime-connections-for-source-file)`.
