### ISSUE TITLE
File mode specification error: (void-function ensime-scala-mode-hook)

### ISSUE THREAD

**Issue by zwb-ict** [ensime/ensime-emacs#196]
OS: Mac OSX 10.10
Emacs: 24.5

I use scala-mode2

(add-hook 'scala-mode-hook 'ensime-scala-mode-hook)

when I open a *.scala, It says:  File mode specification error: (void-function ensime-scala-mode-hook)

**Comment by fommil** [comment]
that looks like you've not loaded the ensime plugin. e.g. `(require 'ensime)`

**Comment by zwb-ict** [comment]
@fommil  Thank you for your help, I'm sorry, I forget to load ensime.
