### ISSUE TITLE
Should ensime mode list both company and auto-complete as dependencies?

### ISSUE THREAD

**Issue by IvanMalison** [ensime/ensime-emacs#212]
It seems weird that ensime requires the installation of both of these packages as dependencies. Having both company and auto-complete installed can cause annoying conflicts in certain modes unless they are configured perfectly.

**Comment by fommil** [comment]
yes, it's a user option. I only use company mode.

**Comment by fommil** [comment]
(auto complete users complain if we dont support, but maybe we should just declare company mode the winner and be done with it :-P)
