### ISSUE TITLE
utf-8 characters not being sent properly over the wire

### ISSUE THREAD

**Issue by channingwalton** [ensime/ensime-emacs#216]
OSX Yosmite
GNU Emacs 24.5.1 (x86_64-apple-darwin14.4.0, Carbon Version 157 AppKit 1348.17) (Emacs Mac Port)
Clean install of spacemacs
sbt plugin versino 0.1.7-SNAPSHOT for generating the ensile config

What I see on loading the attached file is the server buffer full of NumberFormatExceptions when I edit the file - it looks like ensime is trying to parse chunks of the code.

**Comment by fommil** [comment]
I think we'd really need to see an example project to be able to help you. even a simple hello world, are you using a weird character encoding?

Each blob of the SWANK protocol is a number and the server is receiving message parts.

Always prefer our recommendations over spacemacs... they are just packaging up ENSIME and their docs are out of date https://github.com/ensime/ensime-emacs/wiki/Quick-Start-Guide#installing-the-ensime-sbt-plugin

**Comment by channingwalton** [comment]
sorry I screwed up the initial report - thought I could attach some code. The file I loaded is https://github.com/channingwalton/playground/blob/master/src/main/scala/database/ReaderWriterDatabase.scala from a https://github.com/channingwalton/playground

I am UTF-8 but I'll double-check

**Comment by fommil** [comment]
hmm, works for me. Are you sure you're using the latest ensime client from MELPA and either downloaded or built the latest server?

**Comment by fommil** [comment]
btw, @channingwalton to get rid of those sbt warnings about conflicting versions, add this to your `build.sbt`

```scala
dependencyOverrides ++= Set(
  "org.scala-lang" % "scala-compiler" % "2.11.7",
  "org.scala-lang" %% "scala-reflect" % "2.11.7",
  "org.scalaz" %% "scalaz-concurrent" % "7.1.2"
)
```

(little known feature of sbt to force consistent versions without having to go and add explicit versions to each module)

**Comment by channingwalton** [comment]
I managed to get it working! But after a while it hung again. I'll try to get some debugging.
Thanks for the tip about libs :)

**Comment by fommil** [comment]
Make sure to update again to the latest server upgrade. Rory rewrote the SWANK handler and it was merged today.

**Comment by fommil** [comment]
actually we think your bug is an encoding issue, can you check what encoding Emacs is using (and even what line termination characters you are using).

**Comment by channingwalton** [comment]
Right, day job out of the way. I'll start experimenting with encoding and update the server.

**Comment by fommil** [comment]
just so you know what is probably happening: the SWANK protocol is framed like this:

* https://github.com/ensime/ensime-server/blob/master/server/src/main/scala/org/ensime/server/FramedStringProtocol.scala
* https://github.com/ensime/ensime-server/blob/master/server/src/test/scala/org/ensime/server/FramedStringProtocolSpec.scala

and we suspect you're using an encoding that emacs is unable to count the bytes of properly.

If that's happening, some messages will consume parts of the next one and then the number exception will happen. Your files will also exhibit point offsets when they are working, so you'll typically get the wrong type for where you're asking.

If you can force everything to use UTF-8 then all will probably be good with the world.

**Comment by channingwalton** [comment]
The files I am using appear to be UTF-8 but some contain unicode characters for ← and ⇒.

I took a file with none of those characters and pasted a ←, which instantly caused NPEs in the server buffer, shortly followed by ensile hanging.

Serves me right for using flashy characters.

**Comment by fommil** [comment]
hmm, that's interesting. I'll have a try with your playground tomorrow. It's possible that Mac Emacs is using non-UTF-8 for the buffer and then counting the bytes wrong. In any case, this is sounding increasingly like an emacs client bug. It would be good to add a UTF-8 test example to the emacs tests to cover us for this, although we only run those tests on linux.

**Comment by fommil** [comment]
well, pasting in that left arrow gives me

```
21:27:51.896 ERROR akka://ENSIME/user/ensime-main/tcp-server/con1 o.e.s.t.TCPConnectionActor - Error seen during message processing, closing client connection
org.parboiled.errors.ParsingException: Invalid :
Unexpected end of input, expected Digits, Frac, Exp, Whitespace, Sexp or ) (line 360, pos 6):
")) 8
     ^

	at org.ensime.sexp.util.ParboiledParser$$anonfun$parse$1.apply(ParboiledParser.scala:23) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.sexp.util.ParboiledParser$$anonfun$parse$1.apply(ParboiledParser.scala:23) ~[sexpress_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
```

is that the same exception as you?

@rorygraves when this happens, the connection dies but the server process is still running... that's really confusing, can we have the server process die?

**Comment by fommil** [comment]
we have a way of capturing the string message as it is sent on the wire. I'll try to turn it into a unit test, but it seems that fancy UTF-8 characters are causing problems right now. We found an inconsistency in the protocol recently, and fixed it, so perhaps the client side was at least partially compensating. We should just fix it properly on client and server, even if it means a bit of pain for a few days.

**Comment by fommil** [comment]
@aemoncannon do you know off the top of your head which part of the emacs code is counting the bytes of the outbound message?

I'll create a SWANK unit test to confirm that this isn't a server bug, and then write a client side failing test, hopefully with a fix. I'm starting to feel pretty confident about elisp :smile:

**Comment by channingwalton** [comment]
The error I see in the inferior-ensime-server buffer is the NumberFormatException one

java.lang.NumberFormatException: For input string: "ated))"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_31]
	at java.lang.Integer.parseInt(Integer.java:580) ~[na:1.8.0_31]
	at java.lang.Integer.valueOf(Integer.java:740) ~[na:1.8.0_31]
	at org.ensime.server.FramedStringProtocol$class.readString(FramedStringProtocol.scala:39) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.SwankProtocol.readString(SwankProtocol.scala:10) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.SwankProtocol.read(SwankProtocol.scala:15) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]
	at org.ensime.server.SocketHandler$$anon$1.run(SocketHandler.scala:43) ~[server_2.11-0.9.10-SNAPSHOT.jar:0.9.10-SNAPSHOT]

**Comment by channingwalton** [comment]
The character can appear anywhere it seems:  println("←") is enough to cause the NPE

**Comment by rorygraves** [comment]
@fommil "when this happens, the connection dies but the server process is still running... that's really confusing, can we have the server process die?"  
You explicitly told me to stop doing this and that 'emacs takes care of the buffer'.  However saying that I have added the ```-Densime.explode.on.disconnect``` flag back in.

**Comment by rorygraves** [comment]
@channingwalton Yep - this is a symtom of the framing failing.  Each message contains 6 bytes containing the length (hex number) followed by the bytes.  It has not read enough, so when it tries to read the next message it sees the random leftover from the previous message - giving the error.

**Comment by rorygraves** [comment]
@fommil  This mean our assumption that the lisp side was encoding byte length rather than utf8 length was incorrect.

**Comment by fommil** [comment]
@rorygraves yeah but that was for things like analyser failures. When the connection itself dies, things get a bit funky. Actually, if the connection didn't die, and instead just slurped all input, to get itself back into a recoverable state, that would be much better.

**Comment by fommil** [comment]
Hmm, I take that back. Slurping behaviour is complex. The current error behaviour is probably correct and we should just change the client to either attempt reconnection or flag the server to bail as you suggest.

**Comment by fommil** [comment]
ok, hotfix time :smile: delete all the `.elc` files (they take priority over the sources) and apply this

```diff
diff --git a/ensime-client.el b/ensime-client.el
index e0cb58b..d9b44c8 100644
--- a/ensime-client.el
+++ b/ensime-client.el
@@ -509,7 +509,7 @@ This doesn't mean it will connect right after Ensime is loaded."
  level of communication. The sexp will be read and interpreted
  by the Ensime Server."
   (let* ((msg (concat (ensime-prin1-to-string sexp) "\n"))
-        (string (concat (ensime-net-encode-length (length msg)) msg))
+        (string (concat (ensime-net-encode-length msg) msg))
         (coding-system (cdr (process-coding-system proc))))
     (when ensime--debug-messages (message "--> %s" sexp))
     (ensime-log-event sexp)
@@ -599,9 +599,9 @@ This doesn't mean it will connect right after Ensime is loaded."
   "Read a 24-bit hex-encoded integer from buffer."
   (string-to-number (buffer-substring-no-properties (point) (+ (point) 6)) 16))
 
-(defun ensime-net-encode-length (n)
-  "Encode an integer into a 24-bit hex string."
-  (format "%06x" n))
+(defun ensime-net-encode-length (msg)
+  "Encode the length of MSG into a 24-bit hex string."
+  (format "%06x" (length (encode-coding-string msg 'raw-text))))
 
 (defun ensime-prin1-to-string (sexp)
   "Like `prin1-to-string' but don't octal-escape non-ascii characters.
```

**Comment by rorygraves** [comment]
So fundamentally emacs did not send the number of bytes, but the number of characters originally?

**Comment by fommil** [comment]
Multibyte chars when sending to the server, bytes when receiving.

I tried adding this to your 

```scala
  class 裃()

  case class Abcαβγ()

  val αβγ = Abcαβγ()
```

and did a few "type at point" queries, it's looking good. I'll add a unit test around the input/output expectations and then raise a priority PR.

I also need to handle scala-2.10 (older protocols) differently, because it's using the old scheme.

**Comment by fommil** [comment]
ok, I created a fix for this (at the beginning of my lunch break, it only needed a small change).

**Comment by channingwalton** [comment]
awesome thanks. I'll try it out
