### ISSUE TITLE
Adding a dependency is not picked up on ensime restart

### ISSUE THREAD

**Issue by Profpatsch** [ensime/ensime-emacs#224]
When I add a dependency to `build.sbt` and run `ensime-gen-and-restart`, they are still marked in red. I have to restart Emacs for it to work.

**Comment by fommil** [comment]
Have you confirmed that the dot ENSIME is updated? Have you confirmed that ENSIME restarts?

**Comment by Profpatsch** [comment]
`ensime-gen-and-restart` does not update `.ensime`. Neither does `ensime-reload`.

**Comment by fommil** [comment]
It's ensime-gen-and-restart in ENSIME? I can't find it.

As a workaround, run `sbt-command reload`, `sbt-command gen-ensime` and then restart the ensime server.

**Comment by Profpatsch** [comment]
I actually deleted my `~/.sbt` previously because stuff didn’t work and deleted the `ensime-sbt` plugin with that.

And I found out that `ensime-gen-and-restart` is a spacemacs function (https://github.com/syl20bnr/spacemacs/blob/master/contrib/!lang/scala/packages.el#L68).

**Comment by fommil** [comment]
Yeah, I'm pretty sure we have a different way of doing this, we have a PR to auto watch the project defn and resort. Their bug in that they don't reload.

**Comment by Profpatsch** [comment]
@fommil Do you have a link to the code that does this for you?

**Comment by fommil** [comment]
Check the outstanding PR list
