### ISSUE TITLE
test/depend on MELPA stable not unstable

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#226]
_From @jmglov on August 26, 2015 8:46_

When I run `ensime` in a Scala file to start the server, I get the following error message in my minibuffer:

```
Error running timer `ensime-idle-typecheck-function': (void function -fine)
```

Here's my package info:

```
ensime is an installed package.

     Status: Installed in `~/.emacs.d/elpa/ensime-20150819.1214/' (unsigned).
    Archive: n/a
    Version: 20150819.1214
   Requires: scala-mode2-0.21, sbt-mode-0.3, popup-0.5.0, yasnippet-0.8.0, company-0.8.7, auto-complete-1.5.0,
               dash-2.10.0, s-1.3.0
    Summary: ENhanced Scala Interaction Mode for Emacs
   Homepage: https://github.com/ensime/ensime-emacs
   Keywords: languages 
    Other versions: 20150819.1214 (melpa.org).
```

And here's my `.ensime` from my project directory:

```
(
 :root-dir "/home/jmglov/Documents/code/functional-programming-in-scala"
 :cache-dir "/home/jmglov/Documents/code/functional-programming-in-scala/.ensime_cache"
 :name "functional-programming-in-scala"
 :java-home "/home/jmglov/.gentoo/java-config-2/current-user-vm"
 :java-flags ("-Xms512M" "-Xmx512M" "-Xss1M" "-XX:+CMSClassUnloadingEnabled" "-XX:MaxPermSize=384M")
 :reference-source-roots ("/home/jmglov/.gentoo/java-config-2/current-user-vm/src.zip")
 :scala-version "2.10.5"
 :compiler-args nil
 
 :subprojects ((
   :name "functional-programming-in-scala"
   :module-name "functional-programming-in-scala"
   :source-roots nil
   :target "/home/jmglov/Documents/code/functional-programming-in-scala/target/scala-2.10/classes"
   :test-targets ("/home/jmglov/Documents/code/functional-programming-in-scala/target/scala-2.10/test-classes")
   :depends-on-modules nil
   :compile-deps ("/home/jmglov/.sbt/boot/scala-2.10.5/lib/scala-library.jar")
   :runtime-deps nil
   :test-deps nil
   :doc-jars ("/home/jmglov/.ivy2/cache/org.scala-lang/scala-library/docs/scala-library-2.10.5-javadoc.jar" "/home/jmglov/Documents/code/functional-programming-in-scala/target/scala-2.10/functional-programming-in-scala_2.10-0.1-SNAPSHOT-javadoc.jar")
   :reference-source-roots ("/home/jmglov/.ivy2/cache/org.scala-lang/scala-library/srcs/scala-library-2.10.5-sources.jar")))
 
)
```

**Comment by fommil** [comment]
`-fine` is a dash function, how did you install ensime? It should be installed automatically.

**Comment by jmglov** [comment]
I just did M-x ensime from a Scala buffer.

**Comment by fommil** [comment]
@jmglov but how did you **install** ensime? Did you use MELPA, or did you just copy the git repo?

**Comment by jmglov** [comment]
MELPA.

**Comment by fommil** [comment]
@jmglov could be that your version of `dash` is too old. Can you upgrade it?

**Comment by jmglov** [comment]
That did the trick!

But now I can't start SBT from my Scala buffer. When I hit **C-c C-b s**, I'm prompted to select a project, which defaults to `foo#1` (where `foo` is the directory in which my project resides). When I select the default, I get "Could not find project root, type `C-h f sbt:find-root` for help."

I've also tried chopping off the `#1`, but I get the same result.

I don't have a `build.sbt` file in my project root. Do I need one? I can run `sbt` from the command line and interact with the REPL normally, so I think my project is set up correctly.

**Comment by fommil** [comment]
Cool. But that new problem is with `sbt-mode` --- that's where `sbt:find-root` comes from. It should work with `project/Build.scala` style projects (see `ensime-server` for example).

In either case it sounds like we have an incompatibility with MELPA stable, I'd recommend updating all the ENSIME dependencies and we'll flag this as something we need to fix before we make a stable release.

**Comment by jmglov** [comment]
OK, I'll check out `ensime-server`.

I just updated all my packages as recommended in the ENSIME starter guide, so I should be set there.

Thanks for your help!

**Comment by fommil** [comment]
@jmglov you have the `stable.melpa.org` repo, I think the guide only recommends `melpa.org` so you may experience incompatibilities.

**Comment by jmglov** [comment]
Gotcha. Unfortunately, I need melpa-stable for `cider-mode`, so I'll have to live with it.

**Comment by jmglov** [comment]
Adding a `project/build.properties` made sbt work. :)

**Comment by fommil** [comment]
interesting. It's actually really good practice anyway, otherwise you get a random version of sbt.
