### ISSUE TITLE
debugging use hydra

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#228]
Imagine going into "debug mode" and then everything is a single key press (with a helpful reminder of what everything does)

https://github.com/abo-abo/hydra
##

**Comment by topisani** [comment]
is this still interesting? if so, i may take a look at it

**Comment by topisani** [comment]
right, so i am currently working on this. It will be fairly basic, a little table of what you can do in the minibuffer, and then some simple keys for all the actions. I also think I'm going to implement a help menu for the debugger (simply providing the description of the functions on a hydra-key basis.

Any specific key requests?

Im thinking this should probably be opened with something like `C-c C-d C-d` or maybe even just `C-c C-d`, but thats pretty much up to you

**Comment by fommil** [comment]
Awesome! If you like to do some more hydra-fication take a look at the sbt support to run tests, or the jump to test functionality.

**Comment by topisani** [comment]
a better interface for searching is also something i might look into, but one thing at a time

**Comment by VlachJosef** [comment]
@fommil @topisani I'm currently working on a complete overhaul of my workflow with sbt everything based on hydras. There is no ticket for it, but I hope to make a PR hopefully next week.

**Comment by topisani** [comment]
@VlachJosef i use gradle, so i am very happy not to touch sbt. Does your overhaul include debugging as well?

**Comment by VlachJosef** [comment]
@topisani no, I'm not touching debugging at all. It will be just hydra for controlling sbt.

**Comment by topisani** [comment]
Great! ill leave all that alone then.

**Comment by fommil** [comment]
@VlachJosef that'd be really cool! We should really move everything out into `ensime-sbt.el` and also there is #198 

I'd really like to change the `.ensime` format now that we're in 2.0... have separate configs (`main`, `test`, `it`, etc) each with their own list of dependencies and scala compiler options, it'll give us much better server support for contextual completions (and robustness against bad compiler instances).

**Comment by VlachJosef** [comment]
@fommil I didn't look into `ensime-sbt.el` up until now. What I'm doing right now is completely disconnected from `ensime-server` only dependency is `ensime-sbt` and `hydra`.

Later when I'm done I will look at how it can be integrated with `ensime-server`.

**Comment by fommil** [comment]
Not sure you need to do anything with the server, most things just need the .ensime file

**Comment by fommil** [comment]
e.g. to work out the current project name (and in future, with changes to the format) the configuration name.

**Comment by VlachJosef** [comment]
Yes, currently what I need is projects names, which I can get from `.ensime` but also information if project has main class for determining if `run` can be executed for that project. This information is missing in `.ensime` but it can be easily added If needed I guess. 

Anyway I'm using `show mainClass` command in sbt and parsing `*sbt*` buffer for getting this informations.

**Comment by fommil** [comment]
A function was added recently for compileOnly which looks up the module name.

**Comment by fommil** [comment]
Sounds like asking sbt for the main class is the best way to do that.
