### ISSUE TITLE
M-x ensime starts ensime server but does not connect the buffer to it

### ISSUE THREAD

**Issue by wonk1132** [ensime/ensime-emacs#229]
As title describes, I'm having trouble connecting my buffer to ensime using 'M-x ensime' using emacs 24.3.1 on os x. when I type this command, I can see \*inferior-ensime-server-root\* tracking the process of the ensime server spinning up, resulting with a success message ('Ensime Ready...'), however, the status bar for the buffer shows (Scala [ENSIME: (Disconnected)] 

here is the trace from the \*inferior-ensime-server-root\* buffer 

18:31:12.968 INFO  None a.e.s.Slf4jLogger - Slf4jLogger started
18:31:12.984 DEBUG EventStream(akka://ENSIME) a.e.EventStream - logger log1-Slf4jLogger started
18:31:12.988 DEBUG EventStream(akka://ENSIME) a.e.EventStream - Default Loggers started
18:31:13.072 INFO  None o.a.c.v.i.StandardFileSystemManager - Using "/var/folders/lt/7gnn5z5j42qf0qg288rbpkx40000gn/T/vfs_cache" as temporary files store.
18:31:13.150 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/0 a.i.TcpListener - Successfully bound to /127.0.0.1:52831
18:31:13.154 INFO  None o.e.s.PortUtil$ - creating portfile /Users/wonk/Code/scala/hello/.ensime_cache/port
18:31:13.156 INFO  akka://ENSIME/user/ensime-main/tcp-server o.e.s.t.TCPServer - Bound server on port 52831
18:31:14.929 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/1 a.i.TcpListener - Successfully bound to /127.0.0.1:52832
18:31:14.968 INFO  None o.e.s.PortUtil$ - creating portfile /Users/wonk/Code/scala/hello/.ensime_cache/http
18:31:14.969 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor - ENSIME HTTP on /127.0.0.1
18:31:14.972 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor - Environment:
  OS : Mac OS X
  Java : Java HotSpot(TM) 64-Bit Server VM 25.60-b23, Java(TM) SE Runtime Environment 1.8.0_60-b27
  Scala : version 2.11.7
  Ensime : 0.9.10-SNAPSHOT
18:31:15.408 WARN  None c.j.b.BoneCPConfig - JDBC username was not set in config!
18:31:15.408 WARN  None c.j.b.BoneCPConfig - JDBC password was not set in config!
18:31:16.068 INFO  None o.e.i.SearchService - removing 0 stale files from the index
18:31:16.100 INFO  None o.e.i.ClassfileWatcher - Setting up new file watchers
18:31:16.181 DEBUG None o.e.i.SearchService - committing index to disk...
18:31:16.182 DEBUG None o.e.i.SearchService - ...done committing index
18:31:16.197 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - indexed 0 and removed 0
18:31:16.885 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/0 a.i.TcpListener - New connection accepted
18:31:16.919 INFO  akka://ENSIME/user/ensime-main/tcp-server o.e.s.t.TCPServer - Connection from localhost
18:31:16.924 INFO  akka://ENSIME/user/ensime-main/tcp-server o.e.s.t.TCPServer - Client connected - active clients now: 1
18:31:17.063 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/1 o.e.s.RequestHandler - ConnectionInfoReq
18:31:17.067 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message ConnectionInfoReq
18:31:17.071 DEBUG akka://ENSIME/user/ensime-main/tcp-server/con1/1 o.e.s.RequestHandler - received handled message ConnectionInfo(None,EnsimeImplementation(ENSIME),0.8.17) in state receive
18:31:18.816 DEBUG akka://ENSIME/user/ensime-main/project/analyzer o.e.c.Analyzer - received handled message FullTypeCheckCompleteEvent in state startup

if I do a 'M-x ensime-connect' at this point I get a message in the mini-buffer that reads 'error in process filter: Cache dir in ensime configuration file appears to be unset'. I get this same msgs attempting any ensime commands such as C-c C-c a

here is my .ensime file (created by  `sbt gen-ensime` and not touched by me)

(
 :root-dir "/Users/wonk/Code/scala/hello"
 :cache-dir "/Users/wonk/Code/scala/hello/.ensime_cache"
 :name "root"
 :java-home "/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home"
 :java-flags ("-Xms1024m" "-Xmx1024m" "-XX:ReservedCodeCacheSize=128m" "-XX:MaxMetaspaceSize=256m")
 :reference-source-roots ("/Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/src.zip")
 :scala-version "2.11.7"
 :compiler-args nil
 
 :subprojects ((
   :name "root"
   :module-name "root"
   :source-roots nil
   :target "/Users/wonk/Code/scala/hello/target/scala-2.11/classes"
   :test-targets ("/Users/wonk/Code/scala/hello/target/scala-2.11/test-classes")
   :depends-on-modules nil
   :compile-deps ("/Users/wonk/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.7.jar")
   :runtime-deps nil
   :test-deps nil
   :doc-jars ("/Users/wonk/.ivy2/cache/org.scala-lang/scala-library/docs/scala-library-2.11.7-javadoc.jar" "/Users/wonk/Code/scala/hello/target/scala-2.11/hello_2.11-1.0-javadoc.jar")
   :reference-source-roots ("/Users/wonk/.ivy2/cache/org.scala-lang/scala-library/srcs/scala-library-2.11.7-sources.jar")))
 
)

the dir /Users/wonk/Code/scala/hello/.ensime_cache is  a valid directory (that has contents).

[I found a promising bug report from the ensime server project here](https://github.com/ensime/ensime-server/issues/714)

this suggests symlink issues. I checked --no symlinks in my case.

**Comment by fommil** [comment]
Your source roots are nil. I suspect you have a script style project, there is an FAQ about this.

**Comment by Hodapp87** [comment]
Where is a FAQ about this? [Troubleshooting](https://ensime.github.io/editors/emacs/troubleshooting/) links to https://github.com/ensime/ensime-emacs/issues?q=label%3AFAQ or https://github.com/ensime/ensime-server/issues?q=label%3AFAQ, but I don't see anything relevant in either.

Are you talking about [issue #714](https://webcache.googleusercontent.com/search?q=cache:N_QiZPkD2PMJ:https://github.com/ensime/ensime-server/issues/714+&cd=1&hl=en&ct=clnk&gl=us) which was marked FAQ but deleted for some unknown reason?

**Comment by dickmao** [comment]
See https://github.com/ensime/ensime-server/issues/1432

In my case, using play framework WITH submodules, I had to:
```
ln -s ~/MyPlayApp/app ~/MyPlayApp/src/main/scala
sbt ensimeConfig
```
(ensime seems to work out-of-the-box on Play "script-style" layouts WITHOUT submodules, however).
