### ISSUE TITLE
make ensime-db-attach more central to the DB process

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#232]
ok, this is embarrassing. After using ENSIME for nearly 18 months I just started up the debugger for the first time :blush:

with the new `ensime-sbt` support (which I assume is probably easier to implement in other build tools) this was super easy, but I needed to use `M-x` commands.

create a key, update the docs, sensible defaults for the host and port to match the `ensime-sbt` stuff, plus maybe an extra command for remote debugging (which always asks for these things).

**Comment by fommil** [comment]
@aemoncannon @edani what do you say to deprecating the `ensime-db-start` function in preference of the build tool doing the launching? `sbt` is working fine now for this and I'll probably get `gradle` doing this when I'm using it in anger. Our launcher is very limited: doesn't use properties or pass args, and most importantly doesn't work for the tests.

**Comment by edani** [comment]
Given that we're no longer using ensime to compile or run applications, it makes sense to not launch the debugger either. At some point I'd like ensime to regain control these things, e.g. through sbt-remote-control, but that's a larger project.

**Comment by aemoncannon** [comment]
+1
The workflow with sbt is super convenient.
