### ISSUE TITLE
object not member of package

### ISSUE THREAD

**Issue by arigoldx** [ensime/ensime-emacs#236]
I'm hesitant posting this 'cause I don't have much to say but:

I'm getting an `object not member of package` error in my imports. But only for one of many imports.

I've done a `sbt gen-ensime` which often helps but not this time. I've googled quite a bit so figured I'd ask.

Outside of ensime/emacs-ensime everything works A OK - that is, there's nothing wrong with the import when I compile.

Again, sorry for my barely-helpful message - I'm more than happy to dig deep to help figure things out if y'al give me some direction. Thanks!

**Comment by arigoldx** [comment]
Well I'll be. I ran the test in `sbt` (the problem was in a spec file) and poof, error vanished. Maybe it needed some artifacts? Hmm...

**Comment by edani** [comment]
I bet you were missing .class files in your project.  This gets me from time to time: I remember to do `sbt compile` before launching ensime, but I forget `sbt test:compile`

**Comment by arigoldx** [comment]
Thanks! I'll keep that in mind. TBH, I never do a `sbt compile` before launching ensime but sometimes thinks break so I do a `sbt gen-ensime` and that usually fixes everything.

Dunno if this should just be closed or if there's some other protocol so I'm gonna leave it open.

Thanks again!

**Comment by fommil** [comment]
Cool. Have a read of the wiki, especially the workflow section for some more ideas.

**Comment by xelibrion** [comment]
@fommil I have the same issue, although I made sure that `.class` files are generated before I launch ensime, I'm using ensime-gradle to generate config.
