### ISSUE TITLE
Ensime gives thousands of errors on a cats based project

### ISSUE THREAD

**Issue by svalaskevicius** [ensime/ensime-emacs#239]
it seems ensime is unable to find the implicits imported from the cats library and generates lots of errors.

as an example I've defined a free monad based using cats library, and flatMapping it gives >8k errors in ~15 lines of for comprehension.

currently the project I used to replicate this is not on github but if it helps to reproduce the error, I can publish it

**Comment by svalaskevicius** [comment]
btw, all (or almost all) of the errors are duplicates

**Comment by fommil** [comment]
Without seeing an example project, this is almost impossible for us to say anything. That said, I'm almost certain that this is covered by the FAQ about red lines, and also user the workflow wiki page.

**Comment by fommil** [comment]
Yup, was a grumpy Monday morning. Told you! :-) send in the project when its ready and we'll have a look.

**Comment by svalaskevicius** [comment]
Cheers!

**Comment by svalaskevicius** [comment]
Project on github (with the current commit when the failures are found): https://github.com/svalaskevicius/eventflow/tree/48ef1d9a3c6358d08673fa38167be3e4f11c0342/


`ensime-show-all-errors-and-warnings` result:

```
Latest Compilation Results (q to quit, g to refresh, TAB to jump to next error)
/Users/svalaskevicius/priv/dev/eventflow/src/main/scala/Cqrs/InMemoryDb.scala
WARNING: Unused import : line 11
ERROR: Cqrs.InMemoryDb.Db[E,<error>] takes no type parameters, expected: one : line 51
ERROR: Cqrs.InMemoryDb.Db[E,<error>] takes no type parameters, expected: one : line 51
ERROR: not found: type ? : line 51
ERROR: Cqrs.InMemoryDb.Db[E,<error>] takes no type parameters, expected: one : line 51
ERROR: Cqrs.InMemoryDb.Db[E,<error>] takes no type parameters, expected: one : line 51
ERROR: not found: type ? : line 51
ERROR: Cqrs.InMemoryDb.Db[E,<error>] takes no type parameters, expected: one : line 80
ERROR: not found: type ? : line 80

/Users/svalaskevicius/priv/dev/eventflow/src/main/scala/Domain/Counter/package.scala
ERROR: value >> is not a member of c.AD[Unit] : line 42

/Users/svalaskevicius/priv/dev/eventflow/src/main/scala/Cqrs/Aggregate.scala
ERROR: value >>= is not a member of Aggregate.this.AD[Boolean] : line 76
ERROR: value >>= is not a member of cats.state.StateT[Cqrs.Aggregate.EventDatabaseWithFailure,Cqrs.Aggregate.AggregateState[D],List[Cqrs.Aggregate.VersionedEvents[E]]] possible cause: maybe a semicolon is missing before `value >>='? : line 103

/Users/svalaskevicius/priv/dev/eventflow/.ensime_cache/dep-src/source-jars/cats/package.scala
WARNING: higher-kinded type should be enabled by making the implicit value scala.language.higherKinds visible. This can be achieved by adding the import clause 'import scala.language.higherKinds' or by setting the compiler option -language:higherKinds. See the Scala docs for value scala.language.higherKinds for a discussion why the feature should be explicitly enabled. : line 6
WARNING: higher-kinded type should be enabled by making the implicit value scala.language.higherKinds visible. : line 6
WARNING: higher-kinded type should be enabled by making the implicit value scala.language.higherKinds visible. : line 7
WARNING: higher-kinded type should be enabled by making the implicit value scala.language.higherKinds visible. : line 7
```

Thanks!

**Comment by fommil** [comment]
I can confirm this, but its not very drastic because everything else pretty much works (e.g. do a type at point on symbols nearby). I'm pretty sure this is just a dupe of https://github.com/ensime/ensime-server/issues/673

In this case it is failing for code that looks like this:

```scala
  def runInMemoryDb_[E]: EventDatabaseOp ~> Db[E, ?] = new (EventDatabaseOp ~> Db[E, ?]) {
```

(on the `?`s)

I recommend creating an absolutely minimal file that exhibits the same problem, using only the standard library, and report upstream (i.e. the scala language issue tracker).

@non is there anything in cats that you can think of which might be making life difficult for the presentation compiler, or any workarounds for this in terms of an alternative coding style?

BTW, I can confirm that this happens with or without all the scala compiler flags that you're using (wartremover, etc).

**Comment by fommil** [comment]
similar for the errors around ` >>=` and `>>`
