### ISSUE TITLE
Enter should also close object tree while debugging.

### ISSUE THREAD

**Issue by reactormonk** [ensime/ensime-emacs#242]
Given the following object:

    channel: Session$Command = Instance of SessionChannel
     Instance of net.schmizz.sshj.connection.channel.direct.SessionChannel
     exitStatus: Integer = Instance of Integer
      Instance of java.lang.Integer
      serialVersionUID: long = -8742448824652078965
     exitSignal: Signal = NA
      null: Null
     wasCoreDumped: Boolean = NA
     exitErrMsg: String = NA
      null: Null
     canDoFlowControl: Boolean = NA
     usedUp: boolean = true
    stdErrBytes: byte[] = NA
     null: Null
    stdOutBytes: byte[] = NA
     null: Null
    exitSignal: Option = NA
     null: Null
    exitCode: Option = NA
     null: Null
    exitErrorMessage: Option = NA
     null: Null
    bitmap$0: byte = 0
     0: byte

On the cursor on `channel`, it should close the object tree again.

**Comment by fommil** [comment]
Thank you for using ENSIME!

We are getting a lot of bug reports recently that are missing key information, so we're using https://github.com/Astrac/github-autoresponder to ask that everything is captured in the ticket.

Before somebody responds to this ticket, can you please confirm that you have checked the following:

* are you are using the latest release of ensime-emacs? Make sure to use MELPA to update your packages regularly.
* try nuking your ivy cache (specifically `~/.ivy2/cache/org.ensime`), then type `ensime-update` before trying again (upstream bug in `sbt`).
* check the [tickets flagged as FAQ on the server](https://github.com/ensime/ensime-server/issues?labels=FAQ) and [tickets flagged as FAQ for Emacs](https://github.com/ensime/ensime-emacs/issues?labels=FAQ).
* check the [most recently updated tickets](http://github.com/ensime/ensime-emacs/issues?direction=desc&sort=updated).
* do a few keyword searches using the github search (top of the page) to see if anybody has reported this already.
* if its about a non-scala specific question, check that the thing you're experiencing isn't from another Emacs mode.

If that solved your problem, great! Please close the ticket. If not, please read on...

There is very little we can do unless you provide us with a **minimal reproduction of the problem**. Creating a standalone project on github is a great way to do this. Please also provide step by step instructions about how you triggered the bug (videos can be useful too). Commit your `.ensime` and the output from the server buffer in the repository. You can also enable `(setq debug-on-error t)` to get a stacktrace in Emacs if an error occurred, which is useful to include.

The next step is for us to help you create a unit test that fails. Once we have an automated failing test, then finding the solution is typically a lot easier.

We'll give as much help as we can, our goal is to grow this community. Honestly, if you're already using Emacs to write Scala code, you have all the skills you'll need to make ENSIME even better.
