### ISSUE TITLE
debugging-off doesn't disable debugging

### ISSUE THREAD

**Issue by reactormonk** [ensime/ensime-emacs#244]
[project] $ debugging-off
    [info] Set current project to project
    [project] $ spark-client/testQuick
    [info] Compiling 1 Scala source to project
    Listening for transport dt_socket at address: 5005

**Comment by fommil** [comment]
You'll need to give me an example project and session for this.

**Comment by reactormonk** [comment]
Cannot reproduce.

**Comment by fommil** [comment]
Guess: you enabled debugging twice and didn't disable twice. There is probably a minor but in there. Have a quick look at the source of the plugin and see if you spot anything suspect.
