### ISSUE TITLE
Do we really need a gutter icon *and* an underline for implicits?

### ISSUE THREAD

**Issue by aemoncannon** [ensime/ensime-emacs#247]
Seems like too much noise to me. Also, can't see breakpoints when gutter is in use.

**Comment by fommil** [comment]
Somebody requested this currently and I recommended that they set the overlay to nil. But in general I wonder if there is a prettier way of doing it. Maybe gutter for implicit params and something else for multiline implicits

**Comment by metatron-the-chronicler** [comment]
Maybe something like Eldoc might work for this.  There could be a setting that says that whenever Eldoc gets activated it should display the implicits in the signature.  It might be preferable to just have the gutter icon for everything in the editor window and a command that shows all of the implicits in that are in the file.

**Comment by fommil** [comment]
This is now fixed actually, but requires a setting.
