### ISSUE TITLE
Should give some ui message when stepped debug source is not found.

### ISSUE THREAD

**Issue by aemoncannon** [ensime/ensime-emacs#248]
From the server log:
19:38:40.143 DEBUG akka://ENSIME/user/ensime-main/project/debugging o.e.c.DebugManager - received handled message StepEvent@org.openide.util.lookup.InheritanceTree:288 in thread pool-1-thread-1-ScalaTest-running-JavaCompilerSpec
19:38:40.143 WARN  akka://ENSIME/user/ensime-main/project/debugging o.e.c.DebugManager - Step position not found: InheritanceTree.java : 288

**Comment by fommil** [comment]
#249 is the solution
