### ISSUE TITLE
Support debug stepping through bytecode when source is not available.

### ISSUE THREAD

**Issue by aemoncannon** [ensime/ensime-emacs#249]
This is actually not so hard. We already have source (somewhere) for pretty printing bytecode..
##

**Comment by fommil** [comment]
Yeah, I broke this. There was some reason why it got in the way during a refactor, and then I just forgot all about it.

**Comment by fommil** [comment]
better yet, why not use a decompiler?

**Comment by aemoncannon** [comment]
I think both would be neat. Some folks like to look at byte code.
