### ISSUE TITLE
Ensime tries to start in wrong project if user switches to different buffer in meantime

### ISSUE THREAD

**Issue by greenrd** [ensime/ensime-emacs#259]
This bug would be rendered irrelevant if https://github.com/ensime/ensime-emacs/pull/138 had been accepted in the first place.

**Comment by fommil** [comment]
We're waiting for you to rebase/update that PR

**Comment by greenrd** [comment]
Yes, but when I get around to changing it to be the way you wanted it, this bug will still be an issue. If it was done my way, it would not be an issue.

**Comment by fommil** [comment]
I'll have a closer look when I return from holiday. If you have a test case of it failing that would be useful. You mean you type M-x ensime and then change buffer before it asks?

**Comment by greenrd** [comment]
Yes, exactly.

**Comment by fommil** [comment]
Right OK, and I guess this only happens when it needs to update itself.

**Comment by greenrd** [comment]
Ah, that could also trigger this bug, I forgot about that. But no, I was thinking of the case where it is regenerating the .ensime file for me.

**Comment by fommil** [comment]
I've been thinking about a refactor to move all SBT related commands into one file, I'll have a look at all this regen stuff when I do that. Also, I know ensime-reload is basically broken so that probably don't help either.

**Comment by fommil** [comment]
is this still relevant?

**Comment by greenrd** [comment]
Yes - today I ran ensime in one project, switched to another project in another frame, and ensime started in the second project. (I tried again, it failed again, and then I just restarted emacs.)

**Comment by fommil** [comment]
We must be calculating the config file location late in the process instead of at the beginning. Although I'm surprised that this happens because I thought an interactive function stayed in the initiating buffer. It is probably related to the way we attach process monitors.
