### ISSUE TITLE
Unmatched parenthesis in Semantic Highlighting wiki

### ISSUE THREAD

**Issue by d1egoaz** [ensime/ensime-emacs#260]
There is an error in the example code of: Semantic Highlighting
There are a few unmatched parenthesis:
![image](https://cloud.githubusercontent.com/assets/950087/10437014/1f6a909a-70df-11e5-9541-d35d344b9acb.png)

I fixed this in the following commit, but as it's a wiki page I can't make a PR.
https://github.com/d1egoaz/ensime-emacs/commit/5c85c4ae1b0f0df44f7f37569e411cc567364592

**Comment by fommil** [comment]
I think you should just be able to edit the wiki directly, no? If not, reopen this ticket.

**Comment by d1egoaz** [comment]
ohh Cool! I didn't know I can do that (edit wiki privileges)
Fixed wiki!
