### ISSUE TITLE
Error: "subseq: Autoloading failed to define function edmacro-subseq" when executing ensime-inspect-type-at-point

### ISSUE THREAD

**Issue by czshigemura-michihito** [ensime/ensime-emacs#261]
## Environment

* OSX Yosemite
* Emacs 24.4.1 
* activator 1.3.8
* ensime 0.2.0

## Overview

When I execute ensime-inspect-type-at-point to know variable's type, I saw this error log.

```
subseq: Autoloading failed to define function edmacro-subseq
```

I think there's a problem in edmacro, but I have no idea further.

**Comment by fommil** [comment]
Without seeing your project source code, there isn't a lot we can do to help, sorry.

**Comment by czshigemura-michihito** [comment]
Sorry for bothering you. It's spray's sample code from https://github.com/x1-/spray-sandbox

Boot.scala
```
package com.inkenkun.x1

import akka.actor.{ActorSystem, Props}
import akka.io.IO
import spray.can.Http
import akka.pattern.ask
import akka.util.Timeout
import scala.concurrent.duration._

object Boot extends App {

  // we need an ActorSystem to host our application in
  implicit val system = ActorSystem( "on-spray-can" )

  // create and start our service actor
  val service = system.actorOf( Props[MyServiceActor], "demo-service" )

  implicit val timeout = Timeout( 5.seconds )
  // start a new HTTP server on port 8080 with our service actor as the handler
  IO( Http ) ? Http.Bind( service, interface = "localhost", port = 8080 )
}
```

I put cursorl on "system" in 13th line and executed "ensime-inspect-type-at-point", but I see this error.

**Comment by fommil** [comment]
Are you sure you don't have some funky macro or compiler plugin that you're using? Thanks for the test case.

**Comment by czshigemura-michihito** [comment]
Thank you for your answers :smile:

**Comment by czshigemura-michihito** [comment]
I changed my Emacs's version from 24.5 to 24.3, ensime-inspect-type-at-point works!

**Comment by fommil** [comment]
I think edmacro might be something in your config, not ENSIME.
