### ISSUE TITLE
Hangs Emacs on 'waiting for connection info...' on Ubuntu

### ISSUE THREAD

**Issue by jasonzoladz** [ensime/ensime-emacs#264]
On atom, ensime works fine. But it's broken for Emacs -- at least for simple projects.

Minimal reproduce (ubuntu: Emacs 24.4; mac: Emacs 24.5)

- create a new sbt project by hand with a bare-minimum build.sbt
- create one scala package with a single "hello world" object
- `sbt compile`
- `sbt gen-ensime`
- open the "hello world" file
- start ensime

Emacs is rendered unresponsive.  `xkill`

I've also posted this issue here:  ensime/ensime-server#1113  Obviously, one should be closed.

**Comment by aemoncannon** [comment]
Nasty. Use C-g to cancel whatever is running, and then paste the contents of *inferior-ensime-server* buffer?

**Comment by jasonzoladz** [comment]
I wish that I could.  When I say unresponsive, I mean that I must force-quit/xkill Emacs.  No commands will work.  Here's a screenshot:

<img width="833" alt="screen shot 2015-10-22 at 11 04 10 am" src="https://cloud.githubusercontent.com/assets/8467728/10669051/f95cfe58-78ac-11e5-8be9-757388f6574c.png">

**Comment by aemoncannon** [comment]
Did you have an existing .ensime_cache from Atom? maybe kill that and retry?

**Comment by aemoncannon** [comment]
Also, might try killing the jvm process -- that might unblock emacs and let you get the log info.

**Comment by jasonzoladz** [comment]
No, I only fired-up Atom editor  to see if it was an emacs-specific issue.  (Nonetheless, I deleted .ensime and .ensime_server and retried; no avail.)

Ugh.  Killing the jvm process doesn't unfreeze Emacs.

**Comment by aemoncannon** [comment]
Can you put a repro project up on github so we can clone? (I tried and could not repro just now)

**Comment by jasonzoladz** [comment]
Here it is:  https://github.com/jasonzoladz/hellobrokenensime

**Comment by fommil** [comment]
Did you try ESC ESC ESC? There is a short period of blocking during startup and this (typical) Emacs command is used to escape it.

**Comment by jasonzoladz** [comment]
Yep.  Completely unresponsive.

**Comment by hakuch** [comment]
I've experienced this too.

**Comment by fommil** [comment]
We have at open ticket for this on OS X, the interesting thing there is that you're experiencing it in Linux. If you're also seeing this, can you confirm it is with the above instructions? How long do you leave it before giving up? Which distro and which exact version of Emacs? We should be able to reproduce in docker.

**Comment by jasonzoladz** [comment]
- Ubuntu 15.04
- emacs 24.4.1
- I left it for 20 minutes; had to `xkill`

**Comment by fommil** [comment]
I mean the exact package version name (from aptitude or apt)

**Comment by jasonzoladz** [comment]
apt

**Comment by diego-alvarez-hs** [comment]
Trying using on osx  the emacs-mac-port app, I had some similar problems, after I move to  emacs-mac-port everything it's working great.
emacs-mac-port: https://github.com/syl20bnr/spacemacs#os-x

**Comment by jasonzoladz** [comment]
Tried that.  Doesn't work.

**Comment by fommil** [comment]
Let's keep this ticket about Ubuntu. There is already a OSX variant.

**Comment by fommil** [comment]
I was unable to reproduce (Debian Testing, Emacs 24.5)
