### ISSUE TITLE
Find abstract method definitions / implementations

### ISSUE THREAD

**Issue by aij** [ensime/ensime-emacs#273]
I'm trying to find the implementation of an abstract method. I'm using M-. (ensime-edit-definition) on a method call, but that only gets me the abstract declaration (with no implementation).

Is it possible to get ensime to show me the code that is actually being run? (Obviously, due to dynamic dispatch, there could be several implementations, so ensime-edit-definition is probably not what I want.)

Currently, my inefficient workaround is to build scaladoc, find docs for the abstract class/trait, then look through the known subclasses for ones that implement the method.

**Comment by fommil** [comment]
this is not implemented yet, raise as a feature request on ensime-server.
