### ISSUE TITLE
the tests are broken

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#280]
And I don't know when they broke because drone was lying to us for ages (I used `&&` in the scripts instead of `;`).

The problem seems to be that the `ensime-net-filter` is unable to obtain a connection and it looks like its a transient because a different test fails each time :cry:

**Comment by aemoncannon** [comment]
What's the status here? Anything I can do to help?

**Comment by fommil** [comment]
I basically have no idea what the cause is. If you could diagnose the cause that'd be awesome. We've had a few reports of Emacs freezing and I'm wondering if it's all related. I'm pretty sure it's Emacs side and related to no connection being available/found.

**Comment by aemoncannon** [comment]
:-(    Ok. Pointers on how to run the drone build locally?

**Comment by fommil** [comment]
It fails for me without drone actually, just running the test script should do it (but don't forget to set `JDK_HOME` to a JDK6 first, otherwise you might get some false positives in the search/debug queries where different javas return different results).

But I think drone should be able to run locally if you just clean the directory and type `drone exec`. installation instructions here http://readme.drone.io/cli/

**Comment by fommil** [comment]
if that sounds too easy it probably is... you need to have `docker` installed locally, of course. You also might want to download our build image ahead of time by typing `docker pull ensime/ensime:latest`. This gets updated every time a build completes successfully on master, but only the top few layers get updated so its a small delta.
