### ISSUE TITLE
Emacs Ensime stuck in (Analyzing) phase

### ISSUE THREAD

**Issue by tharpa** [ensime/ensime-emacs#287]
I've got a problem with the latest Ensime for Emacs (version  MELPA 20151109.739).  After `M-x ensime` the server starts correctly but the project is stuck in the 'analysing' phase and none of the Ensime functionality is working properly.  I've done the `M-x ensime-update` and restarted Emacs as well.  The `*inferior-ensime-server-project*` buffer lists new commands as they are issued in the Scala buffer.

**Comment by fommil** [comment]
There isn't anything we can do without at example project.

**Comment by tharpa** [comment]
-> Sam Halliday writes:

> There isn't anything we can do without at example project.

Do you have an account on bitbucket?  I don't have private repos on
GitHub.  Please provide me with an email address for your account on
Bitbucket.  Alternatively, I'll send you a zip file of the sceleton
project (just starting).

Thanks for your prompt response.

cheers
-- 
-rafał

**Comment by fommil** [comment]
Just create a minimal example that exhibits the problem. My bet is you'll end up finding a bug in some macro that you're using.

**Comment by tharpa** [comment]
I'm trying to understand while I'm having this problem even with the simplest Scala set project. It stays either in `disconnected` or `analyzing` state forever.  It worked fine just last week, damn it.

**Comment by fommil** [comment]
make sure you've updated ensime via MELPA.

**Comment by tharpa** [comment]
Hey, I've updated to the latest MELPA package (`  ensime             20151109.1242 installed             ENhanced Scala Interaction Mode for Emacs`) and prepared this simple HelloWorld sbt project:  https://github.com/tharpa/HelloWorld.  Please see the included screencast video for the behavior I'm experiencing. Is it Scala 2.11.7, Java 1.8.0_66 or some other lisp packages which cause the problem?  I'd be curious if you can reproduce it based on my settings in `.ensime`.  I'd like to have a strategy how to debug and fix the problem.

**Comment by fommil** [comment]
thanks! I'll try to have a look over the next few days. Ping me if I don't respond by Sunday.

**Comment by tharpa** [comment]
-> Sam Halliday writes:

> thanks! I'll try to have a look over the next few days. Ping me if I don't respond by Sunday.

Sure, I'll haunt you by Sunday then.  In the meantime, what would be the
first thing you would go after?  Maybe I can verify that on my own...

**Comment by fommil** [comment]
JDK version. Try on Java 6 or 7.

**Comment by tharpa** [comment]
I've tried all JVMs I have:
```
$ ls -l /Library/Java/JavaVirtualMachines/
total 0
drwxr-xr-x  3 root  wheel  102 Jul 14 23:52 1.6.0.jdk
drwxr-xr-x  3 root  wheel  102 Dec 17  2014 jdk1.8.0_25.jdk
drwxr-xr-x  3 root  wheel  102 Jun 10 16:23 jdk1.8.0_45.jdk
drwxr-xr-x  3 root  wheel  102 Nov  3 18:21 jdk1.8.0_66.jdk
```
changing the `.ensime` settings to use them accordingly.  No success. I suspect it is more on the Emacs side of the fence. I'll try starting with `emacs -Q` and load only the ensime and its dependencies and see what will happen.

**Comment by rorygraves** [comment]
From the screencast the Ensime server is starting successfully and the last thing shows it indexing.  Can you 
a) look for any error lines (ERR) in the inferior buffer.
b) Save a copy of the buffer into a text file and at it to the github project above?

Thanks

Rory

**Comment by tharpa** [comment]
-> Rory Graves (@a dev musing) writes:

> From the screencast the Ensime server is starting successfully and the last thing shows it indexing. Can you 
> a) look for any error lines (ERR) in the inferior buffer.
> b) Save a copy of the buffer into a text file and at it to the github project above?

Hi Rory,

There are no ERR lines in the inferior buffer, I'm afraid.  Please have
a look yourself:

https://github.com/tharpa/HelloWorld/blob/master/inferior-ensime-server-helloworld.txt

Thanks for jumping in!

> Thanks

> Rory

> —
> Reply to this email directly or view it on GitHub.

-- 
-rafał

**Comment by tharpa** [comment]
Sam, Rory,

I've tried to run the `Emacs -Q` with both my old `GNU Emacs 25.0.50.2 (x86_64-apple-darwin14.5.0, NS appkit-1348.17 Version 10.10.5 (Build 14F27)) of 2015-08-15 on obelix` and fresh of git repo `GNU Emacs 25.0.50.2 (x86_64-apple-darwin15.0.0, NS appkit-1404.13 Version 10.11.1 (Build 15B42)) of 2015-11-13` on the sample project.  I'm seeing the same exact problem again.

I'm curious if some of you guys can reproduce that. What else do you need to debug the issue?  Elisp package list, my `emacs.d`?  I really need this to start working again, please.

**Comment by fommil** [comment]
I actually can't see the problem. The server logs shows that the server has startup up ok, what exactly is not working as you expect?

Can you maybe post your full server log and maybe the `*Messages*` buffer?

**Comment by fommil** [comment]
there is also ` *ensime-events*`

**Comment by tharpa** [comment]
Well, the problem is that most of the Ensime functionality is not there like type checking commands, e.g. `C-c C-c c` or `C-c C-c a` or completion.

__Actually, there is no `*ensime-events*` buffer at all!__

Here is the `*Messages*` buffer from the `emacs -Q` session:

```
For information about GNU Emacs and the GNU system, type C-h C-a.
Saving file /Users/rk/Developer/Scala/HelloWorld/src/main/scala/HelloWorld.scala...
Wrote /Users/rk/Developer/Scala/HelloWorld/src/main/scala/HelloWorld.scala
Eager macro-expansion failure: (error "Not connected. M-x ensime to connect")
ENSIME server starting...
Connecting to Swank on port 61081..
ad-handle-definition: ‘ido-completing-read’ got redefined
Connected to ENSIME speaking protocol 0.8.9, please wait while the project is loaded.
Checking entire project...
Saving file /Users/rk/Developer/Scala/HelloWorld/src/main/scala/HelloWorld.scala...
Wrote /Users/rk/Developer/Scala/HelloWorld/src/main/scala/HelloWorld.scala
Checking entire project... [2 times]
Formatting...
```
I've added this [video] (https://github.com/tharpa/HelloWorld/blob/master/emacs-Q.mov) of the `Emacs -Q` session (no personal customizations, just `(package-initialize)`.

**Comment by fommil** [comment]
Are you using symbolic links by any chance?

**Comment by tharpa** [comment]
No symbolic links in the sbt project, though I have my `.emacs.d` on Dropbox and symlinked to my home.

**Comment by tharpa** [comment]
Good news.  I've solved my issue with the following steps:

```
  rm -rf .ivy2/
  rm -rf .m2
  sbt gen-ensime
  sbt update
```
and then with `M-x ensime-update` in Emacs.  I have no clue what the problem might have been; some stale packages in the ivy2 cache? Anyway, this was neither ensime-server no ensime-emacs fault. 

Thanks for support Sam & Rory.

**Comment by aemoncannon** [comment]
So many layers of caching fail :-\

**Comment by fommil** [comment]
@tharpa FWIW, this is probably the biggest problem we see. It's actually in the FAQ and CONTRIBUTING notes as the first thing to do. That said, this is a completely different manifestation of the problem so I wouldn't even have guessed to suggest it :-/
