### ISSUE TITLE
ensime keeps restarting (not due to file in current buffer not being found)

### ISSUE THREAD

**Issue by greenrd** [ensime/ensime-emacs#289]
Eventually it crashes and dies (GC exhaustion or something). This makes it hard to use ensime for real work when approaching a deadline.

**Comment by rorygraves** [comment]
Ouch, thats not fun - can you post a segment of the log with the restarts in?

**Comment by rorygraves** [comment]
If I had to guess we are probably leaking presentation compilers or something - they are nasty thready beasts.

**Comment by fommil** [comment]
ideally a failing project

**Comment by fommil** [comment]
#283
