### ISSUE TITLE
compiler is confused by file renames

### ISSUE THREAD

**Issue by akamaus** [ensime/ensime-emacs#290]
Say I open a file tst.scala and write where:
```
class Tst {
  val x = 1
  def receive() = {println("is good"); println(y)}
}
```
So far so good, Ensime correctly points on y being unknown.

But if now I rename tst.scala to tst2.scala (by using C-x-w and subsequent deleting original file) I get the following messages:
```
/home/dvyal/test/scala/src/main/scala/tst2.scala
ERROR: constructor Tst is defined twice   conflicting symbols both originated in file '/home/dvyal/coding/vk_gazer/scala/src/main/scala/tst.scala' : line 1
ERROR: x  is already defined as value x : line 2
ERROR: x is already defined as value x : line 2
ERROR: not found: value y : line 3
ERROR: self constructor arguments cannot reference unconstructed `this` : line 4

/home/dvyal/test/scala/src/main/scala/tst.scala
ERROR: not found: value y : line 3
ERROR: self constructor arguments cannot reference unconstructed `this` : line 4
```

Looks like the compiler hasn't notice first file was deleted.

**Comment by fommil** [comment]
Interesting. I thought we had a hook on deleted files. Maybe the new file is created before the old one is deleted.

If you could create a test for this in ensime-tests.el your probably find that the fix is trivial.

**Comment by akamaus** [comment]
of course it is. First I created a file, then I decided to save it under another name, and after that I fired Dired and deleted original. I'll look at ensime-tests.el as you suggested

**Comment by fommil** [comment]
ah, actually I'm not sure if we're ever going to be able to handle this situation, it's a genuine error. If you get the error with dired's `R` (rename/move) command, that's a different matter.

**Comment by fommil** [comment]
there was some work in this area recently, create a new ticket following https://github.com/ensime/ensime-emacs/wiki/issue if it still persists.
