### ISSUE TITLE
Strange completion behavior

### ISSUE THREAD

**Issue by oscar-broman** [ensime/ensime-emacs#291]
```scala
object Test {
  val fo = ""
  val foo = ""

  fo<press .>
}
```

When I do that, it will put `foo.` instead of `fo.`. To avoid this I'd need to type `fo<SPC>` then `.`.

I'm using Spacemacs; perhaps it has some configuration that messes up the intended behavior.

**Comment by fommil** [comment]
this is the behaviour of the autocompletion. I don't know what spacemacs does here but I don't believe it works this way in stock emacs.

**Comment by oscar-broman** [comment]
The problem lies in Spacemacs.

Issue on this: https://github.com/syl20bnr/spacemacs/issues/2702
