### ISSUE TITLE
Emacs is hanging, what do I do?

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#294]
If Emacs ever hangs, just use the universal quit command, bound to `ESC ESC ESC` or `C-g`.

**Comment by aij** [comment]
Is there a good way to see *why* it's hanging?

**Comment by aemoncannon** [comment]
If you can manage to run M-x profiler-start *before* it hangs, then you
might get some good info after you cancel out of the hang and do M-x
profiler-report.

**Comment by fommil** [comment]
`debug-on-quit`
