### ISSUE TITLE
Test Autoresponder

### ISSUE THREAD

**Issue by hrajanie** [ensime/ensime-emacs#304]

**Comment by fommil** [comment]
Thank you for using ENSIME!

Most tickets can be resolved easily by following a simple process.

Before one of the core devs can respond to this ticket, please confirm the following (tick each box as you complete the task):

[ ] you nuked ENSIME from your ivy cache (i.e. `rm -rf ~/.ivy2/cache/org.ensime`).
[ ] you are using the latest release of `ensime-emacs` (i.e. update `ensime` via MELPA).
[ ] you are using the latest release of `ensime-server` (i.e. type `M-x ensime-update`).
[ ] you checked the [tickets flagged as FAQ for Emacs](https://github.com/ensime/ensime-emacs/issues?labels=FAQ).
[ ] you checked the [tickets flagged as FAQ on the server](https://github.com/ensime/ensime-server/issues?labels=FAQ).
[ ] you checked the [most recently updated tickets](http://github.com/ensime/ensime-emacs/issues?direction=desc&sort=updated)
[ ] you checked `M-x customize-group ensime` (or viewed `ensime-vars.el`) to see if this is already handled.
[ ] (if you are using spacemacs) you asked on the spacemacs user list first.

If that solved your problem, great! Please close this ticket. If not, please read on...

There is very little we can do unless you provide us with a **minimal reproduction of the problem**. Please provide:

[ ] a standalone project on github (or use `ensime-server` itself, as we all have it checked out)
[ ] step by step instructions about how you triggered the bug (videos can be useful)
[ ] attach your `.ensime` to the repository (or in a gist)
[ ] also attach the output from the ENSIME server buffer
[ ] also attach an emacs stacktrace (if relevant), e.g. via `(setq debug-on-error t)`

**The next step is for us to help you create a unit test that fails.** We'll give as much help as we can, our goal is to grow this community. You have all the skills you'll need to make ENSIME even better.

All interactions within the ENSIME community have been friendly and supportive: we want this to continue, formalised by our [Code of Conduct](https://github.com/ensime/ensime-server/wiki/Code-of-Conduct).

This message has been brought to you by [consierge](https://github.com/Astrac/github-autoresponder).
