### ISSUE TITLE
Optimize semantic highlighting. Somehow...

### ISSUE THREAD

**Issue by aemoncannon** [ensime/ensime-emacs#312]
1) We unconditionally clear all overlays before applying new ones, so small edits with purely local effects end up triggering big repaints.

2) The results of a highlight are often invalidated before its received, but we still apply it.

Note: I'm not advocating a clever diffing approach. I think there is some easy, low-hanging fruit.

**Comment by fommil** [comment]
I was reading in the emacs lisp reference manual that overlays are slow and they recommend faces... so maybe we could do it that way.
