### ISSUE TITLE
no ensime connection in jump-to source in external jars

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#315]
I don't know how, but we managed to break this recently.

In https://github.com/fommil/ensime-server/tree/graphpocalypse I do a `M-.` on `Future` and when I am navigated to that file, the connection is gone.

**Comment by aemoncannon** [comment]
I bet I broke it. Needs a test.

**Comment by fommil** [comment]
@aemoncannon totally unrelated, if you want to understand how S-Express and the JSON magic works, check out my talk from Scala eXchange! https://t.co/vTnHXUmm2L Also (both of!) Rory's https://t.co/jnh2nPK944 https://t.co/zD4pnq7waZ

**Comment by aemoncannon** [comment]
Hmmm, I can't repro this on ensime project with latest master ensime-emacs. Hopping happily through akka sources.

**Comment by fommil** [comment]
Hmm. I'll check my setup.

**Comment by aemoncannon** [comment]
It could be an elisp caching thing.. If you have a long lived session. I
did roll my own crappy memoize..

**Comment by fommil** [comment]
btw, we can use `memoize` now if you want. I got it on-boarded at work :smile:

**Comment by fommil** [comment]
@aemoncannon any ideas on this one? It keeps stinging me, are you seeing it?

**Comment by fommil** [comment]
ok great, now it seems to be working for me. Perhaps just erratic.

**Comment by aemoncannon** [comment]
Would be useful to trace the args/result of config-includes-source-file to
see if there's any pattern.

**Comment by caoilte** [comment]
Here are some steps to reproduce this

1) Make sure Emacs not running
2) cd ensime-server
3) rm -rf .ensime*
4) sbt
5) gen-ensime
6) Start Emacs
7) Open File core/src/main/scala/org/ensime/util/Reporter.java
8) It should find the .ensime and start automatically.
9) Wait until Analyzing has finished
10) Goto Line 40 (definition of formatMessage)
11) Move cursor over "Position"
12) M-x "ensime-edit-definition"
13) Seems to hang for a while
14) Should go to Position.scala (in ensime-server/.ensime-cache/dep-src/source-jars/scala/reflect/internal/util)
15) Ensime should be stuck in Disconnected

**Comment by fommil** [comment]
can't reproduce :-/
