### ISSUE TITLE
:paste may be better than :load in ensime-inf-load-file

### ISSUE THREAD

**Issue by prateemmandal** [ensime/ensime-emacs#321]
I got into trouble while loading this code into scala> prompt using C-c C-v l (code and error is in the link below)
http://lpaste.net/148133

In the IRC chat room someone helpfully suggested to try out :paste which worked for me. Then I looked at what C-c C-v l was bound to and found that :load is used instead of :paste in ensime-inf-load-file. Then while searching the difference between :load and :paste I found this link
http://blog.japila.pl/2013/04/when-in-scala-repl-paste-might-be-your-better-friend-than-load/

There may be reasons because of which :load may be preferred. If not will it be better to change it to :paste?

**Comment by fommil** [comment]
Thank you for using ENSIME!

Most tickets can be resolved easily by following a simple process.

Before one of the core devs can respond to this ticket, please confirm the following:

1. you nuked ENSIME from your ivy cache (i.e. `rm -rf ~/.ivy2/cache/org.ensime`).
2. you are using the latest release of `ensime-emacs` (i.e. update `ensime` via MELPA).
3. you are using the latest release of `ensime-server` (i.e. type `M-x ensime-update`).
4. you checked the [tickets flagged as FAQ for Emacs](https://github.com/ensime/ensime-emacs/issues?labels=FAQ).
5. you checked the [tickets flagged as FAQ on the server](https://github.com/ensime/ensime-server/issues?labels=FAQ).
6. you checked the [most recently updated tickets](http://github.com/ensime/ensime-emacs/issues?direction=desc&sort=updated)
7. you checked `M-x customize-group ensime` (or viewed `ensime-vars.el`) to see if this is already handled.
8. (if you are using spacemacs) you asked on the spacemacs user list first.

If that solved your problem, great! Please close this ticket. If not, please read on...

There is very little we can do unless you provide us with a **minimal reproduction of the problem**. Please provide:

1. a standalone project on github (or use `ensime-server`)
2. step by step instructions to trigger the bug (videos are useful)
3. attach your `.ensime` to the repository (or in a gist)
4. also attach the output from the ENSIME server buffer
5. also attach an emacs stacktrace (if relevant), e.g. via `(setq debug-on-error t)`

**The next step is for us to help you create a unit test that fails.** We'll give as much help as we can, our goal is to grow this community. You have all the skills you'll need to make ENSIME even better.

All interactions within the ENSIME community have been friendly and supportive: we want this to continue, formalised by our [Code of Conduct](https://github.com/ensime/ensime-server/wiki/Code-of-Conduct).

This message has been brought to you by [consierge](https://github.com/Astrac/github-autoresponder).

**Comment by prateemmandal** [comment]
Hi Sam,

Please bear with me as I am new to the process.

I tried out the checklist and I seem to be safe.

I created a github repo with a minimal code that shows the issue. I included detailed setup and repro of the problem and possible workaround in the README.

https://github.com/prateemmandal/ensimebug

Please let me know if that will suffice.

**Comment by fommil** [comment]
OK great, I don't know this code very well but probably the best next step would be to try and reproduce this in a test in ensime-emacs. Do you think you'd be able to do that?

Our tests are all in one big file, which is scary, but all you'll need to do is find one that's close the what you want to do.

Maybe a good test would be sending some multiline string to the REPL and then closing the REPL? If it's difficult to get text back from the REPL we could make the code write something to a file.

**Comment by fommil** [comment]
Actually if it's really just a simple case of changing load to paste, then feel free to send a PR. Although I'd feel a lot happier if there was a test.
