### ISSUE TITLE
Stop closing my windows - too many ensime functions use (delete-window)

### ISSUE THREAD

**Issue by MrBones118** [ensime/ensime-emacs#332]
I frequently split my frame in to two windows, sometimes three or four.

Various functions in ensime use (delete-window) in their when their window is no longer to be displayed.

Off the top of my head, *ensime-compilation-result* will kill its window when you hit q, and so does the buffer that appears after invoking (ensime)

In comparison, many built in emacs things (like ibuffer, or buffer-menu, or package-menu) do not affect close windows if they did not create them.

A simple reproduction: open a frame with one window. split that window. invoke M-x ensime. second window disappears.

Desired behaviour - don't close windows that you didn't open. Possible additional behaviour: don't close windows inside process sentinels - this leads to windows magically disappearing when you're doing something else, which is quite disruptive.

**Comment by fommil** [comment]
@MrBones118 would you like to have a look into the code to see what can be done?

Ideally we'd like to replace a lot of custom major modes with new melpa standard packages.

**Comment by MrBones118** [comment]
I could certainly take a look. What are the new melpa standard packages?

**Comment by fommil** [comment]
don't know, but MELPA didn't really exist when ensime was originally written so there is probably a bunch of stuff that could be refactored to use external packages.

**Comment by fommil** [comment]
PRW
