### ISSUE TITLE
ensime-update doesn't send keypresses to sbt

### ISSUE THREAD

**Issue by greenrd** [ensime/ensime-emacs#334]
If you get an error in your global `plugins.sbt` or `build.sbt` and you have to press `r` to retry, ensime-update doesn't send the keypress to the underlying sbt process, so you have to kill the buffer and try running `ensime` again.

**Comment by fommil** [comment]
this sounds like a dupe

**Comment by fommil** [comment]
this will go away when we move to coursier, so I wouldn't spend too much time on it. There are also the assembly jars.

**Comment by fommil** [comment]
Supporting this would require a major rewrite of the update script. Since the easy solution is to kill the buffer and try again, I'm closing as `WontFix`
