### ISSUE TITLE
ensime-shutdown leaves stale port/http files on Windows

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#338]
I think we've seen this one before for clean shutdowns on windows.

**Comment by aemoncannon** [comment]
Related:
There's no clean way to 'steal' these resources. Sometimes I leave a screen
session open and then try to start a new session on the desktop and i have
to go find the screen session and kill it, or find all 5 lock files and
delete them one by one : (

**Comment by fommil** [comment]
Are you on windows at work too?

**Comment by aemoncannon** [comment]
Na linux

**Comment by fommil** [comment]
this is probably best fixed server side in https://github.com/ensime/ensime-server/issues/1277
