### ISSUE TITLE
Wiki disappeared?

### ISSUE THREAD

**Issue by timcharper** [ensime/ensime-emacs#340]
Lots of search results from Google point to wiki pages for this project, yet they redirect and no longer seem to work. Where did they go? If migrating, it seems like it'd be helpful to leave a wiki page behind with a link the new location.

**Comment by fommil** [comment]
Google will just have to catch up.

**Comment by timcharper** [comment]
:/

**Comment by fommil** [comment]
There is literally one line on every project's README now.
