### ISSUE TITLE
Project waiting for init...

### ISSUE THREAD

**Issue by rlvoyer** [ensime/ensime-emacs#341]
I have started Scala development on a new machine and I am unable to get ENSIME up and running. The ENSIME server logs this line and then never does anything else:

```
10:52:40.119 [default-akka.actor.default-dispatcher-4] INFO  org.ensime.server.Project - Project waiting for init...
```

I'm seeing this behavior when attempting to get it working for development on the ensime-server project, but I've confirmed that the behavior is consistent w/ other Scala projects on my machine. Here's what my environment looks like:

OS: OS X 10.11.2
Java: Java HotSpot(TM) 64-Bit Server VM 25.65-b01, Java(TM) SE Runtime Environment 1.8.0_65-b17
Scala: 2.11.7
Ensime: 0.9.10-SNAPSHOT
Emacs: 24.5

I tried everything listed on the [ENSIME Troubleshooting page](http://ensime.github.io/editors/emacs/troubleshooting/). I started by ensuring that my ensime-server checkout was clean:

```sh
➜  ensime-server git:(master) pwd
/Users/rlvoyer/Code/ensime-server
➜  ensime-server git:(master) rm -rf .ensime .ensime_cache target
```

Then I cleared out any ENSIME artifacts my ivy cache:

```sh
➜  ensime-server git:(master) rm -rf ~/.ivy2/cache/org.ensime
```

To ensure a clean install of ensime-emacs, I deleted ensime and then re-installed from the package-list menu (see the compilation output [here](https://gist.github.com/b440c5da8e24cbaab975)).

I read [here](https://github.com/ensime/ensime-server/issues/310) that the melpa-compiled .elc files can be problematic, so I cleared those out like so:

```sh
➜  ensime-server git:(master) cd ~/.emacs.d/elpa/ensime-20160109.1159
➜  ensime-20160109.1159  find . -name "*.elc" | xargs rm
```

Then I recompile those elisp files myself from Emacs via `M-x byte-recompile-directory`:

```
Byte recompile directory: ~/.emacs.d/elpa/ensime-20160109.1159/
```

Back at the command-line, I ran sbt gen-ensime to create an ensime config from within the ensime-server directory:

```sh
➜  ensime-server git:(master) sbt gen-ensime
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
[info] Loading global plugins from /Users/rlvoyer/.sbt/0.13/plugins
[info] Loading project definition from /Users/rlvoyer/Code/ensime-server/project
[info] Set current project to ensime (in build file:/Users/rlvoyer/Code/ensime-server/)
[info] ENSIME update. Please vote for https://github.com/sbt/sbt/issues/2266
[info] Updating {file:/Users/rlvoyer/Code/ensime-server/}ensime...
[info] Done updating.
[info] ENSIME updateClassifiers. Please vote for https://github.com/sbt/sbt/issues/1930
[info] ENSIME processing testingImplicits (testingImplicits)
[info] ENSIME processing testingDebug (testingDebug)
[info] ENSIME processing testingDocs (testingDocs)
[info] ENSIME processing core (core)
[info] ENSIME processing swank (swank)
[info] ENSIME processing api (api)
[info] ENSIME processing testingEmpty (testingEmpty)
[info] ENSIME processing server (server)
[info] ENSIME processing testingSimple (testingSimple)
[info] ENSIME processing testingTiming (testingTiming)
[info] ENSIME processing sexpress (sexpress)
[info] ENSIME processing testingJava (testingJava)
[info] ENSIME processing util (util)
[info] ENSIME processing ensime (ensime)
[info] ENSIME processing jerk (jerk)
[warn] Some source directories do not exist and will be ignored by ENSIME.
[warn] For example: /Users/rlvoyer/Code/ensime-server/testing/debug/src/test/scala,/Users/rlvoyer/Code/ensime-server/src/test/scala,/Users/rlvoyer/Code/ensime-server/testing/timing/src/test/scala,/Users/rlvoyer/Code/ensime-server/testing/implicits/src/test/scala,/Users/rlvoyer/Code/ensime-server/testing/docs/src/test/scala
```

Then I opened a file from ensime-server in Emacs:

```sh
➜  ensime-server git:(master) emacs core/src/main/scala/org/ensime/indexer/ClassfileIndexer.scala
```

Within emacs, I ran ensime-update, via `M-x ensime-update`, and specified my newly created .ensime file as the ENSIME project file:

```
ENSIME Project file: ~/Code/ensime-server/.ensime
```

I then attempted to startup ensime using the same config file as above, via `M-x ensime` (`ENSIME Project file: ~/Code/ensime-server/.ensime`), while editing the same ensime-server file mentioned above (core/src/main/scala/org/ensime/indexer/ClassfileIndexer.scala).

See the contents of the *inferior-ensime-server-ensime-server* buffer [in this gist](https://gist.github.com/rlvoyer/9574c4e6ca2c0f626473).

See the contents of my corresponding .ensime file [in this gist](https://gist.github.com/rlvoyer/aa52b978b22df056324e).

Let me know if there are any other details I can provide to help figure this out, and thanks in advance for any guidance you can offer!

**Comment by fommil** [comment]
elc cleanup is erroneous. What SBT script do you use?

**Comment by fommil** [comment]
BTW, possibly related, but ensime is built with Java 6, not 8. Your tests will fail.

**Comment by fommil** [comment]
Are you sure you've not got anything in your LOCAL ivy cache, not the cache dir.

**Comment by fommil** [comment]
In fact, I know you due because I can see it in the log :wink: /Users/rlvoyer/.ivy2/local/org.ensime/ensime_2.11/0.9.10-SNAPSHOT

NEXT!

**Comment by rlvoyer** [comment]
Bam. Thanks so much! Sorry I missed that. I had forgotten about ~/.ivy2/local.
