### ISSUE TITLE
instead of using sbt from the PATH, first check the sbt-mode

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#344]
`sbt:program-name` may be set correctly (and its easy for us to document for new starters instead of PATH setups)

**Comment by sellout** [comment]
Can you assign this to me?

I think it makes sense to _only_ use `sbt:program-name`, as the default value for it is simply “sbt”, which effectively looks in PATH. So, any other value is something the user apparently wanted, even if it’s `nil`.  (And I feel like that goes along with the other “exorcize Ensime’s internal sbt stuff”.)

**Comment by fommil** [comment]
Yup. I can't assign in the mobile app though.

**Comment by d1egoaz** [comment]
Is the idea of this PR to replace the uses of `ensime-sbt-command` variable with `sbt-command` here:
https://github.com/ensime/ensime-emacs/search?utf8=%E2%9C%93&q=ensime-sbt-command

**Comment by fommil** [comment]
Yup sounds about right

**Comment by fommil** [comment]
dupe
