### ISSUE TITLE
`ensime-search-mode-hooks` is ignored when entering `ensime-search-mode`

### ISSUE THREAD

**Issue by timcharper** [ensime/ensime-emacs#351]
With `evil-mode`, you can specify the initial editing mode for major modes; to do this, it adds a hook for the major mode to set whether it should start with emacs editing, vim compat insert editing, or vim compat modal mode.

In order for this to work, `ensime-search-mode-hooks` needs to be evaluated on instantiation of the major mode.

**Comment by fommil** [comment]
Sounds like that should be easy to implement, want the give it a try? Should be easy enough to test too
