### ISSUE TITLE
model the API with defclasses

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#356]
@aemoncannon 

Just a thought, but we could use `alists` instead of data lists when we define the auto-magic SWANKY http://endlessparentheses.com/new-on-elpa-and-in-emacs-25-1-let-alist.html

(big change to client, definitely a 2.0 thing...)

**Comment by fommil** [comment]
changing the title because after reading up on it, I think the emacs object model is strong enough to support our API: https://emacs.stackexchange.com/questions/22544/with-accessors-for-all-accessors https://emacs.stackexchange.com/questions/22543/eieio-defclasses-as-plists

**Comment by iravid** [comment]
Adding here for documentation: https://github.com/sigma/marshal.el

**Comment by fommil** [comment]
Very nice find
