### ISSUE TITLE
Don't re-configure company

### ISSUE THREAD

**Issue by iced** [ensime/ensime-emacs#362]
https://github.com/ensime/ensime-emacs/blob/master/ensime-company.el#L126

Some of us got company configured the way we want. Please, don't touch such settings.

**Comment by iced** [comment]
What makes it worse, the way you set it makes virtually impossible to hook/reset it. Forced to hack it in installed ensime for now. Please fix it.

**Comment by fommil** [comment]
pull requests welcome.

**Comment by iced** [comment]
https://github.com/ensime/ensime-emacs/pull/363
