### ISSUE TITLE
M-x ensime-troubleshooting

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#364]
It would be good to package this as a command so we can ask people to type it on the gitter chat room and here when new users post very vague bug reports.

**Comment by d1egoaz** [comment]
What information would you like to include in the report?

I just read this issue https://github.com/ensime/ensime-emacs/issues/225 and it comes to my mind that this info might help?

- OS
- Emacs version
- ensime-sbt-command variable content
- debug-on-error variable status
- backtrace, is it always a buffer?
- .ensime file from current project if exists
- exec-path content

**Comment by fommil** [comment]
Sounds good, the most important thing is for it to remind people not to post everything directly to gitter, and also to remember to go through the checklist.
