### ISSUE TITLE
remove use of the old refactoring API

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#370]
https://github.com/ensime/ensime-server/issues/1293

**Comment by lxol** [comment]
`ensime-refactor-add-import` is the only function left that uses the old `ensime-refactor-prepare`.  Shall I remove it along with all legacy refactoring query functions. It looks like it is broken anyway.

**Comment by fommil** [comment]
+1

**Comment by aemoncannon** [comment]
+1
