### ISSUE TITLE
method completion: better default behaviour

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#373]
sometimes I want to insert a method completion but not provide any of the parameters (e.g. if I am changing the method that I'm calling and already have the parameter list)

I think it would be very convenient if the parameters were not inserted if I type the spacebar (like an "empty" hint).

e.g.

```scala
thing.foo(a, b, c)
```

I delete `foo` and complete bar, it looks like this

```scala
thing.bar(a: java.lang.String, b: scala.Int, c: scala.Boolean)(a, b, c)
```

with the point at `a` and the tab jumping enabled for the three parameters. I want, in a single keystroke (space) to go to

```scala
thing.bar(a, b, c)
```

@aemoncannon do you ever get this in Java land too?

**Comment by aemoncannon** [comment]
Yeah for sure, I hit this all the time. I think I filed a bug about it before... Special key could work.

**Comment by aemoncannon** [comment]
Should check what intellij / eclipse does..

**Comment by fommil** [comment]
it's not a real bug report unless it has 6 dupes.

**Comment by fommil** [comment]
I suppose we could auto detect if the next character is `(` or `{` and not expand in that case... in magical unicorn world we'd take a diff of the parameters that are there and what the new requirements and then go to exactly that slot.

**Comment by aemoncannon** [comment]
Yeah. That sounds tough.. but this is suuuuch a bread & butter feature. Challenge accepted? Unfortunately I don't see a good way of leaning on the server for this, as it depends on which completion is chosen, and involves broken syntax. Yay parsing scala in elisp!

**Comment by aemoncannon** [comment]
Data point: Android Studio (based on intellij) doesn't do anything fancy. First off it doesn't insert a param template to begin with.. just shows a help hint in the status bar when you're within the parens. And if you re-type a method name per above, it just duplicates the name with a trailing semi. E.g.

myFun<TAB> => myFunction()
myFun<TAB>myFunction(arg1, arg2) => myFunction();myFunction()

I'm an intellij noob but I don't see any setting for making this fancier.

**Comment by aemoncannon** [comment]
Note: fancier is not necessarily better. Could be they're taking the wise road by getting out of the programmer's way.

**Comment by fommil** [comment]
Winning.

**Comment by fommil** [comment]
(Serious point: I think detecting a `(` in key here)
