### ISSUE TITLE
ensime-import-type-at-point doesn't seem to like scalaz disjunction (\/)

### ISSUE THREAD

**Issue by caoilte** [ensime/ensime-emacs#375]
So, the very first time I tried to use 'ensime-import-type-at-point' it didn't do anything at all. It turns out that was probably because I was trying it out on a scalaz disjunction (\/). It worked when I tried using it on an alphabetic type.

Even if Ensime can't be changed to work on disjunction, it would be nice if it could tell you that it couldn't find a type where your cursor is as I was quite confused for a while.

**Comment by fommil** [comment]
So, that template we just showed you? :-P

**Comment by fommil** [comment]
I'm pretty sure this is a server bug, can you please reopen on `ensime-server` (and follow the template guide this time :stuck_out_tongue_winking_eye: : )

**Comment by caoilte** [comment]
### Steps to reproduce

1. Using Emacs/Ensime open a project with scalaz as a dependency
2. Declare a scalaz either type eg val x = String \/ String (https://github.com/scalaz/scalaz/blob/d6311bdfdd96d06db52384cfb65489f64f79fc5e/core/src/main/scala/scalaz/Either.scala#L27)
3. Move cursor over \/ and execute ensime-import-type-at-point

### Expected behaviour

Emacs/Ensime to make request to server for type at that location

### Actual behaviour

Emacs/Ensime does nothing at all (nothing gets printed in *ensime-events* buffer)

### Errata

I tried reproducing this with a local type, but I can't get Ensime Server to find local types at all. Possibly it only works with types in dependent JARs?

I will try and create a failing test case in `ensime-tests.el` but this may take a while as I haven't done any Lisp for 14 years.

**Comment by fommil** [comment]
can you try to create a standalone zero-dependency scala file that exhibits the problem?

**Comment by caoilte** [comment]
This gist exhibits the problem.

https://gist.github.com/caoilte/d33bdfbb2b87215a7e1a

Emacs sends the request for the `Bar` type but not for the `/\` type. Frustratingly ensime-server doesn't find anything useful for the `Bar` type though.

**Comment by fommil** [comment]
it won't until you compile the file. It's incredibly rare that you'd want to import a class from the file that you're in.

**Comment by caoilte** [comment]
I created a project 

https://github.com/caoilte/ensime-bugs/tree/master/375

where you can see the problem if you follow the instructions in

https://github.com/caoilte/ensime-bugs/blob/master/375/src/main/scala/bug/Bug.scala

**Comment by fommil** [comment]
@hvesalai this is an interesting bug possibly in both ensime server, ensime client and scala-mode. Is there some regex rule that isn't happy with weird characters in class names?

**Comment by fommil** [comment]
@caoilte that's three excellent reproductions! Which one is annoying you the most? so we can help you automate a test, then fix it :smile:

**Comment by fommil** [comment]
@caoilte do you think you'll be able to find the time to fix this? I don't use scalaz or fancy classnames like this so chances of me fixing this are exactly 0%
