### ISSUE TITLE
insert type at point

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#379]
it'd be nice to be able to ask for the type at point and then insert its short name after a colon. It sounds like we might be able to do this without any specific server support, just with regexes / the expand region support.

**Comment by greenrd** [comment]
`C-u C-c C-v t` for this?

**Comment by fommil** [comment]
well that's what I currently do, which involves a lot of manual steps to move to the right place, enter the colon, and paste. In IntelliJ they can do this with a single keybinding.

**Comment by aemoncannon** [comment]
yeah we could have ensime-add-type-annotation. that'd be neat.

**Comment by aemoncannon** [comment]
actually i think i did this in a live-coding ensime talk at some point ;-)

**Comment by tbje** [comment]
I like the idea of add-type-annotation. This one just adds it to the kill-ring:
```
(defun ensime-kill-type-at-point ()
  "Puts the simple name of type at point at the kill ring for easy insertion. A ":" is prepended."
  (interactive)
  (let ((pack-path (ensime-package-path-at-point)))
    (cond ((ensime-visiting-java-file-p)
	   (ensime-inspect-java-type-at-point))
	  (t ;; inspect package if package under point
	   (unless pack-path
	     ;; otherwise, inspect type
	     (let* ((inspect-info (ensime-type-inspect-info-at-point)))
               (kill-new (format ": %s" (plist-get (plist-get inspect-info :type) :name)))))))))
```

**Comment by fommil** [comment]
@tbje is this doing anything more than `C-u C-c C-v t` ?

**Comment by tbje** [comment]
@fommil Ah, didn't know the trick and missed the comment. 

To answer your question, apart from returning the simple / stripped name and the additional ":" no. I guess I could try to improve it a bit so that it actually inserts it in front of the next =. What do you think?

**Comment by tbje** [comment]
```
(defun ensime-add-type-annotation ()
  "Add a type annotation for type at point"
  (interactive)
  (let ((pack-path (ensime-package-path-at-point)))
    (cond ((ensime-visiting-java-file-p)
       (ensime-inspect-java-type-at-point))
      (t 
       (unless pack-path
         (let* ((inspect-info (ensime-type-inspect-info-at-point)))
           (save-excursion
             (search-forward " =")
             (backward-char 2)
             (insert (format ": %s" (ensime-type-name-with-args (plist-get inspect-info :type))))))))))))
```

I only tested it for simple cases. Is there a way to find out if full type is required ?

**Comment by aemoncannon** [comment]
Note -- I think you can use ensime-type-at-point?
type-inspect-info-at-point does a lot more work.

**Comment by fommil** [comment]
there are also the expand region commands, which could be useful for non-val/def use cases

**Comment by fommil** [comment]
nice, that worked in my test case :smile:
