### ISSUE TITLE
License version inconsistencies

### ISSUE THREAD

**Issue by greenrd** [ensime/ensime-emacs#380]
`LICENSE.txt` is GPL 3, the header at the top of `ensime.el` doesn't specify a GPL version so it could become GPL 4 if there ever is a GPL 4, and the header at the top of `ensime-debug.el` says GPL v2 or later. None of this is contradictory, but it is inconsistent, and I think we should standardise the license version in all files (and standardise the header text, while we're at it).

@aemoncannon

**Comment by aemoncannon** [comment]
Sgtm

**Comment by fommil** [comment]
Yeah. Btw, I've been using a short form in all new files. Have a look at my Emacs config to see how i set up yatemplate for this.
