### ISSUE TITLE
Leaving paste mode kills the repl session

### ISSUE THREAD

**Issue by xificurC** [ensime/ensime-emacs#383]
### Steps to reproduce
1. Open a scala file and start ensime (`M-x ensime`)
2. Start the repl (`C-c C-v z`)
3. Enter paste mode (type ":paste" into the repl)
4. Leave paste mode with `C-d`
### Expected behaviour

Paste mode successfully finished
### Actual behaviour

Paste mode successfully finished, repl killed right afterwards.
### What is paste mode for

Paste mode is e.g. needed when defining a class with a companion object. In a normal file one could have

``` scala
class Something {
  ...
}

object Something {
  ...
}
```

and compiling that woks just fine. Entering it into the repl will not work correctly though because the class would be defined with the closing bracket and once that's done we cannot implement a companion object. That's why there's paste mode, the repl will read everything in 1 bulk and then this works.

**Comment by fommil** [comment]
can you give some more details in the reproduction please? People might not know what paste mode is, or which exact ensime-emacs commands to run to get there.

Some example scala code to paste would also be good that demonstrates the need to `:paste`

**Comment by xificurC** [comment]
Added more info

**Comment by fommil** [comment]
we're been chatting on gitter, do you feel you have enough information about how this works to try and put together a fix? We're happy to help (although I'm not the greatest elisper in the world)

**Comment by fommil** [comment]
@xificurC ! Ping

**Comment by xificurC** [comment]
Hey @fommil , sorry but I'm low on free time so I'm not going to chase this
