### ISSUE TITLE
Cannot launch SBT

### ISSUE THREAD

**Issue by igrishaev** [ensime/ensime-emacs#391]
### Steps to reproduce

1. run ensime with `M-x ensime`
2. try to run `M-x ensime-sbt` or `M-x sbt-start` 

### Expected behaviour
I believe a buffer should open with sbt prompt

### Actual behaviour
no sbt buffer and error `abbreviate-file-name: Wrong type argument: stringp, nil`

tested on both Mac and Ubuntu (under vagrant) in terminal, 24.5 and 24.3

**Comment by fommil** [comment]
you'd be best asking on gitter for this, after you read through the Getting Help page.

**Comment by fommil** [comment]
I updated this page recently, you might want to make sure you followed these newer instructions http://ensime.github.io/editors/emacs/install/

**Comment by igrishaev** [comment]
I've solved the issue reading the help for `sbt:find-root` function.

```
  - a directory containing a 'project/build.properties' in it.

  - a directory that contains a file matching one of the patterns
    '*.sbt' or 'project/*.scala' file in it.
```
Once I created a `*.sbt` file, it started working OK.
