### ISSUE TITLE
ensime-import-type-at-point strange behaviour without a package declaration

### ISSUE THREAD

**Issue by bomgar** [ensime/ensime-emacs#393]
### Steps to reproduce

1. A scala file without a package declaration and no blank lines before the import statements
2. Use ensime-import-type-at-point for a type not imported yet

### Expected behaviour

The import should not be inserted in a new line.

### Actual behaviour

The import statement is inserted in 2 parts. The "i" is the first character in the first line followed by the import statement that was there before. The rest of the statement is in the second line.

**Comment by fommil** [comment]
can you please provide more detail in the production please, e.g. a minimal test project on github.

**Comment by fommil** [comment]
or, better yet, write it up as a failing test in the emacs tests.

**Comment by bomgar** [comment]
In the Hello.scala is an import missing. Try importing it.
https://github.com/bomgar/ensime-emacs-import-test

**Comment by fommil** [comment]
ok, I can see that. If you could minimise a little further and get it into one file, the next step would be to write up a unit test in ensime-emacs. The contributing page gives instructions on how to do that, ask if you need help.

**Comment by bomgar** [comment]
I tried to move everything in the same file. This makes it even worse. The import is inserted in the inner package (which contains the class) instead.
https://github.com/bomgar/ensime-emacs-import-test/tree/one-file

**Comment by fommil** [comment]
Ok, sounds like two separate bugs each requiring a test.

You can reproduce the first bug by importing a class that's not in your project.

Have you read the contributor docs yet? I think this will be easy to fix once you have failing tests in place.

**Comment by bomgar** [comment]
I wrote a test. Now what? Should I create a pull request with the test?

**Comment by fommil** [comment]
Cool! Well now let's try to fix it :-) do you know how to step debug it Emacs lisp the find out which functions are being called for your usecase? Once we know which exact line is causing the problem, the fix might be obvious.

**Comment by fommil** [comment]
ok, looks like `ensime-import-type-at-point` is actually mostly implemented client side (see `ensime-client.el`) so that's where to start.

Note that the whole function only calls out to the ensime server in one place (`ensime-rpc-import-suggestions-at-point`) so you could potentially rewrite your test to be a unit test (without the server) and just mock out this one function. That should speed up the test cycle significantly. We have ert and cucumber style tests, the cucumber ones might be more appropriate for this.

**Comment by bomgar** [comment]
I do not know how to debug elisp. Would be great if you can point me to a documentation on how to do that. So far i figured out when ensime-insert-new-import-next-line is called the (point) is 1. But when the lamda is executed the point somehow is 2.

**Comment by fommil** [comment]
have you read through http://ensime.org/contributing/  yet? There is an emacs specific section, which recommends the Emacs Lisp Guide, which has a section on debugging. It's quite impressive actually.

**Comment by bomgar** [comment]
I got it fixed. But I'm not sure if this is the way to do it.

**Comment by fommil** [comment]
great stuff! Please squash these commits and raise as a PR.

Did you also have a second failing case?

**Comment by bomgar** [comment]
I have. But that problem deserves its own issue.
