### ISSUE TITLE
Ensime plugin breaks redo functionality from undo tree plugin

### ISSUE THREAD

**Issue by kurnevsky** [ensime/ensime-emacs#394]
### Steps to reproduce

1. Install and activate both undo tree and ensime plugins.
2. Open any scala file.
3. Type something.
4. Undo.
5. Redo.

### Expected behaviour

Typed text appears.

### Actual behaviour

It writes "No further redo information".

**Comment by fommil** [comment]
you'll need to include a lot more information for your reproduction, e.g. initial state, exact actions. I have been using undo-tree with ensime for a very long time and there are no problems for me. Closing until you can reproduce.

**Comment by kurnevsky** [comment]
@fommil 
Here is minimal config for reproducing (last binding is important, without it redo works, I don't know why):

`(setq package-list '(ensime undo-tree))
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(package-initialize)
(unless package-archive-contents
  (package-refresh-contents))
(dolist (package package-list)
  (unless (package-installed-p package)
    (package-install package)))
(require 'undo-tree)
(require 'ensime)
(cua-mode t)
(global-undo-tree-mode)
(setq undo-tree-enable-undo-in-region nil)
(add-hook 'scala-mode-hook 'ensime-scala-mode-hook)
(define-key undo-tree-map (kbd "C-/") nil)
(global-set-key (kbd "C-S-z") 'undo-tree-redo)
(global-set-key (kbd "C-y") 'undo-tree-redo)
(global-set-key (kbd "C-o") 'find-file)
(define-key ensime-mode-map (kbd "C-/ e") 'ensime-print-errors-at-point)
(define-key ensime-mode-map (kbd "C-/ t") 'ensime-inspect-type-at-point)`

**Comment by fommil** [comment]
what text do you have on the screen and what did you type? Can you perhaps make a screencast?

I suspect that one of these is causing the confusion

```elisp
(cua-mode t)
(setq undo-tree-enable-undo-in-region nil)
```

or one of these bindings is winning over your `C-/` binding

```
(define-key ensime-mode-map (kbd "C-/ e") 'ensime-print-errors-at-point)
(define-key ensime-mode-map (kbd "C-/ t") 'ensime-inspect-type-at-point)
```

**Comment by kurnevsky** [comment]
@fommil 
It can be reproduced on any scala file, it is not matter what are you typing.
And you are right - without last two bindings it works. But why? I try to redo by C-S-z (as defined in config).
