### ISSUE TITLE
over time, ensime becomes very slow

### ISSUE THREAD

**Issue by svalaskevicius** [ensime/ensime-emacs#397]
### Steps to reproduce

1. just use ensime in emacs.

### Expected behaviour

emacs performance not to degrade over time.

### Actual behaviour

after a while (~1-2 hours of usage), emacs becomes unbearably slow (gradually). I don't even see my cursor when moving it.

`ensime-shutdown` and then `ensime` commands seem to make it even worse. same with `ensime-reload`

only a full restart of emacs brings it to the initial performance again.

**Comment by aemoncannon** [comment]
Can you capture a profiling trace with profiler-start, profiler-report ?

**Comment by fommil** [comment]
Are you sure this is ensime? Because if you run ensime-shutdown it will actually kill ensime.

**Comment by svalaskevicius** [comment]
well, as I didn't know how to profile it was just an assumption (based on the grounds that it didn't use to happen without ensime), next time it happens I'll update the ticket with the results from the emacs profiler and reopen it.

btw, thx for the tip re profiler :)
