### ISSUE TITLE
`ensime-typecheck-current-buffer` command is not working

### ISSUE THREAD

**Issue by hujianxin** [ensime/ensime-emacs#405]
### What happened
Now, I use spacemacs as my config file. I use ensime-emacs as my Scala environment. Everything is OK, except that the `ensime-typecheck-current-buffer` command is not working. This funtion is binded to `C-c C-c c`.
### Expected behaviour 

When I enter `C-c C-c c` key, nothing happens!  Opposite of this, when I enter `ensime-typecheck-all`, ensime will show the error or warning in my project. 

So, I think It is the problem `ensime-typecheck-current-buffer`

**Comment by fommil** [comment]
I'm afraid that's not enough information. Can you please give a full reproduction, ideally in the form of a unit or integration test? A github repository with exact instructions for somebody to follow, like a script, is also good. http://ensime.org/getting_help/

We have very good documentation at http://ensime.org/contributing/ to help you get started hacking on ENSIME.

**Comment by fommil** [comment]
Can you please give a reproduction in the form of a unit or integration test? A github repository with exact instructions for somebody to follow, like a script, is also a good starting point. We are more than happy to help you turn it into an automated test, and discuss ideas on how to fix it. Read the http://ensime.org/contributing guide for more information.

We close tickets that look like a known issue or don't provide the details requested by the template, but it's not the end of the conversation and we will open it up again when there is enough information to go on. This is to improve the quality of our issue tracker and to make it easier for contributors to help.

We will reopen this ticket if you can confirm it is a bug by giving us a **detailed** reproduction. Please read the http://ensime.org/getting_help guide to understand the steps that are required prior to submitting a bug report.
