### ISSUE TITLE
use TRAMP to connect to remote build, sources, and ensime-server

### ISSUE THREAD

**Issue by biocyberman** [ensime/ensime-emacs#411]
### Steps to reproduce

1. Create a project on a remote host
2. Start local emacs instance, connect and edit files via `tramp` method. That is to open a file with this path format: `/ssh:remoteuser@remotehost#portnumber:/path/to/file`
3. Start ensime with `M-x ensime /ssh:remoteuser@remotehost:portnumber/path/to/project/.ensime`

### Expected behaviour

ensime should use sbt, java, and other dependencies on the remote host. This make local ensime-emacs a true client.

### Actual behaviour

ensime-emacs is asking for java and sbt from local host. So I get errors like:

`Error java command /path/on/remotehost/jvm/bin/java not found` even though I have java at`/path/to/localhost/jvm/bin/java`

I anticipate that this maybe just something I have to live with because of ensime's design decision. It makes the implementation simpler. But if that is something the developers want to improve, I welcome this feature.

**Comment by fommil** [comment]
this would involve extreme amounts of refactoring to handle your usecase. Just use emacs on the remote.

**Comment by fommil** [comment]
(btw, happy to open this up again if you volunteer to do the work... but it really is an extreme amount of work... and I'm also not keen on allowing the ensime server to listen to non-`localhost` for security reasons)

**Comment by fommil** [comment]
Actually, maybe I should open this again and flag as an Epic incase somebody wants to use it. A lot of people ask, so I'll also flag as FAQ.

**Comment by biocyberman** [comment]
This is definitely a FAQ. Yes, I am using emacs in the terminal to the remote host. Everything works, except some problems with incorrect key bindings and poor color support in the terminal. I solved the later by applying some patches, but the key binding come back once a while. It is an Emacs problem that the GUI version and the terminal version behave differently. It's usually the terminal version has degraded functionality.

**Comment by fommil** [comment]
honestly this is such a huge request that it would realistically require somebody to work on it full time for months. Closing due to lack of interest in implementing it.
