### ISSUE TITLE
cannot find akka-actor_2.10-2.3.0.jar SystemActor and anything

### ISSUE THREAD

**Issue by JacobPigW** [ensime/ensime-emacs#413]
1. I add a line in build.sbt : 
`libraryDependencies ++= Seq(
  "com.typesafe.akka" %% "akka-actor" % "2.3.0"
)`

2. In Emacs, `M+x ensime-refresh-config RET`, then update /path/to/.ensime file, and download akka-actor_2.10-2.3.0.jar in ~/.ivy2/ directory

3. Open a scala file, such as Test.scala. When I input `SystemActor`, I cant import, and I got a error `ERROR: not found: value SystemActor : line 8`

Can anybody help me?

**Comment by fommil** [comment]
Restart ensime
