### ISSUE TITLE
Worksheets: evaluate in REPL and display inline, like CIDER

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#415]
Basically do this https://mobile.twitter.com/emacs/status/720267997806329857 but for scala code

**Comment by malchmih** [comment]
This would be really great!

**Comment by fommil** [comment]
@lxol and @VlachJosef said they were interested in looking at this :smile:

**Comment by kozikow** [comment]
I ended up mixing some of things about this ticket in the other ticket https://github.com/ensime/ensime-emacs/issues/437#issuecomment-225516490 . Both tickets are related.

**Comment by fommil** [comment]
this ticket is a bit sparse... I guess all the discussion has been In Real Life! :smile:

There are several components to this:

1. discover what the region to be evaluated is. Trivial in lisp, in scala we need to talk to the server (implied curly brackets)
2. take that code and run it in the REPL, then parse the repl output. Basically the black box: code in, result string out.
3. display it in the right place

generalises to other languages.

@kozikow are you still hacking in scala, did you get anywhere with this? Are you coming to the church of emacs tonight?

**Comment by KyleErwin** [comment]
Hi @fommil :) Was this ever implemented?

**Comment by fommil** [comment]
~~No it wasn't.~~ (by me anyway)

BTW, I am not maintaining ensime anymore http://ensime.github.io/maintainer/

And you won't get any answer here from me: https://www.reddit.com/r/scala/comments/apq6si/ensime_worksheetscratch_file_evaulation/ because the reddit moderators have permanently banned me because of this post https://www.reddit.com/r/scala/comments/afor0h/scalaz_8_timeline/ee1qlbg/

**Comment by lxol** [comment]
@KyleErwin  I remember I submitted a PR for that more than 2 years ago. It just tested it and looks like it still works. 
Open REPL (ensime-inf-switch), select a region that you want to evaluate and run `ensime-inf-eval-region`. 
The region will be evaluated in the REPL and the result will be displayed as an overlay in the buffer.
