### ISSUE TITLE
Ensime server won't start with `reference to write is ambiguous`

### ISSUE THREAD

**Issue by juanjovazquez** [ensime/ensime-emacs#421]
The issue reported [here](https://github.com/ensime/ensime-atom/issues/79) is also happening with emacs. Same reason probably.

**Comment by fommil** [comment]
this is a problem with your personal sbt config.

**Comment by fommil** [comment]
this is a problem with your personal sbt config, I recommend just changing it so that you don't import any symbols that conflict with `write`. No doubt this will save you lots of trouble in the future on other projects.
