### ISSUE TITLE
support for ensime-sbt's ensimeCompileOnly task

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#423]
https://github.com/ensime/ensime-sbt/issues/181

**Comment by fommil** [comment]
@jmpage this is also another easy-ish one. The idea here would be to create a command that:

1. discovers the name of the subproject that the current buffer is in
2. creates a command such as `subproject/compileOnly /full/path/to/current/Buffer.scala` (it should be possible to add a test for this, you might need to mock out some ensime function that returns the config for the file)
3. sends to `sbt-command`
4. add a keyboard shortcut and menu entry under the `C-c C-b` (sbt) namespace.

We'll probably rename `compileOnly` to `ensimeCompileOnly` but I'll take care of renaming the command when I do that.

**Comment by jmpage** [comment]
Thanks for the suggestion. I think I got a handle on what I need to do. Hopefully I'll have a PR ready soon!

**Comment by fommil** [comment]
FYI I renamed this to `ensimeCompileOnly` in sbt-ensime 0.6.
