### ISSUE TITLE
Server connection closed unexpectedly when using flx-ido

### ISSUE THREAD

**Issue by zainab-ali** [ensime/ensime-emacs#436]
### Steps to reproduce

os: Linux
emacs version: 24.5
build tools: sbt

1. Using this [init.el](https://gist.github.com/zainab-ali/5453b61fe2f3e4af07b91fdade78f0d1)
2. Run `M-x ensime`

### Expected behaviour

ensime server starts up.

### Actual behaviour

[\*Messages\* buffer](https://gist.github.com/zainab-ali/bb8ad516424f650dff461af73be3484b) shows `Server connection closed unexpectedly: connection broken by remote peer`

[\*inferior-ensime-server\* buffer](https://gist.github.com/zainab-ali/6d8ec223b2225e068869ddfc6b39822f) has a `java.lang.Exception: Failed to parse sexp: Invalid input '#', expected Comment, WhiteSpacePredicate or SexpP`

**Comment by fommil** [comment]
this one is truly weird

**Comment by fommil** [comment]
in gitter you said you localised the problem to `flx-ido`, do you know exactly which lines cause the trouble?

**Comment by zainab-ali** [comment]
It's not linked to any particular `flx-ido` parameters that I can see, but I haven't had the chance to debug the lisp script.  Enabling `ido-mode` is enough to cause the error.

**Comment by zainab-ali** [comment]
Weirdly enough, I can use `ido`, just not `flx-ido`:
```
(require 'ido)
(ido-mode 1)
```
works fine

**Comment by fommil** [comment]
Might be worth asking the other if they have any ideas. Can you please write a full screen of every command you do, potentially a screencast?

**Comment by zainab-ali** [comment]
I think I'll be able to debug it better once I learned more `elisp` - I'm going to do so when I have some time free. I'll get back to you once I find a solution.

**Comment by fommil** [comment]
this seems to be related to your setup, can't be reproduced.
