### ISSUE TITLE
persistent show type at point

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#437]
it'd be really nice if the `C-c C-v t` command showed the type inline, but didn't change the source buffer (i.e. a read only view). A bit like what we would want for REPL / Debugging interaction. @lxol

**Comment by kozikow** [comment]
I'd take a shot at it today - I will update what I concluded or achieved by the end of the day.

**Comment by kozikow** [comment]
![screenshot from 2016-06-11 16-53-05](https://cloud.githubusercontent.com/assets/722866/15986086/d865c8cc-2ff6-11e6-9889-cba20fcceb53.png)

I got a prototype working. I need to clean some things before sending PR.
Rought outline:
1. Send to repl via the ensime-inf-eval-region,
2. get output via the comint-output-filter-functions (ensime-inferior-scala buffer)
3. Passed to cider--make-result-overlay
4. cider--make-result-overlay can be extracted from cider.

**Comment by fommil** [comment]
Nice! Looking forward to it

**Comment by kozikow** [comment]
IMO simple pop up could be better:

-   Uses just built in, standard command popup-tip. Honors customizations people have for popup-tip.
-   No need for pulling anything from cider.
-   Better handles multi line string. See screenshots.

[Cider way of showing data could be better for something like IntelliJ debugger inline-data](https://www.jetbrains.com/help/idea/2016.1/inline-debugging.html), but at this point, last command results or inline type the popup-tip seems better.

![eval_inline](https://cloud.githubusercontent.com/assets/722866/15991970/354a8808-30b9-11e6-8273-2e1bb3078351.png)
![eval_popup](https://cloud.githubusercontent.com/assets/722866/15991973/39f0163e-30b9-11e6-8125-c696127dd9d2.png)

**Comment by kozikow** [comment]
Hmm I just noticed you mean "persistent type" in the ticket. Showing the type and "leaving it there" is indeed useful. popup-tip does not support "leave the popup hanging around". It appears that pulling the overlay from cider is indeed useful.

**Comment by fommil** [comment]
Ideally we'd like the user to be able to choose between minibuffer, popup or persistent.

**Comment by kozikow** [comment]
I am now locally running version of overlays without the full cider dependency.

1. Copy cider-overlays from https://github.com/clojure-emacs/cider/blob/master//cider-overlays.el with slight modifications works without cider dependency.
2. Remove the call to =(clojure-backward-logical-sexp 1)= (https://github.com/clojure-emacs/clojure-mode/blob/master/clojure-mode.el#L1628).
   It only is used if the code we are calling the overlay from is a lisp code (so it is not useful for scala/java).
3. Use -when-let from dash rather than custom cider version.

There are a few more things that make the assumptions about lisp-ness of the code and pull dependencies from libraries like clojure-mode. They can be removed, but it makes it unlikely that it is possible to easily create a "common" version between ensime and cider.

**Comment by fommil** [comment]
When I was telling you about the server providing block information, it is exactly backword-logical-sexp that it can provide. It would be good to try to make this a shared library all the same. It is very idiomaticly Emacs to think about all programming languages - including org-mode - in terms of s-expressions. I recommend the Mastering Emacs book for more details.

**Comment by kozikow** [comment]
There is already some form of "try to find last sexp" provided by the (ensime-inf-eval-definition), but it seems it's mostly based on some regexps on emacs side.

**Comment by fommil** [comment]
Ignore that, we'll create a call on the server. It hasn't been written yet. It hasn't a chance in hell of working without that server call.

**Comment by fommil** [comment]
(showing the type at point doesn't need the server call for positional information, but the eval at point sure does)

**Comment by fommil** [comment]
@kozikow btw on your way to getting something working, how about making it work for emacs-lisp `C-x C-e`? That shouldn't involve any external dependencies and would be really useful.

**Comment by kozikow** [comment]
I have it working locally for elisp (and I am using it all the time now). It's as described in http://endlessparentheses.com/eval-result-overlays-in-emacs-lisp.html?source=rss . With cider dependency above code can be just pasted to elisp config.

It could be a good idea to package it as a library that can be just installed from melpa (after removing clojure and cider dependencies), use it as a dependency in ensime and provide a minor-mode for overlays in elisp.

**Comment by fommil** [comment]
awesome! I am going to try this for elisp.

**Comment by lxol** [comment]
@fommil can you review #515  .  I added a new option to displays type and errors at point inline with `C-u C-u` prefix, the same way we eval the expressions.

**Comment by fommil** [comment]
Awesome! Ping me if I forget, I might not be at a computer this weekend.

**Comment by fommil** [comment]
I think this might need a `defcustom` ! :smile:
