### ISSUE TITLE
Overzealous implicit underlining in `emacs -nw`

### ISSUE THREAD

**Issue by fosskers** [ensime/ensime-emacs#440]
In `emacs -nw`, or `emacsclient -nw`, or just `emacs` from the `emacs-nox` package.

### Steps to reproduce

1. `git clone https://github.com/fosskers/geotrellis-admin.git`
2. Move into the dir, and `git checkout scalajs-client`
3. `sbt ensimeConfig`
4. Open emacs in the terminal via `emacs -nw`
5. Navigate to `client/src/main/scala/geotrellis/admin/client/components/sidebar/InfoPanel.scala`
6. Activate `ensime`
7. View the implicit highlighting in `InfoPanel.Backend.render`

### Expected behaviour

This block uses a lot (~40?) implicit conversions, and it should all be highlighted/underlined. Said underlining should only appear until the line break.

### Actual behaviour

Underlining covers the entire screen from left to right.
![2016-05-17-160133_958x1043_scrot](https://cloud.githubusercontent.com/assets/229679/15361914/56311082-1cc8-11e6-8109-ff9fc9b60f97.png)

### Questions

1. Is this ensime?
2. Is this emacs?
3. Is this ncurses?

**Comment by fommil** [comment]
I think this is technically correct. The whole block is implicitly converted, so needs an underline.

We might want to:

1. not underline multi-line blocks
2. not underline trailing whitespace

would you like to have a look at implementing either fix?

**Comment by fosskers** [comment]
You're right that the entire block needs an underline, I'm completely fine with that. Note however the display difference with normal emacs:

![2016-05-18-093457_958x1043_scrot](https://cloud.githubusercontent.com/assets/229679/15367019/f00a0b7e-1cdb-11e6-8edd-c1970a212b61.png)

There is no trailing whitespace in this file, so I'd say the `emacs-nox` version of the display is indeed a bug (by someone).

**Comment by fommil** [comment]
oh right, I see. Hmm, yeah, probably not an ensime bug.

**Comment by fommil** [comment]
to try to diagnose the problem, I recommend investigating how ensime applies the semantic highlighting and trying to reproduce that behaviour in isolation in the terminal. Does that make sense? We use something called overlays.

**Comment by fosskers** [comment]
Could you clarify what you mean by "in isolation"?

**Comment by fommil** [comment]
in an emacs lisp file, without ensime, just apply some overlays onto a text region and see what happens. You might need to do it with visual inspection.

My guess is that the terminal doesn't really see trailing space as a dead area.

**Comment by fosskers** [comment]
You were right, this is strictly an emacs issue.

![2016-05-18-103053_958x1043_scrot](https://cloud.githubusercontent.com/assets/229679/15368631/a90c5ef4-1ce3-11e6-9c76-7d7c1a2d6d35.png)

**Comment by fosskers** [comment]
I've submitted a bug report to the emacs bug list and linked them to this github issue.

**Comment by fosskers** [comment]
This occurs with `emacs -Q` as well, meaning it isn't something about my `.emacs`.

**Comment by fommil** [comment]
I've often wondered if overlays are the right way to do things. Maybe we should be using faces.

**Comment by fosskers** [comment]
Thanks for your help. Hopefully some emacs people chime in. I'll keep commenting here to update progress if they stick to email.

**Comment by fommil** [comment]
cool, thanks!

**Comment by fosskers** [comment]
There's a rather long email chain occuring now. One maintainer is claiming that the GUI not extending the face to the end of the screen is the real bug, and that the multiline underlining behaviour here for GUI emacs is a coincidence. They're considering "fixing" it.

**Comment by fommil** [comment]
LOL ah, bet you're glad you emailed them. When kind of popcorn did you get?

**Comment by fosskers** [comment]
U-turn, there's now talk of:

```
(defcustom face-extend-to-window-edge nil
  "Non-nil means extend face of last character on line to window edge.
This variable specifies whether the space following the last
character on a line is decorated using properties of that
character.  nil means do not extend any properties of that
character.  t means extend all properties of that character.

A property list means to determine the value of any such property
from that list. If a property is not on that list, that property
is not extended.  The special value 'inherit' means to inherit
the value for that property from the last character on the line.
A function specifies the function to return the value of that
property.  Any other value means to extend that as value for that
property.")
```

**Comment by fosskers** [comment]
Update from the future: As far as I'm aware, the emacs bug was never fixed.

**Comment by fommil** [comment]
Maybe we should underline the method, not the instance. There is a new ticket on the server discussing similar.
