### ISSUE TITLE
type-at-point short / full name choices

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#445]
it would be good if there was a way to choose the short or full name when doing a type-at-point. Proposal: `C-c C-v t` is short name and `C-c C-v T` (capital) is full name. There is already a prefix arg to this, so it needs to be preserved.

@noelmarkham fancy picking this up? Should be really simple and will make the new support for all your fancy symbol types all the better.

**Comment by diego-alvarez-hs** [comment]
is it something like this: https://github.com/syl20bnr/spacemacs/blob/develop/layers/+lang/scala/funcs.el#L105 ?

**Comment by fommil** [comment]
that's not really what I had in mind, nor do I understand why that function even needs to exist.

**Comment by fommil** [comment]
By that, I mean I don't understand why we would want a dedicated function to add to the kill ring when the universal argument does that already. Or I'm thinking here is a copy of our type-at-point that uses the short note as per the payload (no processing required), and a bit of defaults. Should be trivial.

**Comment by d1egoaz** [comment]
Yeah sure! (Lisp beginner)


So let me see if I understand this correctly.

- When you say "copy of our type-at-point" is a copy of the whole `ensime-type-a-point` function?

And when you say "short name as per the payload" is to change:
` (fullname (ensime-type-full-name-with-args type)))` with `(shortname (ensime-type-full-name-with-args type)))
`
^ that would be the same as this 😆  https://github.com/syl20bnr/spacemacs/blob/ac104d273917e224638606ca579f26a4602a5f98/layers/%2Blang/scala/funcs.el#L105-L111

- Or are you saying to modify the `ensime-type-a-point` function to somehow it receives a parameter an depending on parameter value it'll use `fullname` or `shortname`?

**Comment by fommil** [comment]
Yeah, your first two points are correct but the spacemacs function it not doing what our function is doing. Look at our type signature, we're using the universal argument to decide whether to add to the kill ring. By copy I mean refactor into a common function :-)

**Comment by fommil** [comment]
Which is your third point :-)

Btw have you had the chance to read the contributing guide? It's got some good resources for learning lisp.

**Comment by fommil** [comment]
And also the Emacs Hacks page has some advice for sending up Emacs for hacking on lisp.
