### ISSUE TITLE
constructor definition not allowed here

### ISSUE THREAD

**Issue by VyacheslavMik** [ensime/ensime-emacs#450]
Hello. When I wrote this in emacs ensime:

```scala
object ParseExpr extends Arith {
  def exec(args: Array[String]) {
    println("input: "+ args(0))
    println(parseAll(expr, args(0)))
  }
}

object Program {
  def main(args: Array[String]) {
    ParseExpr.exec(args)
  }
}
```
I got the following error `constructor definition not allowed here`, but `sbt` compile this code without problem.

Source code for Arith:
```scala
import scala.util.parsing.combinator._

class Arith extends JavaTokenParsers {
  def expr: Parser[Any] = term~rep("+"~term | "-"~term)
  def term: Parser[Any] = factor~rep("*"~factor | "/"~factor)
  def factor: Parser[Any] = floatingPointNumber | "("~expr~")"
}
```

**Comment by fommil** [comment]
http://ensime.org

**Comment by fommil** [comment]
Can you please give a reproduction in the form of a unit or integration test? A github repository with exact instructions for somebody to follow, like a script, is also a good starting point. We are more than happy to help you turn it into an automated test, and discuss ideas on how to fix it. Read the http://ensime.org/contributing guide for more information.

We close tickets that look like a known issue or don't provide the details requested by the template, but it's not the end of the conversation and we will open it up again when there is enough information to go on. This is to improve the quality of our issue tracker and to make it easier for contributors to help.

We will reopen this ticket if you can confirm it is a bug by giving us a **detailed** reproduction. Please read the http://ensime.org/getting_help guide to understand the steps that are required prior to submitting a bug report.

**Comment by VyacheslavMik** [comment]
Sorry, @fommil.:( After updating ensime in emacs everything works. Next time I'll be carefully and try troubleshooting before create an issue.
Thanks!
P.S. Is there any way to remove this issue?

**Comment by fommil** [comment]
Glad you eventually found the documentation :wink:

No need to delete anything, closed tickets are not clutter.
