### ISSUE TITLE
Symbol's value as variable is void: to-insert

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#458]
I am seeing some failures in `ensime--annotate-completions` with completion payloads that looks a little bit like #454 (which is missing a reproduction).

I was able to get the problem by typing

``` elisp
(ensime-plist-bind
      (type-info is-callable to-insert name)
      '(:type-info (:arrow-type t :name "(String) => PathFinder" :full-name "(java.lang.String) => sbt.PathFinder" :result-type (:arrow-type nil :name "PathFinder" :decl-as class :full-name "sbt.PathFinder") :param-sections ((:params (("literal" (:arrow-type nil :name "String" :decl-as class :full-name "java.lang.String")))))) :name "/" :type-sig (((("literal" "java.lang.String"))) "sbt.PathFinder" nil) :is-callable t :relevance 80)
      (propertize name
                  'symbol-name name
                  'type-info type-info
                  'is-callable is-callable
                  'to-insert to-insert))
```

but then it went away! I'm guessing it's got something to do with emacs symbol interning or file opening order.

**Comment by fommil** [comment]
or maybe the `cl-destructuring-bind` is buggy and we should use use `-let` instead.

**Comment by fommil** [comment]
the equivalent call from 454 would be with this payload:

```elisp
 ((:name "match" :type-sig (nil "" nil) :relevance 100) (:name "map" :type-sig (((("f" "scala.Function1[scala.Any, scala.concurrent.S]")) (("executor" "scala.concurrent.ExecutionContext"))) "scala.concurrent.Future[scala.concurrent.S]" t) :is-callable t :relevance 90) (:name "mapTo" :type-sig (((("tag" "scala.reflect.ClassTag[scala.concurrent.S]"))) "scala.concurrent.Future[scala.concurrent.S]" t) :is-callable t :relevance 90)))
```

**Comment by timcharper** [comment]
I upgraded from `20160521.1546` to `20160602.1103` via ELPA and this broke similarly. Then, I switched back and it worked again.

Then, I switched to a cloned version of `ensime-emacs`, caf2e8b7a57a604c1a2a4d999a1e963837a75bd3, and that also works, even though this appears to be the same code as contained by `20160602.1103`.

```
Debugger entered--Lisp error: (void-variable to-insert)
  #[(completion) "\304\303	\"\n\305	\303\300%#\207" [to-insert name completion type-info ensime-plist-bind propertize] 9]((:type-info (:arrow-type t :name "() => Unit" :full-name "() => scala.Unit" :result-type (:arrow-type nil :name "Unit" :decl-as class :full-name "scala.Unit") :param-sections (nil)) :name "gc" :type-sig ((nil) "scala.Unit" nil) :is-callable t :relevance 90))
  mapcar(#[(completion) "\304\303	\"\n\305	\303\300%#\207" [to-insert name completion type-info ensime-plist-bind propertize] 9] ((:type-info (:arrow-type t :name "() => Unit" :full-name "() => scala.Unit" :result-type (:arrow-type nil :name "Unit" :decl-as class :full-name "scala.Unit") :param-sections (nil)) :name "gc" :type-sig ((nil) "scala.Unit" nil) :is-callable t :relevance 90) (:type-info (:arrow-type nil :name "InputStream" :decl-as class :full-name "java.io.InputStream") :name "in" :type-sig (nil "java.io.InputStream" nil) :relevance 90) (:type-info (:arrow-type nil :name "PrintStream" :decl-as class :full-name "java.io.PrintStream") :name "err" :type-sig (nil "java.io.PrintStream" nil) :relevance 90) (:type-info (:arrow-type nil :name "PrintStream" :decl-as class :full-name "java.io.PrintStream") :name "out" 
```

I switched to the latest HEAD

**Comment by fommil** [comment]
Thanks Tim. I think a lot of that experimenting is a false lead, this is transient and related to the plist macro.

**Comment by fommil** [comment]
@timcharper don't use the old one, it's incompatible with the protocol changes I made recently. Completion will start to be weird.

**Comment by michaelrkytch** [comment]
I'm having a similar problem.  Here's a [backtrace](https://gist.github.com/michaelrkytch/3102662b6b03c9e8ba0b0f438694dfdb) if it's helpful.

**Comment by randbw** [comment]
Also having this issue. Here is my [backtrace](https://gist.github.com/randbw/71ef5b8d9150934d1170899782a613a1). Hopefully it's helpful because now you have two.

Happy to help further if I can :)

**Comment by fommil** [comment]
@randbw how's your lisp? I think this might be an emacs lisp bug, so they might appreciate if we can minimise it... otherwise the workaround would be to rewrite using the `ensime-plist-merge` to use `-let` (trivial, I just haven't had time).

**Comment by randbw** [comment]
@fommil I'm very much a beginner in lisp. I'll take a look at this over the weekend though and see if I can get anywhere.

**Comment by randbw** [comment]
Hi again @fommil. Sorry for the delay in getting back to you. I've spent some time going through the code and I believe it was a bit ambitious of me to offer to help this soon... I'll keep learning and hopefully help on a future issue :)

**Comment by fommil** [comment]
everytime I get an error, emacs is truncating parts of the input parameters with `...`

It would be good if there was a way to get a **full** backtrace, then we'd stand a chance of reproducing this.

**Comment by ANorwell** [comment]
I get this very frequently when entering text on 20160626.658 from melpa. I see this might have been addressed in https://github.com/jmpage/ensime-emacs/commit/fd178b104f822f737da3fbb3ff95ccce75c99f43. Is that part of 20160626.658? It's not obvious to me that the stacktrace encountered below (similar to those posted above but also with some complaints about RPC?) is addressed by that commit.

[backtrace](https://gist.github.com/ANorwell/6c0ac24f325a91783933a43e3e21e7ce)

**Comment by fommil** [comment]
We have to idea what the problem is. Ih's gote away for me. I suspect company-mode is sending the wrong input

**Comment by ANorwell** [comment]
I don't get this on the current head of master, 4cc835d.

**Comment by fommil** [comment]
I've not seen this one recently. I'm wondering if it was a transient in company-mode or some load ordering thing. Let's leave it open for a while but when we next cull the tracker and this is stale, we can close it.

**Comment by archena** [comment]
I encountered this issue but in my case, it was probably* bad dependencies. I had installed ensime from the package manager, but I already had most of its dependencies, and some were quite stale.

In the end I did this:

```
Quit emacs
mv ~/.emacs.d/{elpa,OLD_elpa}
mkdir ~/.emacs.d/elpa
Start emacs
M-x package-install ensime
```

Following this the packages and versions installed were:

```
company-20171122.716
dash-20171028.854
ensime-20171027.1433
popup-20160709.729
s-20171102.227
sbt-mode-20171111.1558
scala-mode-20170802.432
yasnippet-20170923.1646
```

I also had an old `scala-mode2` loaded from `~/.emacs`, so I got rid of that too. Obviously, my problems came from having a bad setup; for anybody in the same situation it's an easy fix.

* I also did `rm -rf ~/.emacs.d/ensime` so I guess that might have contributed

**Comment by yyadavalli** [comment]
Looks like it is a transient issue, probably due to bad dependencies. Closing the issue as we did not encounter it for over a year.
