### ISSUE TITLE
confused about getting started

### ISSUE THREAD

**Issue by jimka2001** [ensime/ensime-emacs#465]
I'm not sure what the use model is.
I have not yet written my first scala program.  I'm getting ready to start learning scala.
However, I'm a 30 year emacs veteran.  I'd rather use emacs, than trying to install
and learn eclipse or intelliJ.
I've tried to read the several meta-circular getting-started/trouble-shooting guides and I'm
going around in circles.

When I try to start ensime with M-x ensime, it asks me for the ENSIME Project file.  What is that?
Does this assume I already have a compiled scala project?  Do I need to abandon emacs/ensime
and go use IntelliJ to start a project, then come back and convert it to use emacs?

If I simply press RETURN at the ENSIME Project File : ~/ prompt,
I get an emacs stack trace asking me to check that set is in my path.  
I'm on MACOS, and I've added "/usr/local/bin" to my exec-path, and verified that the variable
has the correct value, and have verified that /usr/local/bin/sbt exists and is executable.

If someone can give me a push in the right direction, that would be great.
Thanks
Jim

**Comment by fommil** [comment]
There shouldn't be any circular dependencies in the docs. Which ones do you mean?

Start at http://ensime.org/getting_started and work your way through the Emacs and (presumably) sbt tracts. It sounds like you skipped the build tool side of things (which is listed in both the general Getting Started page and the Emacs-specific Troubleshooting guide)

It sounds like you're confused by the role of the build tool in Scala. I recommend perhaps reading some sbt documentation first.

**Comment by fommil** [comment]
btw, your situation is something we'd like to cater for but nobody has stepped up to write https://github.com/ensime/ensime.github.io/issues/109 yet

**Comment by fommil** [comment]
(please use the gitter room for these kinds of "help me" questions... you'll find more people on there)
