### ISSUE TITLE
Add autoload cookies to ensime-mode (and any other entry points!)

### ISSUE THREAD

**Issue by phillord** [ensime/ensime-emacs#479]
### Steps to reproduce

1.  Install ensime use package.el
2. M-x ensime-mode (no match...)

### Expected behaviour

Ensime-mode should work

### Actual behaviour

Ensime-mode doesn't

Adding auto-load cookies would make this just work. You could probably change your ensime load form to something like this....

    (use-package ensime
      :after scala-mode
      :config (add-hook 'scala-mode 'ensime-mode))

**Comment by fommil** [comment]
we have installation instructions on http://ensime.org if you have suggestions to improve the process a PR would be better than a bug report.
