### ISSUE TITLE
Wrong starting ensime

### ISSUE THREAD

**Issue by joinvim** [ensime/ensime-emacs#490]
During launch of Ensime appear error. But after loading work fine (probably).

![a1](https://cloud.githubusercontent.com/assets/19364650/16388053/1559098c-3ca0-11e6-9f5c-f11c43c3477b.jpg)

Messages buffer:
![a2](https://cloud.githubusercontent.com/assets/19364650/16388026/f36fccca-3c9f-11e6-87b5-1256a36cdd3e.jpg)

Environment:
ensime-20160626.658
emacs 24.5.1

Emacs config for scala:

```lisp
(setq-default ensime-startup-dirname (expand-file-name ".ensime" aspirin-home-dir)
              ensime-auto-generate-config t)
(diminish 'ensime-mode)
(add-hook 'scala-mode-hook
  (lambda ()
    (setq-local mode-name "SCALA")
    (scala-mode:goto-start-of-code))
```

Project:
Main.scala
```scala
package com.empty
import scalaz._

object Main extends App {
  val s = State[Int, String](i => (i + 1, "Scala"))
  val language = s.eval(1)
  println(s"I'm empty $language project.")
}
```

build.sbt
```scala
name := "Scala/SBT project"
version := "0.1.0"
scalaVersion := "2.11.8"
libraryDependencies ++= {
  Seq("junit" % "junit" % "4.12")
  Seq("org.scalaz" %% "scalaz-core" % "7.2.4")
}
```

step by step instructions:
1. sbt configEmacs
2. M-x ensime

gist on ensim file:
https://gist.github.com/joinvim/79f4ddcab3e210a89bab685440c333ca

**Comment by fommil** [comment]
Sorry i have no idea what the problem is

**Comment by joinvim** [comment]
Problem disappeared after delete line below:
```lisp
(add-hook 'prog-mode-hook #'nlinum-mode)
```
So the command `ensim' have conflict with nlinum-mode.

**Comment by fommil** [comment]
:+1: cool thanks for letting us know
