### ISSUE TITLE
Wrong implicit underline

### ISSUE THREAD

**Issue by joinvim** [ensime/ensime-emacs#491]
![vvvv](https://cloud.githubusercontent.com/assets/19364650/16388375/92c8758c-3ca1-11e6-8c29-02ae6572bb7e.jpg)
Used theme is Zenburn, but after disable it, behaviour not changed.
Environment and project as: https://github.com/ensime/ensime-emacs/issues/490

**Comment by fommil** [comment]
This is expected. It means there are implicit parameters. If you'd can think of a better way to history this, please discuss and send a PR.
