### ISSUE TITLE
Don't load scala mode

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#503]
To get the tests to pass I added loading scala mode to the ensime hook but that is nasty, it should do is own autoloading. Think about Java files.

May require an update to scala-mode (and a stable release)

@phillord any thoughts?

**Comment by phillord** [comment]
Not 100% sure what the issue is. IIUC, if ENSIME is only really useful when combined with scala-mode (and if it directly references it, then it is), when not just `require' scala-mode?

**Comment by fommil** [comment]
ENSIME also works with `java-mode` :wink: 

I think the correct process should be for ensime mode to load via a `scala-mode-hook` or `java-mode-hook`, but I had to add this line recently to get the tests to pass https://github.com/ensime/ensime-emacs/commit/08c93aad53809eebf14fc8da5f9362f423d13d46#diff-860ef808538ce47bcf6807f038e00476R107 and that's nasty

**Comment by phillord** [comment]
Add  `(require 'scala-mode)` to the tests file instead?

**Comment by fommil** [comment]
I don't think that is the problem. ENSIME should be transitively loading `scala-mode` and `scala-mode` should be automatically enabling itself for `*.scala` files. So something is going wrong with autoloading by the looks of it.

**Comment by phillord** [comment]
When you say "to get the tests to work" how are you running them? Is the autoloads file being loaded? This will happen automatically when you install ensime as a package, but not if you are running from a git clone.

I'm guessing here...

**Comment by fommil** [comment]
The thing is that I shouldn't need to do anything special to get the tests to work, so if the tests are broken then that means our distribution is broken. I think this just needs a good sit down and go through the autoloads of scala-mode and ensime and make sure that everything is being loaded as expected (e.g. even the ascription of `.scala` files to `scala-mode`).

**Comment by phillord** [comment]
Sorry for slow reply.

If the distribution is as an Emacs package, then this is not necessarily
true. The tests might fail while the distribution works iff the latter
is running as a package, given that the package installation generates
the autoloads file, and the package initialization loads it. It's a
an occasional problem with raw source.

If you are using define-minor-mode, or equivalent, you can normally
autoload these forms quite safely which should take care of the
auto-mode-alist issue.
