### ISSUE TITLE
ensime-sbt-switch crashes Ensime process

### ISSUE THREAD

**Issue by microamp** [ensime/ensime-emacs#510]
Original issue posted: https://github.com/ensime/emacs-sbt-mode/issues/75

---

Running `ensime-sbt-switch` crashes the running Ensime process with this error:
```emacs-lisp
Debugger entered--Lisp error: (wrong-type-argument markerp nil)
  comint-output-filter(#<process *sbt*<~/src/my-scala-project/>> "[info] Loading global plugins from /Users/microamp/.sbt/0.13/plugins\n")
```

I'm running
* Emacs 25.1.1 on OS X
* Scala 2.11.8
* sbt 0.13
* Emacs packages
  * `ensime-1.0.0` (from stable.melpa.org)
  * `scala-mode-20160813.304` (Also tried the stable version)
  * `sbt-mode-20160816.1353` (Also tried the stable version)
* My `.ensime` file for the project, https://gist.github.com/microamp/729a9b7bf6f1c25b5529a283cb60d636

I wonder if it's a bug elsewhere. Please let me know if I need to provide more info. Thanks.

---

### Steps to reproduce

1. Open a Scala file, this will trigger an Ensime process
2. Once the Ensime process is running, run `ensime-sbt-switch`
3. This creates a new sbt buffer that says "Running sbt", then subsequently kills the Ensime process. There is an error message "Server connection closed unexpectedly: connection broken by remote peer" in the message buffer. With the debug on, you get the error message mentioned above, `(wrong-type-argument markerp nil)`. I can see that the sbt process is still running although it doesn't proceed after the first line, "Running sbt".

**Comment by microamp** [comment]
Also, I'm running Spacemacs. I had to switch to stable.melpa.org (from melpa.org) manually to install the version 1.0 if that helps.

**Comment by fommil** [comment]
Is there anything we can do to help you debug and fix this? Have you read the contributing guide to get set up the look into this?

**Comment by microamp** [comment]
I tried the troubleshooting guide but the problem still remains. I created the ticket in case anyone had seen it before. If not, I'll try reinstalling everything again and see if that helps.

**Comment by fommil** [comment]
the contributing guide http://ensime.github.io/editors/emacs/contributing/

to help you diagnose and fix this. It's unlikely that anybody will want to pick this up as a ticket, so we want to empower you to fix it yourself.

**Comment by microamp** [comment]
I knew I was doing something stupid. I had accidentally added `scala-mode` to `sbt-mode-hook`. I suppose I wanted syntax highlight and autocompletion in the sbt buffer without much thought into it. Closing the ticket now.

**Comment by fommil** [comment]
:-1:

**Comment by fommil** [comment]
Damnit autocomplete... Why would you do that?!?!?


Obviously, :+1:
