### ISSUE TITLE
ensime-startup.el empty line before `scalaBinaryVersion := \"_scala_binary_version_\"`

### ISSUE THREAD

**Issue by bowerth** [ensime/ensime-emacs#511]
I am bluntly ignoring the suggested template to file a bug, I suppose this is quite straight-forward and simple - does anyone else experience an issue with `scalaVersion` and `scalaBinaryVersion` having no empty line between them in [ensime-startup.el](https://github.com/ensime/ensime-emacs/blob/c93111dad5b048f21290f0590ff3af0930e3a1df/ensime-startup.el#L116) ?

**Comment by fommil** [comment]
use the gitter channel for this sort of question.

**Comment by fommil** [comment]
and, no, to answer your question. Otherwise nobody would be able to use ensime.
