### ISSUE TITLE
import-at-point transformation (from _._ to _.{_, _}) adds extra i

### ISSUE THREAD

**Issue by Trevoke** [ensime/ensime-emacs#523]
### Steps to reproduce
1. Have a file with `import java.util.GregorianCalendar`
2. Write `Calendar`
3. With `Calendar` on point, call ensime's function to import type at point
### Expected behaviour

Should display `import java.util.{ Calendar, GregorianCalendar }`
### Actual behaviour

Displays `iimport java.util.{Calendar, GregorianCalendar }`

**Comment by fommil** [comment]
can you minimise this as a starting file or project? I can't reproduce.

**Comment by Trevoke** [comment]
=> https://github.com/Trevoke/for-ensime-debugging-purposes

**Comment by fommil** [comment]
+1 no package definition, we must be assuming there is one.
