### ISSUE TITLE
void-variable ensime-inf-overlay-marker in sbt buffer

### ISSUE THREAD

**Issue by greenrd** [ensime/ensime-emacs#526]
### Steps to reproduce

With unstable version:

1. `M-x ensime`
2. `C-c C-b s`
3. Enable Enter Debugger on Error in emacs options
4. press Enter

### Expected behaviour
No error

### Actual behaviour
Error:
```
Debugger entered--Lisp error: (void-variable ensime-inf-overlay-marker)
  ensime-inf-postoutput-filter("> ")
  run-hook-with-args(ensime-inf-postoutput-filter "> ")
  comint-output-filter(#<process *sbt*<~/git/drivetribe/backend/>> "> ")
  accept-process-output(#<process *sbt*<~/git/drivetribe/backend/>>)
  comint-send-input()
  funcall-interactively(comint-send-input)
  call-interactively(comint-send-input nil nil)
  command-execute(comint-send-input)
```

**Comment by greenrd** [comment]
@fommil At what point did you need to open a .scala file?

**Comment by fommil** [comment]
After starting ensime. The ensime commands are only available for me in ensime-mode. I guess doing the sbt command with M-x could probably trigger it to?

My guess is that there is a hook being added somewhere that has no business being there. Or this variable is referenced without doing a require.

**Comment by greenrd** [comment]
I think I do understand the problem. This bug was introduced by 01f33e9f955c2caa00be61a98005d7f9e3cee632 which added the ability to use scala REPL buffers to evaluate code and display the results inline. However, that commit touched `ensime-inf-postoutput-filter`, which is _also_ used by `ensime-sbt`. While ensime-inf correctly creates the new `ensime-inf-overlay-marker` variable in ensime-inf buffers, ensime-sbt didn't know about that new variable and didn't create it - until my commit.

**Comment by fommil** [comment]
Can we fix this with require statements instead? This will erase whatever it was before.

**Comment by greenrd** [comment]
The thing is, `ensime-inf-overlay-marker` isn't set in `ensime-sbt` mode. It's only set in `ensime-inf` mode.

**Comment by fommil** [comment]
but if `ensime-inf` is loaded first, or the user sets it, when this hack runs, it will erase the variable to `nil`, which defeats its point in the first place. A much preferable solution would be to come up with a sane dependency / `require` chain, such that files are not depending on code that could not have been initialised correctly.

**Comment by greenrd** [comment]
It seems like this variable is being manipulated as if it was a buffer-local variable, but it isn't actually buffer-local. How odd. I'll take a closer look tonight.
