### ISSUE TITLE
Use ensime-sbt's ensimeScalariformTask for ensime-format-source

### ISSUE THREAD

**Issue by yyadavalli** [ensime/ensime-emacs#531]
https://github.com/ensime/ensime-sbt/pull/230

**Comment by fommil** [comment]
FYI #530

**Comment by fommil** [comment]
btw, I'm trialing this (I added a `save-buffer`)

```elisp
(defun ensime-sbt-do-scalariform-only ()
  (interactive)
  (save-buffer)
  (let ((subproject (ensime-sbt-find-subproject buffer-file-name)))
    (if subproject
        (sbt-command (concat subproject "/ensimeScalariformOnly " buffer-file-name))
      (sbt-command (concat "ensimeScalariformOnly " buffer-file-name)))))
```

the concept of running a command for a specific subproject seems like something we could factor out.

**Comment by fommil** [comment]
sounds good!

**Comment by fommil** [comment]
we'll give the other editors a heads up before removing it from the server, and then remove it anyway MUAHAHAHAHAHA!

**Comment by fommil** [comment]
sorry, did I say that out loud?

**Comment by yyadavalli** [comment]
So, should I remove the command or just call `ensime-sbt-do-scalariform-only`?
I'd say remove it.

**Comment by fommil** [comment]
remove! I was talking about server side :-) sorry I broke the functions you're calling with my latest PR. Should be a trivial update for you though.

**Comment by yyadavalli** [comment]
Sure, I believe no other editors are using those messages. If we were to remove `formattingPreferences` from `EnsimeConfig` that would have more impact.
