### ISSUE TITLE
notes performance problem on windows

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#543]
this performance trace says it all really

```
- ensime-net-filter                                               417  54%
 - ensime-process-available-input                                 417  54%
  - ensime-dispatch-event                                         415  54%
   - ensime-add-notes                                             400  52%
    - ensime-make-note-overlays                                   395  51%
     - ensime-make-overlay-at                                     394  51%
      - find-buffer-visiting                                      379  49%
       + file-truename                                            357  46%
       + file-attributes                                            1   0%

```

**Comment by aemoncannon** [comment]
Ouch. truename has to hit the disk to resolve symlinks

**Comment by fommil** [comment]
ouchies. Maybe we could cache it. I do that in my sbt build (which is horrific, btw... I saved 200MB of heap just by renaming the folder that my project is in to have less characters)

**Comment by aemoncannon** [comment]
Could probably come up with something better than using find-buffer-visiting
to map source file to buffer..

**Comment by aemoncannon** [comment]
Without looking at the code, I wonder if we just need to group by source
file so we only hit disk once per file

**Comment by fommil** [comment]
yeah, local buffer variable? I've been thinking recently that we should probably regroup regarding our config/server/other lookup #538 but that's a bigger refactor and I should probably save it for rewriting teh protocol. Which is still on my todo list! I swear it is.
