### ISSUE TITLE
Scala :quit every time I run M-x ensime-inf-eval-region.

### ISSUE THREAD

**Issue by kostafey** [ensime/ensime-emacs#552]
`ensime-20161110.1316`
```bash
scala -version
Scala code runner version 2.11.8 -- Copyright 2002-2016, LAMP/EPFL
```
```bash
java -version
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
```

Steps to reproduce for example project [hello-scala](https://github.com/kostafey/hello-scala)

1. <kbd>M-x find-file</kbd> `hw.scala`
2. <kbd>M-x ensime</kbd>
3. <kbd>C-c C-v z</kbd>
4. Select (mark) `println("Hi!")`, <kbd>M-x ensime-inf-eval-region</kbd>

Result:
```
Welcome to Scala 2.11.8 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_101).
Type in expressions for evaluation. Or try :help.

scala> // Entering paste mode (ctrl-D to finish)


// Exiting paste mode, now interpreting.

Hi!

scala> :quit
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0

Process *Scala REPL* finished
```

Expected result:

I would not like to quit scala process.

**Comment by fommil** [comment]
Would you like to have a look at fixing this? Start with a test, there is a contributor guide to get you started. Nobody else is looking at this.

**Comment by kostafey** [comment]
@fommil Looks like fixed in the developer version of Ensime. Ok, I'll try to become involved in the future.

**Comment by skp33** [comment]
Can you please share the patch detail?

**Comment by kostafey** [comment]
(defun my-ensime-inf-eval-region (start end)
  "Send current region to Scala interpreter. If no region is active send current line to Scala interpreter."
  (interactive "r")
  (ensime-inf-assert-running)
  (let* ((start (if (use-region-p) start (line-beginning-position)))
         (end   (if (use-region-p) end (line-end-position)))
         (reg (buffer-substring-no-properties start end))
         (buffer (buffer-name)))
    (setq ensime-inf-overlay-marker (copy-marker end))
    (with-current-buffer ensime-inf-buffer-name
      (goto-char (point-max))
      (if (eq system-type 'windows-nt)
          ;; Windows
          (progn
            (comint-send-string nil s)
            (let ((comint-input-sender 'ignore)
                  (comint-input-filter-functions nil))
              (comint-send-input t t))
            (comint-send-input)
            (goto-char (process-mark (get-buffer-process (current-buffer))))
            (line-move -1)
            (right-char (length "scala> "))
            (when (and (>= (point-max) (+ (point) 3))
                       (not (equal
                             (buffer-substring (point) (+ (point) 3))
                             "res")))
              (kill-line 1))
            (comint-kill-input))
        ;; Linux
        (progn
          (comint-send-string nil ":paste\n")
          (comint-send-string nil s)
          (comint-send-string nil "\n")
          (sit-for 1)
          (comint-send-eof))))))

**Comment by kostafey** [comment]
(defun my-ensime-inf-eval-region (start end)
  "Send current region to Scala interpreter. If no region is active send current line to Scala interpreter."
  (interactive "r")
  (ensime-inf-assert-running)
  (let* ((start (if (use-region-p) start (line-beginning-position)))
         (end   (if (use-region-p) end (line-end-position)))
         (reg (buffer-substring-no-properties start end))
         (buffer (buffer-name)))
    (setq ensime-inf-overlay-marker (copy-marker end))
    (with-current-buffer ensime-inf-buffer-name
      (goto-char (point-max))
      (if (eq system-type 'windows-nt)
          ;; Windows
          (progn
            (comint-send-string nil s)
            (let ((comint-input-sender 'ignore)
                  (comint-input-filter-functions nil))
              (comint-send-input t t))
            (comint-send-input)
            (goto-char (process-mark (get-buffer-process (current-buffer))))
            (line-move -1)
            (right-char (length "scala> "))
            (when (and (>= (point-max) (+ (point) 3))
                       (not (equal
                             (buffer-substring (point) (+ (point) 3))
                             "res")))
              (kill-line 1))
            (comint-kill-input))
        ;; Linux
        (progn
          (comint-send-string nil ":paste\n")
          (comint-send-string nil s)
          (comint-send-string nil "\n")
          (sit-for 1)
          (comint-send-eof))))))

**Comment by kostafey** [comment]
@skp33 the problem is only related to Windows. It's possible to fix it with ad-hoc snippet like this:

```emacs-lisp
(defun my-ensime-inf-eval-region (start end)
  "Send current region to Scala interpreter. If no region is active send current line to Scala interpreter."
  (interactive "r")
  (ensime-inf-assert-running)
  (let* ((start (if (use-region-p) start (line-beginning-position)))
         (end   (if (use-region-p) end (line-end-position)))
         (reg (buffer-substring-no-properties start end))
         (buffer (buffer-name)))
    (setq ensime-inf-overlay-marker (copy-marker end))
    (with-current-buffer ensime-inf-buffer-name
      (goto-char (point-max))
      (if (eq system-type 'windows-nt)
          ;; Windows
          (progn
            (comint-send-string nil s)
            (let ((comint-input-sender 'ignore)
                  (comint-input-filter-functions nil))
              (comint-send-input t t))
            (comint-send-input)
            (goto-char (process-mark (get-buffer-process (current-buffer))))
            (line-move -1)
            (right-char (length "scala> "))
            (when (and (>= (point-max) (+ (point) 3))
                       (not (equal
                             (buffer-substring (point) (+ (point) 3))
                             "res")))
              (kill-line 1))
            (comint-kill-input))
        ;; Linux
        (progn
          (comint-send-string nil ":paste\n")
          (comint-send-string nil s)
          (comint-send-string nil "\n")
          (sit-for 1)
          (comint-send-eof))))))

(advice-add 'ensime-inf-eval-region :around #'my-ensime-inf-eval-region)
```

**Comment by skp33** [comment]
Thanks @kostafey its working..
