### ISSUE TITLE
ensime stays disconnected

### ISSUE THREAD

**Issue by ahanwadi** [ensime/ensime-emacs#553]
## System Information - Ensime troubleshoot report

- OS: `darwin`
- Emacs: `25.1.1`
- ensime-sbt-command: `/usr/local/bin/sbt`
- debug-on-error: `nil`
- exec-path: `(/usr/local/bin/ /usr/local/sbin/ /usr/bin/ /bin/ /usr/sbin/ /sbin/ /usr/texbin/ /usr/local/Cellar/emacs-plus/25.1/libexec/emacs/25.1/x86_64-apple-darwin16.1.0/)`
- Backtrace:
```
Backtrace not available or not found
```
- .ensime file content:
```
Not provided
```

### Steps to reproduce

1. Create a [HelloWorld project](https://github.com/ahanwadi/HelloWorld)
2. Load the HelloWorld.scala and start ensime 
![out](https://cloud.githubusercontent.com/assets/1645382/20490229/1441f1ea-afc2-11e6-9a45-1742bc403e7d.gif)

3.
[ensime server logs and messages](https://gist.github.com/ahanwadi/2f8180d59011691124fffb161cd322a4#file-gistfile1-txt)

### Expected behaviour
Ensime modeline status should show the project name (HelloWorld in this case).

### Actual behaviour
Ensime modeline status shows disconnected even after "ENSIME ready" message.
None of ensime features such as completion, etc. work.

**Comment by ahanwadi** [comment]
I tried to debug a bit and verified that the ensime-setup-connection went through fine. ensime-list-connections shows the connection.
Nr  Name        Port               Pid    
 --  ----        ----               ---    
  1  ENSIME      (127.0.0.1 56253)  nil

But ensime-buffer-connection is still nil:
=======================================
ensime-buffer-connection is a variable defined in ‘ensime-client.el’.
Its value is nil

  Automatically becomes buffer-local when set.
========================================

I don't see any error except this:
07:45:40.613 DEBUG akka://ENSIME/user/ensime-main/project/scalac o.e.c.Analyzer - received handled message FullTypeCheckCompleteEvent from Actor[akka://ENSIME/deadLetters] in state startup

**Comment by ahanwadi** [comment]
After enabling ensime-log-messages, here is what I see:

<-- (:return (:ok (:implementation (:name ENSIME) :version 1.9.1)) 1)
Connected to ENSIME speaking protocol 1.9.1, please wait while the project is loaded.
08:33:26.252 INFO  None c.z.h.HikariDataSource - HikariPool-1 - Started.

08:33:26.731 DEBUG None o.e.i.SearchService - findStaleFileChecks

<-- (:indexer-ready)
08:33:26.738 DEBUG None o.e.i.SearchService - removing 0 stale files from the index
08:33:26.749 DEBUG None o.e.i.SearchService - Indexing bases...
08:33:26.753 DEBUG None o.e.i.SearchService - committing index to disk...
08:33:26.756 DEBUG None o.e.i.SearchService - ...done committing index
08:33:26.758 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - created 0 and removed 0 searchable rows

<-- (:background-message 105 Initializing Analyzer. Please wait...)
Initializing Analyzer. Please wait...
08:33:27.984 DEBUG akka://ENSIME/user/ensime-main/project/scalac o.e.c.Analyzer - received handled message FullTypeCheckCompleteEvent from Actor[akka://ENSIME/deadLetters] in state startup

<-- (:compiler-ready)
ENSIME ready. M-x be_cool
<-- (:full-typecheck-finished)

**Comment by fommil** [comment]
you're using dev ensime, but the gradle plugin does not yet support it. We're pretty clear about which version you're supposed to use unless you're contributing to ensime: http://ensime.github.io/editors/emacs/install/

**Comment by diego-alvarez-hs** [comment]
@ahanwadi add this to your spacemacs init to use the stable version (1.0.0) of ensime
https://github.com/d1egoaz/dotfiles/blob/master/emacs/.spacemacs#L309-L310

**Comment by fommil** [comment]
@d1egoaz can we get this made the default?

**Comment by diego-alvarez-hs** [comment]
Will do. there is a running PR but it has not being merged yet

**Comment by fommil** [comment]
Thanks Diego. ahanwadi, please let us know if that fixes it for you. If not, we'll reopen this ticket

**Comment by ahanwadi** [comment]
The stable version did not help. I then removed all .emacs.d/elpa, .ivy2, .gradle, .ensime_cache.d, and then finally it worked.

**Comment by fommil** [comment]
You mean you followed the troubleshooting guide :raised_eyebrow:
