### ISSUE TITLE
Error starting ensime

### ISSUE THREAD

**Issue by manuel-uberti** [ensime/ensime-emacs#556]
I get this error when starting latest Ensime from MELPA: http://pastebin.com/baXEtFMA
I am using `GNU Emacs 26.0.50.1 (x86_64-debian-linux-gnu, GTK+ Version 3.14.5) of 2016-11-25`.

### Steps to reproduce

1. Open a `.scala` file in a project  (this is the related `.ensime` in the root directory: http://pastebin.com/HhN5Ceze)
2. <kbd>M-x</kbd> `ensime-start`

### Expected behaviour
Server connected, ready to go.

### Actual behaviour
`Failed to connect: server process exited.` See the full error message above.

**Comment by fommil** [comment]
Can you please give a reproduction in the form of a unit or integration test? A github repository with exact instructions for somebody to follow, like a script, is also a good starting point. We are more than happy to help you turn it into an automated test, and discuss ideas on how to fix it. Read the http://ensime.org/contributing guide for more information.

We close tickets that look like a known issue or don't provide the details requested by the template, but it's not the end of the conversation and we will open it up again when there is enough information to go on. This is to improve the quality of our issue tracker and to make it easier for contributors to help.

We will reopen this ticket if you can confirm it is a bug by giving us a **detailed** reproduction. Please read the http://ensime.org/getting_help guide to understand the steps that are required prior to submitting a bug report.

**Comment by manuel-uberti** [comment]
Sorry, but how much more details can I share? I detailed the steps that lead up to the error, sharing the logs and the related `.ensime`.

Is there any other specific information you need?

**Comment by fommil** [comment]
Also read the install instructions again.

**Comment by sugakandrey** [comment]
@manuel-uberti Looks like you are using `ensime-2.0.0` and your java version is lower than `1.8`. ENSIME 2.0 requires JRE 1.8 to run.

**Comment by manuel-uberti** [comment]
Thanks. Weird though, I have `1.8` installed.

**Comment by manuel-uberti** [comment]
Thank you, @sugakandrey. I followed the Troubleshooting guide,  I cleaned everything ENSIME-related in my project, and reinstalled ENSIME from MELPA but I still had the same error.

So I edited `.ensime` and changed `:java-home "/usr/lib/jvm/java-7-openjdk-amd64"` to `:java-home "/usr/lib/jvm/java-8-openjdk-amd64". Now it ENSIME starts fine.

**Comment by sugakandrey** [comment]
Glad it helped.
