### ISSUE TITLE
have less hacky way of detecting first use

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#565]
the `~/.emacs.d/ensime` directory is a legacy thing left over from the old server installer.

**Comment by yyadavalli** [comment]
Do we actually need to detect first use?

Given the jars are now part of `.ensime` file does it matter. Also at first glance I didn't find any check for that path in the `ensime` command flow. I think we can just update the welcome message

**Comment by fommil** [comment]
yes, it's to popup the "please RTFM" buffer :smile:

**Comment by yyadavalli** [comment]
Ok, I think we are referring to the same message when I said "update the welcome message".

My suggestion is to replace the text 
> It looks like you've just installed ENSIME, welcome!

and popup the message till the user gets fed up and sets `ensime-startup-notification` to nil

**Comment by fommil** [comment]
sorry, I read your message too fast and missed that. Yup, sounds good!

**Comment by fommil** [comment]
in fact, I'm not sure why I didn't just do that before.
