### ISSUE TITLE
ci failing with "cask exec: error"

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#573]
I think the permission error is erroneous, I've checked and the drone is running as `root`

```
cask exec: error: Failed to execute ert-runner: [Errno 13] Permission denied
```

but it's clear that something is not working.

To reproduce, just create a PR with a trivial change and watch the CI fail (commands are defined in `.drone.yml`)

**Comment by fommil** [comment]
to reproduce, just create a PR with a trivial change and watch the CI fail.

**Comment by fommil** [comment]
@lunaryorn I'm aware that you're no longer maintaining cask, but I was wondering if you'd seen this before when running cask / ert-runner in docker? We're stumped.

**Comment by fommil** [comment]
@lunaryorn thanks anyway. I don't think it's `docker` specific... it looks like a python error from the little google I have. Any ideas how to get `cask` to output more debugging information? I tried `--debug` and `--verbose` but nothing.

**Comment by lunaryorn** [comment]
I do not work on Cask anymore, and I feel no longer responsible for its issues or problems.  I'm sorry, but I really cannot help you.

**Comment by fommil** [comment]
snap! @ches vim builds are failing with the same thing https://ci.fommil.com/ensime/ensime-vim/3 might be that a bad python binary is getting on the `PATH` and doesn't have the right executable bit set, or it needs docker to expose something.

**Comment by ches** [comment]
Just to restate a stab-in-the-dark theory from Gitter:

> Could there be some sort of weird umask in effect for the Docker user, causing files created in the host AUFS to have odd perms?

I don't know if I have the patience to help investigate the system environment by opening a throwaway PR and changing commands in the `.drone.yml`, versus being able to log into it…
