### ISSUE TITLE
presentation mode: REPL output to comments

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#586]
@zainab-ali gave a good talk about fs2 at hack the tower with ammonite in emacs, and it seemed that it would be way more useful to be able to give such talks in a "worksheet" style where instead of [`ensime-inf-eval-definition`](http://ensime.org/editors/emacs/cheat_sheet/#repl) (when using `ensime-overlay` #512) the output was added to the file as a line comment.

**Comment by arigoldx** [comment]
reminds me of: https://github.com/marconilanna/REPLesent

(from [Implicits Inspected and Explained - by Tim Soethout](https://www.youtube.com/watch?v=UHQbj-_9r8A&index=9&list=PLLMLOC3WM2r5gdnpoZSTuM9Fh2QN_mABA) from [Scala Days New York 2016](https://www.youtube.com/playlist?list=PLLMLOC3WM2r5gdnpoZSTuM9Fh2QN_mABA).
