### ISSUE TITLE
ensime-inf-eval-region requires ctrl-D

### ISSUE THREAD

**Issue by lambda-knight** [ensime/ensime-emacs#588]
Hi,
In my Emacs environment, ensime-inf-eval-region requires ctrl-D in a REPL screen 
to start eval. Is it correct behavior ?  I'd like to eval the region in Scala code automatically 
when I issue ensime-inf-eval-region. The following is a screen image of emacs. REPL is 
waiting for ctrl-D.

![image](https://cloud.githubusercontent.com/assets/25827631/24479290/7462db68-1519-11e7-9e90-5b829ba3881a.png)

The version of ensime is 20170318.1059.

**Comment by lambda-knight** [comment]
I tested again. It works sometime and it doesn't work sometime. I suspect my emacs setting causes the problem. I close this issue.

Thanks

**Comment by fommil** [comment]
If you can reliably reproduce, please open up a ticket. I sometimes see it too but I don't know why.

**Comment by lambda-knight** [comment]
Sure, I see it again but I don't know when that occurs.

**Comment by fommil** [comment]
I'm guessing it has to do with newlines.

**Comment by mashu** [comment]
I have the same problem, C-c C-v r asks me to press C-d in the REPL, then the code gets executed.
This is not usable, and since more people report this, this should be investigated. I doubt we all use the same "environment".

**It is also reported in separate issues "duplicates" of this!!**
For example https://github.com/ensime/ensime-emacs/issues/662

**Comment by fommil** [comment]
@mashu glad to hear that you plan on investigating this.

**Comment by mashu** [comment]
You are welcome, **steps to reproduce**

1. Create empty ~/.emacs.d
2. Use most basic init.el from http://ensime.org/editors/emacs/learning/
3. Follow tutorial http://ensime.org/editors/emacs/install/ adding three packages from maple-stable
4. C-x C-f to open scala file with just println("Hello world") example
5. M-x ensime
6. C-c C-v z to open REPL
7. Select region with emacs and press C-c C-v b which should evaluate region

Instead you will see in REPL this
`
Welcome to Scala 2.12.4 (OpenJDK 64-Bit Server VM, Java 1.8.0_151).
Type in expressions for evaluation. Or try :help.
scala> // Entering paste mode (ctrl-D to finish)
`

and you need to switch buffors to REPL and press C-D to get result. What is expected is to evaluate region immediately without the need of switching buffers and pressing additional keys.
`
GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.20) of 2017-09-12
`

**Comment by fommil** [comment]
@mashu oh, I thought you meant you were going to fix it.

**Comment by mashu** [comment]
Yes, my part in **trying to help** was related to testing with basic config your website provides, writing instructions to reproduce and information on Emacs version. 

If you find interest in fixing this, want me to test something or more information, let me know.

**Comment by fommil** [comment]
ok maybe somebody will come along. This project has no maintainer and relies on people reporting bugs to also fix them.
