### ISSUE TITLE
scalafmt support

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#591]
it would be good if `C-c C-b f` sent this (under a user / project option) https://github.com/scalameta/scalafmt/issues/873

**Comment by diego-alvarez-hs** [comment]
I'm currently doing this, I don't this is the best emacs way to do it, but it works:
https://github.com/d1egoaz/dotfiles/blob/master/emacs/spacemacs_private_layers/d1egoaz-scala/funcs.el#L17-L22

```lisp
(defun diego-scala/scalafmt-file ()
  (interactive)
  (let ((str (concat "scalafmt -f " buffer-file-name " --config=" user-home-directory ".scalafmt.conf -i --exclude ensime")))
    (message str)
    (shell-command-to-string str))
  (message "scalafmt done"))
```

**Comment by fommil** [comment]
@diego-alvarez-hs I was going to do it via the sbt command of the same name, just following exactly what the current scalariform code is doing. Do you fancy having a go at doing it that way? We could maybe have a user setting (which could be refined per project with a `.dir-locals.el`) called `ensime-sbt-formatter` which can be either scalariform or scalafmt, or maybe a string with the command that we run.

**Comment by fommil** [comment]
i.e. in sbt you can just type `scalafmt -i -f <file>` and it'll get all the correct settings automatically.

**Comment by fommil** [comment]
blocked on https://github.com/lucidsoftware/neo-sbt-scalafmt/issues/6

**Comment by fommil** [comment]
#635
