### ISSUE TITLE
compiler notes should be opt-in

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#609]
when I use a recent checkout of ensime I'm getting compiler type info and implicit notes at the point, without asking for it. This makes it unusable in complex code, can we please go back to opt-in for this? I'm assuming it's a regression from https://github.com/ensime/ensime-emacs/pull/574 @yyadavalli

**Comment by fommil** [comment]
oh, maybe we just need to make `ensime-eldoc-hints` `nil` by default

**Comment by fommil** [comment]
I can do that

**Comment by ashawley** [comment]
It's defined in `ensime-vars.el`, no?

**Comment by ashawley** [comment]
You just need to add `(require 'ensime-vars)` inside `ensime-eldoc.el`.
