### ISSUE TITLE
ensime-startup.el has outdated SNAPSHOT release detection condition (at ensime--1)

### ISSUE THREAD

**Issue by strobe** [ensime/ensime-emacs#613]
Looks like this code https://github.com/ensime/ensime-emacs/blob/master/ensime-startup.el#L144 should also handle case with "M1" (probably M2, M3, RC1 ... etc) since recommended server version is a "2.0.0-M1" (at http://ensime.org/build_tools/sbt/#server-version).

### Steps to reproduce

1.  spacemacs + ensime
2. ~/.sbt/0.13/global.sbt
```
import org.ensime.EnsimeKeys._
ensimeServerVersion in ThisBuild := "2.0.0-M1"
ensimeProjectServerVersion in ThisBuild := "2.0.0-M1"
```
3. try launch ensime at spacemacs for ensime-server project
(for some reason at latest version of spacemacs, it suppress notification after "ensime" command launched 
at interactive mode, but shows it when it launched by "M-:" ( the previous version of spacemacs doesn't do that))

### Expected behaviour
it have to try start server

### Actual behaviour
it shows notification "Your build tool has downloaded the stable version of ENSIME ... " (even "2.0.0-M1" configured at  ~/.sbt/0.13/global.sbt or at ensime.sbt ) 
(if "2.0.0-SNAPSHOT" configured at  ~/.sbt/0.13/global.sbt all works as expected)

**Comment by fommil** [comment]
The .ensime file now has the server version so we can do it over easier. Fancy sending a fix? I'm pretty busy.

**Comment by strobe** [comment]
I will try to do this, but probably not so very soon.
