### ISSUE TITLE
Emacs error: Symbol’s value as variable is void: ensime-server-version

### ISSUE THREAD

**Issue by zachncst** [ensime/ensime-emacs#616]
Running into error when trying to start ensime with latest update.

### Steps to reproduce
1. Load file
2. Start ensime

### Expected behaviour
Ensime connects

### Actual behaviour
Emacs error: `ensime: Symbol’s value as variable is void: ensime-server-version`

Appears to be related to: https://github.com/ensime/ensime-emacs/commit/f1ca2bd6de9b4e7eabe198ada75196183a1862c0

#### global.sbt
```
import org.ensime.EnsimeKeys._
ensimeServerVersion in ThisBuild := "2.0.0-M1" // or "1.0.1"
ensimeProjectServerVersion in ThisBuild := "2.0.0-M1" // or "1.0.1"

ensimeJavaFlags in ThisBuild := Seq("-Xss2m", "-Xmx2g", "-XX:MaxMetaspaceSize=512m")
```
#### plugins.sbt
```
addSbtPlugin("org.ensime" % "sbt-ensime" % "1.12.11")
```

**Comment by fommil** [comment]
normally I'd say you need to share a project ... but in this case it may be obvious to see what is happening by inspection. Would you like to send a PR to fix?

**Comment by fommil** [comment]
actually, this is trivial, I'll push a fix.

**Comment by fommil** [comment]
should be fixed when melpa refreshes in an hour or so

**Comment by zachncst** [comment]
Ah bummer, I was about to submit the PR. :+1: Thanks for the prompt response.

**Comment by fommil** [comment]
our CI is bust, otherwise we would have caught this. I don't have time to fix it... but I wouldn't force that task on anybody.
