### ISSUE TITLE
·Alt + x: ensime-connect· can lead to repeat error message

### ISSUE THREAD

**Issue by yangwen0228** [ensime/ensime-emacs#621]
### Steps to reproduce

1. In project A: `Alt+x: ensime` to start the ensime-server -> 127.0.0.1:88888;
2. In project B: `Alt+x: ensime-connect` to 127.0.0.1:88888;
3. Enter y or n.

### Expected behaviour
Project B connect to the server.
...

### Actual behaviour
Repeated error message:
Error running timer ‘ensime-idle-typecheck-function’: (error "Cache dir in ensime configuration file appears to be unset")
...

**Comment by fommil** [comment]
you can only have one project per server, sorry this is by design and would require a huge change on the server.

**Comment by fommil** [comment]
by "project" I assume we mean "build". A server supports multi-project builds.

**Comment by yangwen0228** [comment]
Haha, Thank you! I understand! I just want to start a server as deamon in the background, and connect all the projects to the server. It seems that the server doesn't support it right now? If this is very complicated to implement, then it's fine. I love ensime! Thank you very much!

**Comment by fommil** [comment]
It's one process per project. Changing that would be a rewrite, each server is coupled to a .ensime file.
