### ISSUE TITLE
ensime-company: can we omit these candidates, like: CollectionMapper$ListClass

### ISSUE THREAD

**Issue by yangwen0228** [ensime/ensime-emacs#622]
### Steps to reproduce

1. Put ensime-company in the company-backends.
2. Type List

### Expected behaviour
Company candidates:
List
ListAssert
ListBuffer
...

### Actual behaviour
Company candidates:
CollectionMapper$ListClass
CollectionMapper$ListType
JSpinner$ListEditor
...
List
...

I think we can omit those candidates contain a "$" by a filter? Any suggestions is welcome! Thank you!

**Comment by fommil** [comment]
(see discussion in the PR)
