### ISSUE TITLE
UTF-8 chars (like Chinese chars) in comments can lead to compiler's range calculation issue

### ISSUE THREAD

**Issue by yangwen0228** [ensime/ensime-emacs#624]
@fommil Can you help me to solve this problem?
### Steps to reproduce

1. Type some Chinese chars in comment or print strings. like `// 中文`
2. Type the normal code `mm`

### Expected behaviour

`ensime-company` shows nothing or  variables prefixed with `mm`

### Actual behaviour
`ensime-company` candidates contain `main(args: java.lang.String[])`

**Comment by fommil** [comment]
Oh sorry, I meant please raise it at https://github.com/scala/bug

You'll need to have compilable code, not just a snippet. I can help you write it up as a pcplod test but I hope we can write it up using the compiler's test suite.

**Comment by fommil** [comment]
The completions thing is related, having bad syntax highlighting after the comment is a stronger indicator of the problem.

**Comment by yangwen0228** [comment]
Oh, sorry. I encountered this kind of problem years before, when I used the `company-irony` for `cc-mode`. I remember I wrote some lisp codes to re-calculate the string length and ranges before sending the buffer string to the server, and that works. So I don't know whether `ensime-server` works the same way as `irony-server` or not? Maybe I can manage to figure it out `later`, after read more `ensime-server` codes. I solve little problems with servers before. So just forgive me! 😄

**Comment by fommil** [comment]
Oh! So this is an ensime bug not scala? If you could investigate that first in would be good but you could also try writing a pcplod test.

**Comment by fommil** [comment]
i.e. please raise here if you don't think emacs is to blame https://github.com/scala/bug/issues/

**Comment by yangwen0228** [comment]
Sorry for the late reply. I didn;t get the time to figure it out these days. Today, I find that it's not an issue from Emacs side. In `JavaCompiler.scala` line154:
`contents.getOrElse(f.readStringDirect)`
The `readStringDirect` function always encode the file using the defaultCharset(or encoding, `GBK` in my computer), but my file is `utf-8` encoded. Then the file contents is origin `utf-8`, then converted to `GBK`, after that, converted back to `utf-8`. If there is odd Chinese char, it will be parsed like `\342\342?`.

However, more weird thing is that even I don't use the `readStringDirect` function, and just use the `Scanner` `utf-8` encoding to read a `utf-8` file (like, test.txt), the result is not correct. It seems that in ensime the test.txt is always converted to `GBK` encoding, then use the `utf-8` to decode:

`origin(utf-8) -> ensime read -> always auto convert (GBK) -> convert back (utf-8)`

If I use the same code in a separate Java file or Scala file, the result is correct. So there may be a problem in the ensimefile read, however, I can't tell where the problem comes from.

**Comment by fommil** [comment]
ok, let's move this to the ensime-server tracker. Can you please raise a ticket there and try to create a unit test? Or a small test project that somebody could look at. When describing a problem, be as specific as possible... include exact public projects, filenames and actions.

**Comment by fommil** [comment]
btw, my computer can't render Chinese characters so I had no way to reproduce the problem. It really wasn't clear to me that you were talking about Java, not Scala, files. This is why exact projects/files/actions are critical for bug reproductions.

**Comment by yangwen0228** [comment]
After a long time, I get some time to play ensime again, and find a ugly solution.

I find that this problem only happened to GBK localed system. In Macos or Linux, we set the default locale to utf-8, we won't get this kind of problem. 

But if we use Windows, and use multibyte encoding as default, like China, Japan, etc. Then this problem occurs. So I just simulate the process to calculate the according offset in Ensime. Now, it works just like a charm no matter whether there are Chinese chars or not in comments. `But this can't work in non GBK locale enviroment`, actually, if we can use a function to detect the system's default locale, we can write a general function, inteady of hard coded `gbk` here.

```
(defun ensime-externalize-offset (offset)
  ;; Locale GBK & Chinese chars: @https://github.com/ensime/ensime-emacs/issues/624
  (let ((before-string (buffer-substring-no-properties 1 offset))
        offset-unicode)
    (if (= (length before-string) (string-bytes before-string))
        (+ offset (- ensime-ch-fix)
           (if (eq 1 (coding-system-eol-type buffer-file-coding-system))
               (save-restriction
                 (widen)
                 (1- (line-number-at-pos offset)))
             0))
      ;; Simulate the GBK locale: Chinese convert to gbk, then convert back.
      (setq offset-unicode (length (decode-coding-string
                                    (decode-coding-string
                                     (encode-coding-string before-string 'utf-8)
                                     'gbk)
                                    'utf-8)))
      (+ offset-unicode 1 (- ensime-ch-fix)
         (if (eq 1 (coding-system-eol-type buffer-file-coding-system))
               (save-restriction
                 (widen)
                 (1- (line-number-at-pos offset)))
             0)))))
```

This may be very useful to the multibyte language Windows users, so I just put the solution here. 
Of course, it is prefered if we can configure the encoding in Ensime somewhere someday.

**Comment by yangwen0228** [comment]
Maybe we can define a variable like `ensime-system-locale` as a workaround at this stage. And use the variable to rewrite the `ensime-externalize-offset` to make it  work more generally.
