### ISSUE TITLE
huge cpu consumption and memory leak during ensime-typecheck-current-buffer

### ISSUE THREAD

**Issue by ahanwadi** [ensime/ensime-emacs#629]
### Steps to reproduce

1. Open a large scala file and run ensime-typecheck-buffer a few times.
2. Each time the buffer local variable face-remapping-alist will keep on growing 
3. You should also see progressively higher cpu consumption and memory usage

### Expected behaviour
cpu and memory usage should not increase with additional typecheck invocations.

### Actual behaviour
memory and cpu usage keeps on growing linearly and exponentially respectively.

**Comment by fommil** [comment]
@ahanwadi you need to provide an actual project and further evidence than this. I'd normally close a ticket that didn't have that level of information, but if you're looking into this I'll leave it open.

**Comment by arigoldx** [comment]
also it's `ensime-typecheck-current-buffer` (to be precise), ain't it?

**Comment by arigoldx** [comment]
aaaaalso, i tried those steps and `face-remapping-alist` ain't growing.

neither does the cpu or memory do much.

hmm!

**Comment by ahanwadi** [comment]
https://github.com/ensime/ensime-emacs/pull/630

**Comment by ahanwadi** [comment]
When you invoke face-remap-replace-relative, you get a cookie that you need to store. The pull request I referenced in the earlier comment, stores the cookie in a buffer local variable and avoid calling face-remap-replace-relative again if the cookie is non-nil.
