### ISSUE TITLE
cannot exit emacs after start ensime, even after kill all buffers.

### ISSUE THREAD

**Issue by hackrole** [ensime/ensime-emacs#634]
If you've come straight to the issue tracker out of habit, you might want to read the [Troubleshooting Guide](http://ensime.github.io/editors/emacs/troubleshooting/) as it has some steps that solve the vast majority of suspected bugs.

If it still looks like a bug and you've come back here, be aware that there is very little we can do unless you provide us with a reproduction of the problem:

1. a standalone (ideally minimal) project on github
2. step by step instructions to trigger the bug (videos are useful)
3. commit your `.ensime` into the repository (or in a gist)
4. commit all your server / client logs into the repository (or in a gist).

The next step is for us to help you create a test that fails. You may want to get a head start by reading the [Contributing](http://ensime.github.io/contributing/) documentation. You have all the skills you'll need to make ENSIME even better.

We'll give as much help as we can, our goal is to grow this community.

Now, delete this line and everything above it, then complete the following template:

### Steps to reproduce

1.  start emacs, use helm-projectile to open dired of the scala project
2. M-x ensime, it says connected. the ensime works ok.
3. after a while I would to exit emacs with C-x C-c. It not works.

### Expected behaviour
exit emacs
...

### Actual behaviour
report errors:
sbt:command: You’re not in an sbt project.  Maybe build.sbt or build.scala is missing?  See http://ensime.org/build_tools
...

**Comment by fommil** [comment]
if you cannot exit emacs, that is an emacs bug. workaround is to use `kill -9 emacs`
