### ISSUE TITLE
scalafmt support

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#635]
blocked on https://github.com/lucidsoftware/neo-sbt-scalafmt/issues/6

workaround for now is to do full compile from emacs

```lisp
(defun ensime-sbt-do-fmt ()
  "WORKAROUND "
  (interactive)
  (sbt:command "fmt"))

(bind-key "C-c C-v F" 'ensime-sbt-do-fmt scala-mode-map)
```

defining that `fmt` in sbt as

```scala
addCommandAlias("fmt", ";scalafmt ;test:scalafmt ;it:scalafmt")
```

**Comment by yyadavalli** [comment]
What's opinion on integrating with scalafmt CLI?

I think it may be better because it will remove any dependency on sbt for simple task like formatting.

**Comment by fommil** [comment]
@yyadavalli I guess that could go into `scala-mode` or something. Isn't it kind of trivial?

I don't like the CLI because

- it's dumb and doesn't pay attention to the project structure (e.g. it reformats ensime's test projects, which have to have lines preserved for test assertions)
- it's hella slow because it starts a fresh JVM every time
- it's not version controlled

**Comment by yyadavalli** [comment]
Hmm, yeah makes sense. I think it is trivial to add it to `scala-mode`.

I use it with nailgun and always use the `--file` option to avoid that issue. 

But your assessment is reasonable we should wait for (or add) `neo-sbt-scalafmt` to support file formatting and integrate with it.

**Comment by beyondpie** [comment]
@fommil , thanks a lot for the ensime, and I now use it everyday.

scalafmt works when the scala project itself is under maven or other project management tools instead of sbt. Is it possible to support different ways of formatting?
