### ISSUE TITLE
Cannot add helm-gtags hook to Scala/ensime hook

### ISSUE THREAD

**Issue by ccqpein** [ensime/ensime-emacs#636]
I write `(add-hook 'scala-mode-hook 'helm-gtags-mode)` and `(add-hook 'ensime-mode-hook 'helm-gtags-mode)` in my init file but `helm-gtags` still not run automaticly when I open scala file. I have run it with `M-x helm-gtags-mode` everytime.

helm-gtags-hook works well on other languages mode including haskell, python, clojure, or lisp. 

How can I fix ti

**Comment by fommil** [comment]
thank you for completely ignoring the template.
