### ISSUE TITLE
create test is broken

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#637]
because it's using the removed `type-by-name` call

```
  ensime-eval((swank:type-by-name "my.thing.GzipSpec"))
```

1. these type-by-name methods should be removed
2. this feature should be rewritten to solve the problem a different way
3. when this happens, it shouldn't knock out the ensime connection

**Comment by Bernolt** [comment]
@fommil Thanks for your indications, I am trying to understand and make a fix.

**Comment by fommil** [comment]
Look at how the ensime-sbt-do methods determine the project name and config. Rely on the config information instead of talking to the server.

There are related tickets to take config info easier to obtain, e.g. as local variables.

**Comment by fommil** [comment]
we should rewrite calls that use `ensime-rpc-get-type-by-name` (removed server side) to use https://github.com/ensime/ensime-server/blob/2.0/api/src/main/scala/org/ensime/api/incoming.scala#L125 `PublicSymbolSearchReq` which returns a https://github.com/ensime/ensime-server/blob/2.0/api/src/main/scala/org/ensime/api/outgoing.scala#L271 `SymbolSearchResults` and preferably add new search query endpoints that refine the response type, e.g. "search for exact methods having this fqn"

**Comment by fommil** [comment]
oh, it's the server that crashes when it gets bad input. Hmm. That might well be the correct behaviour.
