### ISSUE TITLE
Find Usages

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#646]
Emacs support for https://github.com/ensime/ensime-server/pull/1830

Ideally we'd render the results in a `compilation-mode` that looks like the results of a call to `grep` and let Emacs just take care of it from there.

Ivy / Helm users may want some customised rendering view that they can add later.

**Comment by bomgar** [comment]
What does `ensime-show-uses-of-symbol-at-point` actually do? It sounds like the right thing.

**Comment by fommil** [comment]
It probably brown up right now, that call was deleted from the server. It had some very complex rendering that we should delete.
