### ISSUE TITLE
classic search

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#657]
somewhat related to #186 (which would be interactive search) I think I would use a version of `ensime-search` that simply searches for a fixed string and shows the results using the "classic" (ivy/helm) mode would be far better.

// @bomgar would be your sort of thing :smile:

**Comment by bomgar** [comment]
see https://github.com/ensime/ensime-emacs/pull/666

**Comment by fommil** [comment]
The devil's PR!!!
