### ISSUE TITLE
License of package

### ISSUE THREAD

**Issue by matsl** [ensime/ensime-emacs#658]
Hi,

Could not find any other contact info so opening an issue for this license request.

In a thread in the emacs-devel maillist, the licensing situation for emacs packages provided through Emacs package archives has been under focus. I have volunteered to contact the authors of packages that have a license that is incompatible with Emacs, which is now under GPL-3+.

See https://lists.gnu.org/archive/html/emacs-devel/2017-07/msg01069.html                                                                                                     

So I wonder if you could consider to change the license of your package to GPL-3+?

**Comment by fommil** [comment]
it is GPLv3, which as I understand it implies 3+ (ever since the 2+ debacle) but since RMS is asking then I'm happy to do it. Please send a PR, it's easier for all of us.

**Comment by fommil** [comment]
btw, I am surprised that CC-BY-SA 3.0 is incompatible. That's the license we use for our website. Is 4.0 compatible?

**Comment by matsl** [comment]
Sorry for being a bit brief in the initial issue text. Using a standard text for contacting multiple projects. The license text file you provide does say it is GPLv3 with is great. What is missing is the the copying permission statement text that should be part of every file. See https://www.gnu.org/licenses/gpl-howto.html for detail. 

Thanks for suggesting a PR from me. Feel free to beat me to it!

I don't understand the CC-BY-SA 3.0 issue with your website. This is only about the emacs package. As I get it from searching the net using CC-BY-SA 4.0 would be compatible with GPLv3 but I'm not an expert on this.

**Comment by matsl** [comment]
According to the FSF pages, as I read them, it is not legally recommended, but if you choose a one liner please use something like this ";; License: GPL version 3, or (at your option) any later version", so that the "any later version"-option still is clearly communicated.

**Comment by fommil** [comment]
My lawyer is quite happy with a one liner, and the Scala community is very much aware that I'm the kind of person who who sue the hell out of anybody who messes with the freedom of my software.
