### ISSUE TITLE
Crypting error while using any of ensime features

### ISSUE THREAD

**Issue by schvabodka-man** [ensime/ensime-emacs#663]
Leave this list and include an `x` in the relevant boxes:

- [x] I have followed http://ensime.org/editors/emacs/troubleshooting/
- [x] I have followed the troubleshooting guide for my build tool
- [ ] I have asked in http://gitter.im/ensime/ensime-emacs
- [ ] I have included a link to an example project
- [ ] I have included exact bug reproduction instructions

Well, I've added parameters to my build.sbt to download deps with sources(for better autocompletition) and javadocs, I obliviously removed old .ensime file and .ensime_cache. I generated new ensime file and now when I'm trying to do most of the operations(like import suggest) I'm getting this
`Wrong number of arguments: #[nil "Àed\"" [ensime-inf-eval-region] 3 ("/home/user/.emacs.d/elpa/ensime-20170817.2325/ensime-inf.elc" . 9720) nil], 1` 
I was trying to regenerate .ensime and cleaning ensime_cache, reinstalling ensime but none of this helped

**Comment by fommil** [comment]
Ask in the gitter room. I recommend following the trouble shooting guide again.
