### ISSUE TITLE
Automatic "package"

### ISSUE THREAD

**Issue by schvabodka-man** [ensime/ensime-emacs#664]
Hello there! I don't see this valuable feature bit it would be nice if ensime just can do automatic package-path(i.e "package com.apps.example" and etc) because writing it each time when creating new class is annoying(or maybe there is such feature but i don't see it in documentation)

**Comment by fommil** [comment]
yeah, I know what you mean... I have this hack which could work for you https://github.com/fommil/dotfiles/blob/master/.emacs.d/init.el#L615-L634

But it could be implemented in a much cleaner way by getting the dir base from `.ensime`

**Comment by fommil** [comment]
btw, generally for file templates look for `yatemplate` under http://ensime.org/editors/emacs/hacks/

**Comment by schvabodka-man** [comment]
I'm actually using yatemplate. It would be A LOT nicer if there would be nice function to make package-path instead of dirty hacks

**Comment by schvabodka-man** [comment]
Update:
For some reasons your hack doesn't work for me. Hehe

**Comment by fommil** [comment]
It would be great if you wrote something that used .ensime, but unfortunately our mechanism for finding the .ensime is very inefficient... there is a ticket for that.

**Comment by schvabodka-man** [comment]
Aren't ensime by itself supposed to store location of sources and .ensime file by itself in some val?

**Comment by fommil** [comment]
Yeah but finding it in the first place is kind of backwards... it should be rewritten
