### ISSUE TITLE
relative grep paths (e.g. hierarchy) don't work from the source dirs

### ISSUE THREAD

**Issue by fommil** [ensime/ensime-emacs#665]
if I do a hierarchy request when viewing a file from an external dependency, following the grep link doesn't work because emacs doesn't know where the base is... doh!

// @bomgar

**Comment by bomgar** [comment]
I'm having trouble reproducing this. I tried `scala.Some` and the link to `java.lang.Object` works for me.

**Comment by fommil** [comment]
ah, I can see why that would work. But links back into your project won't work. It's a pretty niche usecase.
