### ISSUE TITLE
Symbol’s function definition is void: ensime-is-test-file

### ISSUE THREAD

**Issue by vyachb** [ensime/ensime-emacs#669]
The `ensime-format-source` function bound to `C-c C-v f` doesn't work due to missing function definition.

OS X
Emacs 25.3
SBT 1.0.2

ensime-2.0.1
sbt-mode-20170820.924
scala-mode-20170802.432

- [ x ] I have followed http://ensime.org/editors/emacs/troubleshooting/
- [ x ] I have followed the troubleshooting guide for my build tool
- [ x ] I have asked in http://gitter.im/ensime/ensime-emacs
- [    ] I have included a link to an example project
- [ x ] I have included exact bug reproduction instructions

**Comment by prassee** [comment]
the same error is observed in the following cases as well

C-c C-b C - to compile the current file 
C-c C -t t - to navigate to the test class of the class under cursor

**Comment by tlegutko** [comment]
The missing function was removed in commit https://github.com/ensime/ensime-emacs/commit/f441455b53628840de5a3a5885d94002c86b688c.

By the way emacs docs for `ensime-format-source` suggest it's deprecated and `ensime-sbt-do-scalariform-only` should be used instead, but it suffers from this exact same bug.

**Comment by fommil** [comment]
Nobody is maintaining this project, you need to send a PR reviving the function if you want a fix.

**Comment by tlegutko** [comment]
I understand.

After recursively evaluating functions and variables from before deletion took place, I've managed to get this function to locally call ensime-sbt correctly, however scalariform seems to have been recently removed from ensime-sbt in https://github.com/ensime/ensime-sbt/commit/073a7a3b9a070896e66cbb7da10d9afca01d9693 along with tests and everything.

So I guess this feature is considered to be dropped and in order to get formatting, https://github.com/sbt/sbt-scalariform has to be used locally? And eventual PR would be to just update the docs about it?

EDIT: Oh, I've found https://github.com/ensime/ensime-server/issues/1874 and/or https://github.com/ensime/ensime-emacs/issues/635 so maybe there's hope

By the way, using package from melpa there is info about
```
2. the 3.0 server requires big changes on the emacs side that
   have not yet been implemented.
```
Is there more info to read about changes needed in ensime-emacs for enime-server 3.0? I couldn't find it.

**Comment by fommil** [comment]
Ask in the gitter room.

There is a ticket in upstream sbt-scalariform to add the format only task there. Best speak up there and ideally send a PR porting the feature that used to be in sbt-ensime.

1874 is about using scalafmt on the server code, not what you think. Basically formatting is the job of a formatting tool, not ensime. 635 is about the most integration ensime should do (i.e. convenient way to call external functionality)

**Comment by fommil** [comment]
i,e, everybody interested in this ticket should be looking at https://github.com/sbt/sbt-scalariform/issues/68

**Comment by fommil** [comment]
(and replacing the removed function with something that reads the new .ensime file format)

**Comment by gregnwosu** [comment]
can we have the feature complete ensime in melpa-stable please? I know this is more a bug with scalariform but I would rather like to be able to get a stable version which i can trust to work despite where the issues may come from.

**Comment by fommil** [comment]
@gregnwosu sure, just send a PR with a fix

**Comment by prassee** [comment]
is this still not fixed. How can I use ensime on large project

**Comment by yyadavalli** [comment]
@prassee do you mean the format functionality? That's removed from the sbt-ensime so cannot be supported.

I suggest you use neo-sbt-scalafmt for the whole project.

**Comment by prassee** [comment]
I meant the command that compiles current file alone.

**Comment by yyadavalli** [comment]
It should be available with sbt 0.13, but yet to be implemented in sbt 1.0

**Comment by prassee** [comment]
I still faced the issue with sbt 0.13.15

**Comment by yyadavalli** [comment]
Ohk, maybe I'm forgetting something. Can you try running it sbt shell and if that works, post a debug of why it is failing with emacs and I will fix it.

**Comment by prassee** [comment]
@yyadavalli but this is a emacs related issue, help me understand how this is related to sbt.

**Comment by yyadavalli** [comment]
@prassee @kurnevsky Please test #680 if you can

**Comment by yyadavalli** [comment]
It is on `melpa-stable` now.
