### ISSUE TITLE
company variable is shadowed by ensime-company

### ISSUE THREAD

**Issue by rski** [ensime/ensime-emacs#675]
ensime-company.el defcustoms `company-minimum-prefix-length`, I guess that should be `ensime-company-mimimum-prefix-length`? 

See c2a632a4b59d79db59c071985835a0077cb734cd

I'd change it myself, but I haven't written scala in a while so it would take me ages to setup an ensime project to test any changes.

**Comment by yyadavalli** [comment]
The change is small enough, I'd merge it if you open a PR.

**Comment by rski** [comment]
It's a breaking change so i'm not sure how you'd want to handle that. Plus I just noticed that you need a CLA to be signed, so I'd have to ask my company if they are ok with it since they hold copyright for my code, which is just not worth the hassle for me since I don't even use ensime anymore, sorry.

**Comment by yyadavalli** [comment]
That's okay I'll take care of it later.
