### ISSUE TITLE
[RFC] Testing Frameworks

### ISSUE THREAD

**Issue by yyadavalli** [ensime/ensime-emacs#679]
I recently came across [emacs-buttercup](https://github.com/jorgenschaefer/emacs-buttercup/) and I thought this would be a good time to have a discussion and get any thoughts on what testing frameworks to use. I think some of the options available to us are
  - ERT
  - ecukes
  - buttercup

I believe it would be good to choose one and use it throughout.

One project that I know uses buttercup is [flycheck](https://github.com/flycheck/flycheck).

@fommil @bomgar @iravid

**Comment by fommil** [comment]
looks nice, I've never used anything except ert but I'm all for *any* testing!
