### ISSUE TITLE
Revive ensime-goto-test

### ISSUE THREAD

**Issue by valencik** [ensime/ensime-emacs#681]
`ensime-goto-test` was found to be not working and removed in https://github.com/ensime/ensime-emacs/commit/f441455b53628840de5a3a5885d94002c86b688c
It was originally introduced in the following PR: https://github.com/ensime/ensime-emacs/pull/28

I'm opening this issue to start a dialog about the work required to bring this feature back.

Note, a revival is likely related to some of the work accomplished in https://github.com/ensime/ensime-emacs/issues/669

CC @yyadavalli

**Comment by fommil** [comment]
I think this is a dupe of https://github.com/ensime/ensime-emacs/issues/637 I added some thoughts there
